// Code generated by go-swagger; DO NOT EDIT.

package cloud

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// CloudTargetCollectionGetURL generates an URL for the cloud target collection get operation
type CloudTargetCollectionGetURL struct {
	AccessKey                    *string
	AuthenticationType           *string
	AzureAccount                 *string
	CapURL                       *string
	CertificateValidationEnabled *bool
	ClusterName                  *string
	ClusterUUID                  *string
	Container                    *string
	Fields                       []string
	IpspaceName                  *string
	IpspaceUUID                  *string
	MaxRecords                   *int64
	Name                         *string
	OrderBy                      []string
	Owner                        *string
	Port                         *int64
	ProviderType                 *string
	ReadLatencyWarningThreshold  *int64
	ReturnRecords                *bool
	ReturnTimeout                *int64
	Scope                        *string
	Server                       *string
	ServerSideEncryption         *string
	SnapmirrorUse                *string
	SslEnabled                   *bool
	SvmName                      *string
	SvmUUID                      *string
	URLStyle                     *string
	UseHTTPProxy                 *bool
	Used                         *int64
	UUID                         *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *CloudTargetCollectionGetURL) WithBasePath(bp string) *CloudTargetCollectionGetURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *CloudTargetCollectionGetURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *CloudTargetCollectionGetURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/cloud/targets"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var accessKeyQ string
	if o.AccessKey != nil {
		accessKeyQ = *o.AccessKey
	}
	if accessKeyQ != "" {
		qs.Set("access_key", accessKeyQ)
	}

	var authenticationTypeQ string
	if o.AuthenticationType != nil {
		authenticationTypeQ = *o.AuthenticationType
	}
	if authenticationTypeQ != "" {
		qs.Set("authentication_type", authenticationTypeQ)
	}

	var azureAccountQ string
	if o.AzureAccount != nil {
		azureAccountQ = *o.AzureAccount
	}
	if azureAccountQ != "" {
		qs.Set("azure_account", azureAccountQ)
	}

	var capURLQ string
	if o.CapURL != nil {
		capURLQ = *o.CapURL
	}
	if capURLQ != "" {
		qs.Set("cap_url", capURLQ)
	}

	var certificateValidationEnabledQ string
	if o.CertificateValidationEnabled != nil {
		certificateValidationEnabledQ = swag.FormatBool(*o.CertificateValidationEnabled)
	}
	if certificateValidationEnabledQ != "" {
		qs.Set("certificate_validation_enabled", certificateValidationEnabledQ)
	}

	var clusterNameQ string
	if o.ClusterName != nil {
		clusterNameQ = *o.ClusterName
	}
	if clusterNameQ != "" {
		qs.Set("cluster.name", clusterNameQ)
	}

	var clusterUUIDQ string
	if o.ClusterUUID != nil {
		clusterUUIDQ = *o.ClusterUUID
	}
	if clusterUUIDQ != "" {
		qs.Set("cluster.uuid", clusterUUIDQ)
	}

	var containerQ string
	if o.Container != nil {
		containerQ = *o.Container
	}
	if containerQ != "" {
		qs.Set("container", containerQ)
	}

	var fieldsIR []string
	for _, fieldsI := range o.Fields {
		fieldsIS := fieldsI
		if fieldsIS != "" {
			fieldsIR = append(fieldsIR, fieldsIS)
		}
	}

	fields := swag.JoinByFormat(fieldsIR, "csv")

	if len(fields) > 0 {
		qsv := fields[0]
		if qsv != "" {
			qs.Set("fields", qsv)
		}
	}

	var ipspaceNameQ string
	if o.IpspaceName != nil {
		ipspaceNameQ = *o.IpspaceName
	}
	if ipspaceNameQ != "" {
		qs.Set("ipspace.name", ipspaceNameQ)
	}

	var ipspaceUUIDQ string
	if o.IpspaceUUID != nil {
		ipspaceUUIDQ = *o.IpspaceUUID
	}
	if ipspaceUUIDQ != "" {
		qs.Set("ipspace.uuid", ipspaceUUIDQ)
	}

	var maxRecordsQ string
	if o.MaxRecords != nil {
		maxRecordsQ = swag.FormatInt64(*o.MaxRecords)
	}
	if maxRecordsQ != "" {
		qs.Set("max_records", maxRecordsQ)
	}

	var nameQ string
	if o.Name != nil {
		nameQ = *o.Name
	}
	if nameQ != "" {
		qs.Set("name", nameQ)
	}

	var orderByIR []string
	for _, orderByI := range o.OrderBy {
		orderByIS := orderByI
		if orderByIS != "" {
			orderByIR = append(orderByIR, orderByIS)
		}
	}

	orderBy := swag.JoinByFormat(orderByIR, "csv")

	if len(orderBy) > 0 {
		qsv := orderBy[0]
		if qsv != "" {
			qs.Set("order_by", qsv)
		}
	}

	var ownerQ string
	if o.Owner != nil {
		ownerQ = *o.Owner
	}
	if ownerQ != "" {
		qs.Set("owner", ownerQ)
	}

	var portQ string
	if o.Port != nil {
		portQ = swag.FormatInt64(*o.Port)
	}
	if portQ != "" {
		qs.Set("port", portQ)
	}

	var providerTypeQ string
	if o.ProviderType != nil {
		providerTypeQ = *o.ProviderType
	}
	if providerTypeQ != "" {
		qs.Set("provider_type", providerTypeQ)
	}

	var readLatencyWarningThresholdQ string
	if o.ReadLatencyWarningThreshold != nil {
		readLatencyWarningThresholdQ = swag.FormatInt64(*o.ReadLatencyWarningThreshold)
	}
	if readLatencyWarningThresholdQ != "" {
		qs.Set("read_latency_warning_threshold", readLatencyWarningThresholdQ)
	}

	var returnRecordsQ string
	if o.ReturnRecords != nil {
		returnRecordsQ = swag.FormatBool(*o.ReturnRecords)
	}
	if returnRecordsQ != "" {
		qs.Set("return_records", returnRecordsQ)
	}

	var returnTimeoutQ string
	if o.ReturnTimeout != nil {
		returnTimeoutQ = swag.FormatInt64(*o.ReturnTimeout)
	}
	if returnTimeoutQ != "" {
		qs.Set("return_timeout", returnTimeoutQ)
	}

	var scopeQ string
	if o.Scope != nil {
		scopeQ = *o.Scope
	}
	if scopeQ != "" {
		qs.Set("scope", scopeQ)
	}

	var serverQ string
	if o.Server != nil {
		serverQ = *o.Server
	}
	if serverQ != "" {
		qs.Set("server", serverQ)
	}

	var serverSideEncryptionQ string
	if o.ServerSideEncryption != nil {
		serverSideEncryptionQ = *o.ServerSideEncryption
	}
	if serverSideEncryptionQ != "" {
		qs.Set("server_side_encryption", serverSideEncryptionQ)
	}

	var snapmirrorUseQ string
	if o.SnapmirrorUse != nil {
		snapmirrorUseQ = *o.SnapmirrorUse
	}
	if snapmirrorUseQ != "" {
		qs.Set("snapmirror_use", snapmirrorUseQ)
	}

	var sslEnabledQ string
	if o.SslEnabled != nil {
		sslEnabledQ = swag.FormatBool(*o.SslEnabled)
	}
	if sslEnabledQ != "" {
		qs.Set("ssl_enabled", sslEnabledQ)
	}

	var svmNameQ string
	if o.SvmName != nil {
		svmNameQ = *o.SvmName
	}
	if svmNameQ != "" {
		qs.Set("svm.name", svmNameQ)
	}

	var svmUUIDQ string
	if o.SvmUUID != nil {
		svmUUIDQ = *o.SvmUUID
	}
	if svmUUIDQ != "" {
		qs.Set("svm.uuid", svmUUIDQ)
	}

	var uRLStyleQ string
	if o.URLStyle != nil {
		uRLStyleQ = *o.URLStyle
	}
	if uRLStyleQ != "" {
		qs.Set("url_style", uRLStyleQ)
	}

	var useHTTPProxyQ string
	if o.UseHTTPProxy != nil {
		useHTTPProxyQ = swag.FormatBool(*o.UseHTTPProxy)
	}
	if useHTTPProxyQ != "" {
		qs.Set("use_http_proxy", useHTTPProxyQ)
	}

	var usedQ string
	if o.Used != nil {
		usedQ = swag.FormatInt64(*o.Used)
	}
	if usedQ != "" {
		qs.Set("used", usedQ)
	}

	var uuidQ string
	if o.UUID != nil {
		uuidQ = *o.UUID
	}
	if uuidQ != "" {
		qs.Set("uuid", uuidQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *CloudTargetCollectionGetURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *CloudTargetCollectionGetURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *CloudTargetCollectionGetURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on CloudTargetCollectionGetURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on CloudTargetCollectionGetURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *CloudTargetCollectionGetURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
