// Code generated by go-swagger; DO NOT EDIT.

package s_a_n

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FcpServiceCollectionGetHandlerFunc turns a function with the right signature into a fcp service collection get handler
type FcpServiceCollectionGetHandlerFunc func(FcpServiceCollectionGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn FcpServiceCollectionGetHandlerFunc) Handle(params FcpServiceCollectionGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// FcpServiceCollectionGetHandler interface for that can handle valid fcp service collection get params
type FcpServiceCollectionGetHandler interface {
	Handle(FcpServiceCollectionGetParams, interface{}) middleware.Responder
}

// NewFcpServiceCollectionGet creates a new http.Handler for the fcp service collection get operation
func NewFcpServiceCollectionGet(ctx *middleware.Context, handler FcpServiceCollectionGetHandler) *FcpServiceCollectionGet {
	return &FcpServiceCollectionGet{Context: ctx, Handler: handler}
}

/*
	FcpServiceCollectionGet swagger:route GET /protocols/san/fcp/services SAN fcpServiceCollectionGet

Retrieves FC Protocol services.
### Expensive properties
There is an added computational cost to retrieving values for these properties. They are not included by default in GET results and must be explicitly requested using the `fields` query parameter. See [`Requesting specific fields`](#Requesting_specific_fields) to learn more.
* `statistics.*`
* `metric.*`
### Related ONTAP commands
* `vserver fcp show`
### Learn more
* [`DOC /protocols/san/fcp/services`](#docs-SAN-protocols_san_fcp_services)
*/
type FcpServiceCollectionGet struct {
	Context *middleware.Context
	Handler FcpServiceCollectionGetHandler
}

func (o *FcpServiceCollectionGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFcpServiceCollectionGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
