// Code generated by go-swagger; DO NOT EDIT.

package s_a_n

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewIgroupDeleteParams creates a new IgroupDeleteParams object
// with the default values initialized.
func NewIgroupDeleteParams() IgroupDeleteParams {

	var (
		// initialize parameters with default values

		allowDeleteWhileMappedDefault = bool(false)
	)

	return IgroupDeleteParams{
		AllowDeleteWhileMapped: &allowDeleteWhileMappedDefault,
	}
}

// IgroupDeleteParams contains all the bound params for the igroup delete operation
// typically these are obtained from a http.Request
//
// swagger:parameters igroup_delete
type IgroupDeleteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Allows the deletion of a mapped initiator group.<br/>
	Deleting a mapped initiator group means that the LUNs, to which the
	initiator group is mapped, are no longer available to the initiators.
	This might cause a disruption in the availability of data.<br/>
	<b>This parameter should be used with caution.</b>

	  In: query
	  Default: false
	*/
	AllowDeleteWhileMapped *bool
	/*The unique identifier of the initiator group.

	  Required: true
	  In: path
	*/
	UUID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewIgroupDeleteParams() beforehand.
func (o *IgroupDeleteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qAllowDeleteWhileMapped, qhkAllowDeleteWhileMapped, _ := qs.GetOK("allow_delete_while_mapped")
	if err := o.bindAllowDeleteWhileMapped(qAllowDeleteWhileMapped, qhkAllowDeleteWhileMapped, route.Formats); err != nil {
		res = append(res, err)
	}

	rUUID, rhkUUID, _ := route.Params.GetOK("uuid")
	if err := o.bindUUID(rUUID, rhkUUID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAllowDeleteWhileMapped binds and validates parameter AllowDeleteWhileMapped from query.
func (o *IgroupDeleteParams) bindAllowDeleteWhileMapped(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewIgroupDeleteParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("allow_delete_while_mapped", "query", "bool", raw)
	}
	o.AllowDeleteWhileMapped = &value

	return nil
}

// bindUUID binds and validates parameter UUID from path.
func (o *IgroupDeleteParams) bindUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.UUID = raw

	return nil
}
