// Code generated by go-swagger; DO NOT EDIT.

package s_a_n

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// IgroupNestedCollectionGetOKCode is the HTTP code returned for type IgroupNestedCollectionGetOK
const IgroupNestedCollectionGetOKCode int = 200

/*
IgroupNestedCollectionGetOK OK

swagger:response igroupNestedCollectionGetOK
*/
type IgroupNestedCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.IgroupNestedResponse `json:"body,omitempty"`
}

// NewIgroupNestedCollectionGetOK creates IgroupNestedCollectionGetOK with default headers values
func NewIgroupNestedCollectionGetOK() *IgroupNestedCollectionGetOK {

	return &IgroupNestedCollectionGetOK{}
}

// WithPayload adds the payload to the igroup nested collection get o k response
func (o *IgroupNestedCollectionGetOK) WithPayload(payload *models.IgroupNestedResponse) *IgroupNestedCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the igroup nested collection get o k response
func (o *IgroupNestedCollectionGetOK) SetPayload(payload *models.IgroupNestedResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IgroupNestedCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
IgroupNestedCollectionGetDefault ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 5374852 | The initiator group specified in the URI does not exist. |
Also see the table of common errors in the <a href="#Response_body">Response body</a> overview section of this documentation.

swagger:response igroupNestedCollectionGetDefault
*/
type IgroupNestedCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewIgroupNestedCollectionGetDefault creates IgroupNestedCollectionGetDefault with default headers values
func NewIgroupNestedCollectionGetDefault(code int) *IgroupNestedCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &IgroupNestedCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the igroup nested collection get default response
func (o *IgroupNestedCollectionGetDefault) WithStatusCode(code int) *IgroupNestedCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the igroup nested collection get default response
func (o *IgroupNestedCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the igroup nested collection get default response
func (o *IgroupNestedCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *IgroupNestedCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the igroup nested collection get default response
func (o *IgroupNestedCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IgroupNestedCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
