// Code generated by go-swagger; DO NOT EDIT.

package s_a_n

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// PerformanceFcpMetricCollectionGetOKCode is the HTTP code returned for type PerformanceFcpMetricCollectionGetOK
const PerformanceFcpMetricCollectionGetOKCode int = 200

/*
PerformanceFcpMetricCollectionGetOK OK

swagger:response performanceFcpMetricCollectionGetOK
*/
type PerformanceFcpMetricCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.PerformanceFcpMetricResponse `json:"body,omitempty"`
}

// NewPerformanceFcpMetricCollectionGetOK creates PerformanceFcpMetricCollectionGetOK with default headers values
func NewPerformanceFcpMetricCollectionGetOK() *PerformanceFcpMetricCollectionGetOK {

	return &PerformanceFcpMetricCollectionGetOK{}
}

// WithPayload adds the payload to the performance fcp metric collection get o k response
func (o *PerformanceFcpMetricCollectionGetOK) WithPayload(payload *models.PerformanceFcpMetricResponse) *PerformanceFcpMetricCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the performance fcp metric collection get o k response
func (o *PerformanceFcpMetricCollectionGetOK) SetPayload(payload *models.PerformanceFcpMetricResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PerformanceFcpMetricCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PerformanceFcpMetricCollectionGetDefault ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 8585947 | No metrics are available for the requested object. |
| 8586225 | An unexpected error occurred retrieving metrics for the requested object. |
Also see the table of common errors in the <a href="#Response_body">Response body</a> overview section of this documentation.

swagger:response performanceFcpMetricCollectionGetDefault
*/
type PerformanceFcpMetricCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPerformanceFcpMetricCollectionGetDefault creates PerformanceFcpMetricCollectionGetDefault with default headers values
func NewPerformanceFcpMetricCollectionGetDefault(code int) *PerformanceFcpMetricCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &PerformanceFcpMetricCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the performance fcp metric collection get default response
func (o *PerformanceFcpMetricCollectionGetDefault) WithStatusCode(code int) *PerformanceFcpMetricCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the performance fcp metric collection get default response
func (o *PerformanceFcpMetricCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the performance fcp metric collection get default response
func (o *PerformanceFcpMetricCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *PerformanceFcpMetricCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the performance fcp metric collection get default response
func (o *PerformanceFcpMetricCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PerformanceFcpMetricCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
