// Code generated by go-swagger; DO NOT EDIT.

package s_a_n

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// NewWwpnAliasCreateParams creates a new WwpnAliasCreateParams object
// with the default values initialized.
func NewWwpnAliasCreateParams() WwpnAliasCreateParams {

	var (
		// initialize parameters with default values

		returnRecordsDefault = bool(false)
	)

	return WwpnAliasCreateParams{
		ReturnRecords: &returnRecordsDefault,
	}
}

// WwpnAliasCreateParams contains all the bound params for the wwpn alias create operation
// typically these are obtained from a http.Request
//
// swagger:parameters wwpn_alias_create
type WwpnAliasCreateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The property values for the new WWPN alias.

	  Required: true
	  In: body
	*/
	Info *models.WwpnAlias
	/*The default is false.  If set to true, the records are returned.
	  In: query
	  Default: false
	*/
	ReturnRecords *bool
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewWwpnAliasCreateParams() beforehand.
func (o *WwpnAliasCreateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.WwpnAlias
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("info", "body", ""))
			} else {
				res = append(res, errors.NewParseError("info", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Info = &body
			}
		}
	} else {
		res = append(res, errors.Required("info", "body", ""))
	}

	qReturnRecords, qhkReturnRecords, _ := qs.GetOK("return_records")
	if err := o.bindReturnRecords(qReturnRecords, qhkReturnRecords, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindReturnRecords binds and validates parameter ReturnRecords from query.
func (o *WwpnAliasCreateParams) bindReturnRecords(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewWwpnAliasCreateParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("return_records", "query", "bool", raw)
	}
	o.ReturnRecords = &value

	return nil
}
