// Code generated by go-swagger; DO NOT EDIT.

package s_a_n

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewWwpnAliasGetParams creates a new WwpnAliasGetParams object
//
// There are no default values defined in the spec.
func NewWwpnAliasGetParams() WwpnAliasGetParams {

	return WwpnAliasGetParams{}
}

// WwpnAliasGetParams contains all the bound params for the wwpn alias get operation
// typically these are obtained from a http.Request
//
// swagger:parameters wwpn_alias_get
type WwpnAliasGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The name of FC WWPN alias.

	  Required: true
	  In: path
	*/
	Alias string
	/*Specify the fields to return.
	  In: query
	  Collection Format: csv
	*/
	Fields []string
	/*The unique identifier of the SVM in which the alias is found.

	  Required: true
	  In: path
	*/
	SvmUUID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewWwpnAliasGetParams() beforehand.
func (o *WwpnAliasGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rAlias, rhkAlias, _ := route.Params.GetOK("alias")
	if err := o.bindAlias(rAlias, rhkAlias, route.Formats); err != nil {
		res = append(res, err)
	}

	qFields, qhkFields, _ := qs.GetOK("fields")
	if err := o.bindFields(qFields, qhkFields, route.Formats); err != nil {
		res = append(res, err)
	}

	rSvmUUID, rhkSvmUUID, _ := route.Params.GetOK("svm.uuid")
	if err := o.bindSvmUUID(rSvmUUID, rhkSvmUUID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAlias binds and validates parameter Alias from path.
func (o *WwpnAliasGetParams) bindAlias(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Alias = raw

	return nil
}

// bindFields binds and validates array parameter Fields from query.
//
// Arrays are parsed according to CollectionFormat: "csv" (defaults to "csv" when empty).
func (o *WwpnAliasGetParams) bindFields(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var qvFields string
	if len(rawData) > 0 {
		qvFields = rawData[len(rawData)-1]
	}

	// CollectionFormat: csv
	fieldsIC := swag.SplitByFormat(qvFields, "csv")
	if len(fieldsIC) == 0 {
		return nil
	}

	var fieldsIR []string
	for _, fieldsIV := range fieldsIC {
		fieldsI := fieldsIV

		fieldsIR = append(fieldsIR, fieldsI)
	}

	o.Fields = fieldsIR

	return nil
}

// bindSvmUUID binds and validates parameter SvmUUID from path.
func (o *WwpnAliasGetParams) bindSvmUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SvmUUID = raw

	return nil
}
