// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ClusterModifyHandlerFunc turns a function with the right signature into a cluster modify handler
type ClusterModifyHandlerFunc func(ClusterModifyParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ClusterModifyHandlerFunc) Handle(params ClusterModifyParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ClusterModifyHandler interface for that can handle valid cluster modify params
type ClusterModifyHandler interface {
	Handle(ClusterModifyParams, interface{}) middleware.Responder
}

// NewClusterModify creates a new http.Handler for the cluster modify operation
func NewClusterModify(ctx *middleware.Context, handler ClusterModifyHandler) *ClusterModify {
	return &ClusterModify{Context: ctx, Handler: handler}
}

/*
	ClusterModify swagger:route PATCH /cluster Cluster clusterModify

Updates the cluster configuration after the cluster is created.
### Related ONTAP commands
* `cluster identity modify`
* `system node modify`
* `vserver services dns modify`
* `vserver services name-service dns modify`
* `timezone`
* `security ssl modify`
*/
type ClusterModify struct {
	Context *middleware.Context
	Handler ClusterModifyHandler
}

func (o *ClusterModify) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewClusterModifyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
