// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// CounterRowCollectionGetURL generates an URL for the counter row collection get operation
type CounterRowCollectionGetURL struct {
	CounterTableName string

	AggregationComplete    *bool
	AggregationCount       *int64
	CountersCountersLabel  *string
	CountersCountersValues *int64
	CountersLabels         *string
	CountersName           *string
	CountersValue          *int64
	CountersValues         *int64
	Fields                 []string
	ID                     *string
	MaxRecords             *int64
	OrderBy                []string
	PropertiesName         *string
	PropertiesValue        *string
	ReturnRecords          *bool
	ReturnTimeout          *int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *CounterRowCollectionGetURL) WithBasePath(bp string) *CounterRowCollectionGetURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *CounterRowCollectionGetURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *CounterRowCollectionGetURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/cluster/counter/tables/{counter_table.name}/rows"

	counterTableName := o.CounterTableName
	if counterTableName != "" {
		_path = strings.Replace(_path, "{counter_table.name}", counterTableName, -1)
	} else {
		return nil, errors.New("counterTableName is required on CounterRowCollectionGetURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var aggregationCompleteQ string
	if o.AggregationComplete != nil {
		aggregationCompleteQ = swag.FormatBool(*o.AggregationComplete)
	}
	if aggregationCompleteQ != "" {
		qs.Set("aggregation.complete", aggregationCompleteQ)
	}

	var aggregationCountQ string
	if o.AggregationCount != nil {
		aggregationCountQ = swag.FormatInt64(*o.AggregationCount)
	}
	if aggregationCountQ != "" {
		qs.Set("aggregation.count", aggregationCountQ)
	}

	var countersCountersLabelQ string
	if o.CountersCountersLabel != nil {
		countersCountersLabelQ = *o.CountersCountersLabel
	}
	if countersCountersLabelQ != "" {
		qs.Set("counters.counters.label", countersCountersLabelQ)
	}

	var countersCountersValuesQ string
	if o.CountersCountersValues != nil {
		countersCountersValuesQ = swag.FormatInt64(*o.CountersCountersValues)
	}
	if countersCountersValuesQ != "" {
		qs.Set("counters.counters.values", countersCountersValuesQ)
	}

	var countersLabelsQ string
	if o.CountersLabels != nil {
		countersLabelsQ = *o.CountersLabels
	}
	if countersLabelsQ != "" {
		qs.Set("counters.labels", countersLabelsQ)
	}

	var countersNameQ string
	if o.CountersName != nil {
		countersNameQ = *o.CountersName
	}
	if countersNameQ != "" {
		qs.Set("counters.name", countersNameQ)
	}

	var countersValueQ string
	if o.CountersValue != nil {
		countersValueQ = swag.FormatInt64(*o.CountersValue)
	}
	if countersValueQ != "" {
		qs.Set("counters.value", countersValueQ)
	}

	var countersValuesQ string
	if o.CountersValues != nil {
		countersValuesQ = swag.FormatInt64(*o.CountersValues)
	}
	if countersValuesQ != "" {
		qs.Set("counters.values", countersValuesQ)
	}

	var fieldsIR []string
	for _, fieldsI := range o.Fields {
		fieldsIS := fieldsI
		if fieldsIS != "" {
			fieldsIR = append(fieldsIR, fieldsIS)
		}
	}

	fields := swag.JoinByFormat(fieldsIR, "csv")

	if len(fields) > 0 {
		qsv := fields[0]
		if qsv != "" {
			qs.Set("fields", qsv)
		}
	}

	var idQ string
	if o.ID != nil {
		idQ = *o.ID
	}
	if idQ != "" {
		qs.Set("id", idQ)
	}

	var maxRecordsQ string
	if o.MaxRecords != nil {
		maxRecordsQ = swag.FormatInt64(*o.MaxRecords)
	}
	if maxRecordsQ != "" {
		qs.Set("max_records", maxRecordsQ)
	}

	var orderByIR []string
	for _, orderByI := range o.OrderBy {
		orderByIS := orderByI
		if orderByIS != "" {
			orderByIR = append(orderByIR, orderByIS)
		}
	}

	orderBy := swag.JoinByFormat(orderByIR, "csv")

	if len(orderBy) > 0 {
		qsv := orderBy[0]
		if qsv != "" {
			qs.Set("order_by", qsv)
		}
	}

	var propertiesNameQ string
	if o.PropertiesName != nil {
		propertiesNameQ = *o.PropertiesName
	}
	if propertiesNameQ != "" {
		qs.Set("properties.name", propertiesNameQ)
	}

	var propertiesValueQ string
	if o.PropertiesValue != nil {
		propertiesValueQ = *o.PropertiesValue
	}
	if propertiesValueQ != "" {
		qs.Set("properties.value", propertiesValueQ)
	}

	var returnRecordsQ string
	if o.ReturnRecords != nil {
		returnRecordsQ = swag.FormatBool(*o.ReturnRecords)
	}
	if returnRecordsQ != "" {
		qs.Set("return_records", returnRecordsQ)
	}

	var returnTimeoutQ string
	if o.ReturnTimeout != nil {
		returnTimeoutQ = swag.FormatInt64(*o.ReturnTimeout)
	}
	if returnTimeoutQ != "" {
		qs.Set("return_timeout", returnTimeoutQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *CounterRowCollectionGetURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *CounterRowCollectionGetURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *CounterRowCollectionGetURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on CounterRowCollectionGetURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on CounterRowCollectionGetURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *CounterRowCollectionGetURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
