// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CounterTableCollectionGetHandlerFunc turns a function with the right signature into a counter table collection get handler
type CounterTableCollectionGetHandlerFunc func(CounterTableCollectionGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CounterTableCollectionGetHandlerFunc) Handle(params CounterTableCollectionGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CounterTableCollectionGetHandler interface for that can handle valid counter table collection get params
type CounterTableCollectionGetHandler interface {
	Handle(CounterTableCollectionGetParams, interface{}) middleware.Responder
}

// NewCounterTableCollectionGet creates a new http.Handler for the counter table collection get operation
func NewCounterTableCollectionGet(ctx *middleware.Context, handler CounterTableCollectionGetHandler) *CounterTableCollectionGet {
	return &CounterTableCollectionGet{Context: ctx, Handler: handler}
}

/*
	CounterTableCollectionGet swagger:route GET /cluster/counter/tables Cluster counterTableCollectionGet

Returns a collection of counter tables and their schema definitions.
*/
type CounterTableCollectionGet struct {
	Context *middleware.Context
	Handler CounterTableCollectionGetHandler
}

func (o *CounterTableCollectionGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCounterTableCollectionGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
