// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// LicenseDeleteHandlerFunc turns a function with the right signature into a license delete handler
type LicenseDeleteHandlerFunc func(LicenseDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn LicenseDeleteHandlerFunc) Handle(params LicenseDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// LicenseDeleteHandler interface for that can handle valid license delete params
type LicenseDeleteHandler interface {
	Handle(LicenseDeleteParams, interface{}) middleware.Responder
}

// NewLicenseDelete creates a new http.Handler for the license delete operation
func NewLicenseDelete(ctx *middleware.Context, handler LicenseDeleteHandler) *LicenseDelete {
	return &LicenseDelete{Context: ctx, Handler: handler}
}

/*
	LicenseDelete swagger:route DELETE /cluster/licensing/licenses/{name} Cluster licenseDelete

Deletes a license.
### Related ONTAP commands
* `system license delete`
*/
type LicenseDelete struct {
	Context *middleware.Context
	Handler LicenseDeleteHandler
}

func (o *LicenseDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewLicenseDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
