// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// MediatorCollectionGetOKCode is the HTTP code returned for type MediatorCollectionGetOK
const MediatorCollectionGetOKCode int = 200

/*
MediatorCollectionGetOK OK

swagger:response mediatorCollectionGetOK
*/
type MediatorCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.MediatorResponse `json:"body,omitempty"`
}

// NewMediatorCollectionGetOK creates MediatorCollectionGetOK with default headers values
func NewMediatorCollectionGetOK() *MediatorCollectionGetOK {

	return &MediatorCollectionGetOK{}
}

// WithPayload adds the payload to the mediator collection get o k response
func (o *MediatorCollectionGetOK) WithPayload(payload *models.MediatorResponse) *MediatorCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the mediator collection get o k response
func (o *MediatorCollectionGetOK) SetPayload(payload *models.MediatorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MediatorCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
MediatorCollectionGetDefault ONTAP Error Response codes
| Error code  |  Description |
|-------------|--------------|
| 2430739     | Unable to access Mediator. Reason: Invalid Mediator IP or Mediator does not exist.|

swagger:response mediatorCollectionGetDefault
*/
type MediatorCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewMediatorCollectionGetDefault creates MediatorCollectionGetDefault with default headers values
func NewMediatorCollectionGetDefault(code int) *MediatorCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &MediatorCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the mediator collection get default response
func (o *MediatorCollectionGetDefault) WithStatusCode(code int) *MediatorCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the mediator collection get default response
func (o *MediatorCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the mediator collection get default response
func (o *MediatorCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *MediatorCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the mediator collection get default response
func (o *MediatorCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MediatorCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
