// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/metal-stack/ontap-go/api/models"
)

// NewMetroclusterInterconnectModifyParams creates a new MetroclusterInterconnectModifyParams object
// with the default values initialized.
func NewMetroclusterInterconnectModifyParams() MetroclusterInterconnectModifyParams {

	var (
		// initialize parameters with default values

		returnTimeoutDefault = int64(0)
	)

	return MetroclusterInterconnectModifyParams{
		ReturnTimeout: &returnTimeoutDefault,
	}
}

// MetroclusterInterconnectModifyParams contains all the bound params for the metrocluster interconnect modify operation
// typically these are obtained from a http.Request
//
// swagger:parameters metrocluster_interconnect_modify
type MetroclusterInterconnectModifyParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Interconnect adapter
	  Required: true
	  In: path
	*/
	Adapter string
	/*MetroCluster interconnect interface information
	  Required: true
	  In: body
	*/
	Info *models.MetroclusterInterconnect
	/*Node UUID
	  Required: true
	  In: path
	*/
	NodeUUID string
	/*DR Partner type
	  Required: true
	  In: path
	*/
	PartnerType string
	/*The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.
	  Maximum: 120
	  Minimum: 0
	  In: query
	  Default: 0
	*/
	ReturnTimeout *int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewMetroclusterInterconnectModifyParams() beforehand.
func (o *MetroclusterInterconnectModifyParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rAdapter, rhkAdapter, _ := route.Params.GetOK("adapter")
	if err := o.bindAdapter(rAdapter, rhkAdapter, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.MetroclusterInterconnect
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("info", "body", ""))
			} else {
				res = append(res, errors.NewParseError("info", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Info = &body
			}
		}
	} else {
		res = append(res, errors.Required("info", "body", ""))
	}

	rNodeUUID, rhkNodeUUID, _ := route.Params.GetOK("node.uuid")
	if err := o.bindNodeUUID(rNodeUUID, rhkNodeUUID, route.Formats); err != nil {
		res = append(res, err)
	}

	rPartnerType, rhkPartnerType, _ := route.Params.GetOK("partner_type")
	if err := o.bindPartnerType(rPartnerType, rhkPartnerType, route.Formats); err != nil {
		res = append(res, err)
	}

	qReturnTimeout, qhkReturnTimeout, _ := qs.GetOK("return_timeout")
	if err := o.bindReturnTimeout(qReturnTimeout, qhkReturnTimeout, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAdapter binds and validates parameter Adapter from path.
func (o *MetroclusterInterconnectModifyParams) bindAdapter(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Adapter = raw

	return nil
}

// bindNodeUUID binds and validates parameter NodeUUID from path.
func (o *MetroclusterInterconnectModifyParams) bindNodeUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.NodeUUID = raw

	return nil
}

// bindPartnerType binds and validates parameter PartnerType from path.
func (o *MetroclusterInterconnectModifyParams) bindPartnerType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.PartnerType = raw

	return nil
}

// bindReturnTimeout binds and validates parameter ReturnTimeout from query.
func (o *MetroclusterInterconnectModifyParams) bindReturnTimeout(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewMetroclusterInterconnectModifyParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("return_timeout", "query", "int64", raw)
	}
	o.ReturnTimeout = &value

	if err := o.validateReturnTimeout(formats); err != nil {
		return err
	}

	return nil
}

// validateReturnTimeout carries on validations for parameter ReturnTimeout
func (o *MetroclusterInterconnectModifyParams) validateReturnTimeout(formats strfmt.Registry) error {

	if err := validate.MinimumInt("return_timeout", "query", *o.ReturnTimeout, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("return_timeout", "query", *o.ReturnTimeout, 120, false); err != nil {
		return err
	}

	return nil
}
