// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewSensorsCollectionGetParams creates a new SensorsCollectionGetParams object
// with the default values initialized.
func NewSensorsCollectionGetParams() SensorsCollectionGetParams {

	var (
		// initialize parameters with default values

		returnRecordsDefault = bool(true)
		returnTimeoutDefault = int64(15)
	)

	return SensorsCollectionGetParams{
		ReturnRecords: &returnRecordsDefault,

		ReturnTimeout: &returnTimeoutDefault,
	}
}

// SensorsCollectionGetParams contains all the bound params for the sensors collection get operation
// typically these are obtained from a http.Request
//
// swagger:parameters sensors_collection_get
type SensorsCollectionGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Filter by critical_high_threshold
	  In: query
	*/
	CriticalHighThreshold *int64
	/*Filter by critical_low_threshold
	  In: query
	*/
	CriticalLowThreshold *int64
	/*Filter by discrete_state
	  In: query
	*/
	DiscreteState *string
	/*Filter by discrete_value
	  In: query
	*/
	DiscreteValue *string
	/*Specify the fields to return.
	  In: query
	  Collection Format: csv
	*/
	Fields []string
	/*Filter by index
	  In: query
	*/
	Index *int64
	/*Limit the number of records returned.
	  In: query
	*/
	MaxRecords *int64
	/*Filter by name
	  In: query
	*/
	Name *string
	/*Filter by node.name
	  In: query
	*/
	NodeName *string
	/*Filter by node.uuid
	  In: query
	*/
	NodeUUID *string
	/*Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.
	  In: query
	  Collection Format: csv
	*/
	OrderBy []string
	/*The default is true for GET calls.  When set to false, only the number of records is returned.
	  In: query
	  Default: true
	*/
	ReturnRecords *bool
	/*The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.
	  Maximum: 120
	  Minimum: 0
	  In: query
	  Default: 15
	*/
	ReturnTimeout *int64
	/*Filter by threshold_state
	  In: query
	*/
	ThresholdState *string
	/*Filter by type
	  In: query
	*/
	Type *string
	/*Filter by value
	  In: query
	*/
	Value *int64
	/*Filter by value_units
	  In: query
	*/
	ValueUnits *string
	/*Filter by warning_high_threshold
	  In: query
	*/
	WarningHighThreshold *int64
	/*Filter by warning_low_threshold
	  In: query
	*/
	WarningLowThreshold *int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSensorsCollectionGetParams() beforehand.
func (o *SensorsCollectionGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qCriticalHighThreshold, qhkCriticalHighThreshold, _ := qs.GetOK("critical_high_threshold")
	if err := o.bindCriticalHighThreshold(qCriticalHighThreshold, qhkCriticalHighThreshold, route.Formats); err != nil {
		res = append(res, err)
	}

	qCriticalLowThreshold, qhkCriticalLowThreshold, _ := qs.GetOK("critical_low_threshold")
	if err := o.bindCriticalLowThreshold(qCriticalLowThreshold, qhkCriticalLowThreshold, route.Formats); err != nil {
		res = append(res, err)
	}

	qDiscreteState, qhkDiscreteState, _ := qs.GetOK("discrete_state")
	if err := o.bindDiscreteState(qDiscreteState, qhkDiscreteState, route.Formats); err != nil {
		res = append(res, err)
	}

	qDiscreteValue, qhkDiscreteValue, _ := qs.GetOK("discrete_value")
	if err := o.bindDiscreteValue(qDiscreteValue, qhkDiscreteValue, route.Formats); err != nil {
		res = append(res, err)
	}

	qFields, qhkFields, _ := qs.GetOK("fields")
	if err := o.bindFields(qFields, qhkFields, route.Formats); err != nil {
		res = append(res, err)
	}

	qIndex, qhkIndex, _ := qs.GetOK("index")
	if err := o.bindIndex(qIndex, qhkIndex, route.Formats); err != nil {
		res = append(res, err)
	}

	qMaxRecords, qhkMaxRecords, _ := qs.GetOK("max_records")
	if err := o.bindMaxRecords(qMaxRecords, qhkMaxRecords, route.Formats); err != nil {
		res = append(res, err)
	}

	qName, qhkName, _ := qs.GetOK("name")
	if err := o.bindName(qName, qhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	qNodeName, qhkNodeName, _ := qs.GetOK("node.name")
	if err := o.bindNodeName(qNodeName, qhkNodeName, route.Formats); err != nil {
		res = append(res, err)
	}

	qNodeUUID, qhkNodeUUID, _ := qs.GetOK("node.uuid")
	if err := o.bindNodeUUID(qNodeUUID, qhkNodeUUID, route.Formats); err != nil {
		res = append(res, err)
	}

	qOrderBy, qhkOrderBy, _ := qs.GetOK("order_by")
	if err := o.bindOrderBy(qOrderBy, qhkOrderBy, route.Formats); err != nil {
		res = append(res, err)
	}

	qReturnRecords, qhkReturnRecords, _ := qs.GetOK("return_records")
	if err := o.bindReturnRecords(qReturnRecords, qhkReturnRecords, route.Formats); err != nil {
		res = append(res, err)
	}

	qReturnTimeout, qhkReturnTimeout, _ := qs.GetOK("return_timeout")
	if err := o.bindReturnTimeout(qReturnTimeout, qhkReturnTimeout, route.Formats); err != nil {
		res = append(res, err)
	}

	qThresholdState, qhkThresholdState, _ := qs.GetOK("threshold_state")
	if err := o.bindThresholdState(qThresholdState, qhkThresholdState, route.Formats); err != nil {
		res = append(res, err)
	}

	qType, qhkType, _ := qs.GetOK("type")
	if err := o.bindType(qType, qhkType, route.Formats); err != nil {
		res = append(res, err)
	}

	qValue, qhkValue, _ := qs.GetOK("value")
	if err := o.bindValue(qValue, qhkValue, route.Formats); err != nil {
		res = append(res, err)
	}

	qValueUnits, qhkValueUnits, _ := qs.GetOK("value_units")
	if err := o.bindValueUnits(qValueUnits, qhkValueUnits, route.Formats); err != nil {
		res = append(res, err)
	}

	qWarningHighThreshold, qhkWarningHighThreshold, _ := qs.GetOK("warning_high_threshold")
	if err := o.bindWarningHighThreshold(qWarningHighThreshold, qhkWarningHighThreshold, route.Formats); err != nil {
		res = append(res, err)
	}

	qWarningLowThreshold, qhkWarningLowThreshold, _ := qs.GetOK("warning_low_threshold")
	if err := o.bindWarningLowThreshold(qWarningLowThreshold, qhkWarningLowThreshold, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCriticalHighThreshold binds and validates parameter CriticalHighThreshold from query.
func (o *SensorsCollectionGetParams) bindCriticalHighThreshold(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("critical_high_threshold", "query", "int64", raw)
	}
	o.CriticalHighThreshold = &value

	return nil
}

// bindCriticalLowThreshold binds and validates parameter CriticalLowThreshold from query.
func (o *SensorsCollectionGetParams) bindCriticalLowThreshold(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("critical_low_threshold", "query", "int64", raw)
	}
	o.CriticalLowThreshold = &value

	return nil
}

// bindDiscreteState binds and validates parameter DiscreteState from query.
func (o *SensorsCollectionGetParams) bindDiscreteState(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.DiscreteState = &raw

	return nil
}

// bindDiscreteValue binds and validates parameter DiscreteValue from query.
func (o *SensorsCollectionGetParams) bindDiscreteValue(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.DiscreteValue = &raw

	return nil
}

// bindFields binds and validates array parameter Fields from query.
//
// Arrays are parsed according to CollectionFormat: "csv" (defaults to "csv" when empty).
func (o *SensorsCollectionGetParams) bindFields(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var qvFields string
	if len(rawData) > 0 {
		qvFields = rawData[len(rawData)-1]
	}

	// CollectionFormat: csv
	fieldsIC := swag.SplitByFormat(qvFields, "csv")
	if len(fieldsIC) == 0 {
		return nil
	}

	var fieldsIR []string
	for _, fieldsIV := range fieldsIC {
		fieldsI := fieldsIV

		fieldsIR = append(fieldsIR, fieldsI)
	}

	o.Fields = fieldsIR

	return nil
}

// bindIndex binds and validates parameter Index from query.
func (o *SensorsCollectionGetParams) bindIndex(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("index", "query", "int64", raw)
	}
	o.Index = &value

	return nil
}

// bindMaxRecords binds and validates parameter MaxRecords from query.
func (o *SensorsCollectionGetParams) bindMaxRecords(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("max_records", "query", "int64", raw)
	}
	o.MaxRecords = &value

	return nil
}

// bindName binds and validates parameter Name from query.
func (o *SensorsCollectionGetParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Name = &raw

	return nil
}

// bindNodeName binds and validates parameter NodeName from query.
func (o *SensorsCollectionGetParams) bindNodeName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.NodeName = &raw

	return nil
}

// bindNodeUUID binds and validates parameter NodeUUID from query.
func (o *SensorsCollectionGetParams) bindNodeUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.NodeUUID = &raw

	return nil
}

// bindOrderBy binds and validates array parameter OrderBy from query.
//
// Arrays are parsed according to CollectionFormat: "csv" (defaults to "csv" when empty).
func (o *SensorsCollectionGetParams) bindOrderBy(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var qvOrderBy string
	if len(rawData) > 0 {
		qvOrderBy = rawData[len(rawData)-1]
	}

	// CollectionFormat: csv
	orderByIC := swag.SplitByFormat(qvOrderBy, "csv")
	if len(orderByIC) == 0 {
		return nil
	}

	var orderByIR []string
	for _, orderByIV := range orderByIC {
		orderByI := orderByIV

		orderByIR = append(orderByIR, orderByI)
	}

	o.OrderBy = orderByIR

	return nil
}

// bindReturnRecords binds and validates parameter ReturnRecords from query.
func (o *SensorsCollectionGetParams) bindReturnRecords(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewSensorsCollectionGetParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("return_records", "query", "bool", raw)
	}
	o.ReturnRecords = &value

	return nil
}

// bindReturnTimeout binds and validates parameter ReturnTimeout from query.
func (o *SensorsCollectionGetParams) bindReturnTimeout(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewSensorsCollectionGetParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("return_timeout", "query", "int64", raw)
	}
	o.ReturnTimeout = &value

	if err := o.validateReturnTimeout(formats); err != nil {
		return err
	}

	return nil
}

// validateReturnTimeout carries on validations for parameter ReturnTimeout
func (o *SensorsCollectionGetParams) validateReturnTimeout(formats strfmt.Registry) error {

	if err := validate.MinimumInt("return_timeout", "query", *o.ReturnTimeout, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("return_timeout", "query", *o.ReturnTimeout, 120, false); err != nil {
		return err
	}

	return nil
}

// bindThresholdState binds and validates parameter ThresholdState from query.
func (o *SensorsCollectionGetParams) bindThresholdState(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ThresholdState = &raw

	return nil
}

// bindType binds and validates parameter Type from query.
func (o *SensorsCollectionGetParams) bindType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Type = &raw

	return nil
}

// bindValue binds and validates parameter Value from query.
func (o *SensorsCollectionGetParams) bindValue(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("value", "query", "int64", raw)
	}
	o.Value = &value

	return nil
}

// bindValueUnits binds and validates parameter ValueUnits from query.
func (o *SensorsCollectionGetParams) bindValueUnits(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ValueUnits = &raw

	return nil
}

// bindWarningHighThreshold binds and validates parameter WarningHighThreshold from query.
func (o *SensorsCollectionGetParams) bindWarningHighThreshold(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("warning_high_threshold", "query", "int64", raw)
	}
	o.WarningHighThreshold = &value

	return nil
}

// bindWarningLowThreshold binds and validates parameter WarningLowThreshold from query.
func (o *SensorsCollectionGetParams) bindWarningLowThreshold(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("warning_low_threshold", "query", "int64", raw)
	}
	o.WarningLowThreshold = &value

	return nil
}
