// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SoftwarePackageGetHandlerFunc turns a function with the right signature into a software package get handler
type SoftwarePackageGetHandlerFunc func(SoftwarePackageGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SoftwarePackageGetHandlerFunc) Handle(params SoftwarePackageGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SoftwarePackageGetHandler interface for that can handle valid software package get params
type SoftwarePackageGetHandler interface {
	Handle(SoftwarePackageGetParams, interface{}) middleware.Responder
}

// NewSoftwarePackageGet creates a new http.Handler for the software package get operation
func NewSoftwarePackageGet(ctx *middleware.Context, handler SoftwarePackageGetHandler) *SoftwarePackageGet {
	return &SoftwarePackageGet{Context: ctx, Handler: handler}
}

/*
	SoftwarePackageGet swagger:route GET /cluster/software/packages/{version} Cluster softwarePackageGet

Retrieves the software package information.
### Related ONTAP commands
* `cluster image package show-repository`
### Learn more
* [`DOC /cluster/software`](#docs-cluster-cluster_software)
*/
type SoftwarePackageGet struct {
	Context *middleware.Context
	Handler SoftwarePackageGetHandler
}

func (o *SoftwarePackageGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSoftwarePackageGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
