// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// ActiveDirectoryPreferredDcCollectionGetOKCode is the HTTP code returned for type ActiveDirectoryPreferredDcCollectionGetOK
const ActiveDirectoryPreferredDcCollectionGetOKCode int = 200

/*
ActiveDirectoryPreferredDcCollectionGetOK OK

swagger:response activeDirectoryPreferredDcCollectionGetOK
*/
type ActiveDirectoryPreferredDcCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.ActiveDirectoryPreferredDcResponse `json:"body,omitempty"`
}

// NewActiveDirectoryPreferredDcCollectionGetOK creates ActiveDirectoryPreferredDcCollectionGetOK with default headers values
func NewActiveDirectoryPreferredDcCollectionGetOK() *ActiveDirectoryPreferredDcCollectionGetOK {

	return &ActiveDirectoryPreferredDcCollectionGetOK{}
}

// WithPayload adds the payload to the active directory preferred dc collection get o k response
func (o *ActiveDirectoryPreferredDcCollectionGetOK) WithPayload(payload *models.ActiveDirectoryPreferredDcResponse) *ActiveDirectoryPreferredDcCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the active directory preferred dc collection get o k response
func (o *ActiveDirectoryPreferredDcCollectionGetOK) SetPayload(payload *models.ActiveDirectoryPreferredDcResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActiveDirectoryPreferredDcCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
ActiveDirectoryPreferredDcCollectionGetDefault Error

swagger:response activeDirectoryPreferredDcCollectionGetDefault
*/
type ActiveDirectoryPreferredDcCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewActiveDirectoryPreferredDcCollectionGetDefault creates ActiveDirectoryPreferredDcCollectionGetDefault with default headers values
func NewActiveDirectoryPreferredDcCollectionGetDefault(code int) *ActiveDirectoryPreferredDcCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &ActiveDirectoryPreferredDcCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the active directory preferred dc collection get default response
func (o *ActiveDirectoryPreferredDcCollectionGetDefault) WithStatusCode(code int) *ActiveDirectoryPreferredDcCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the active directory preferred dc collection get default response
func (o *ActiveDirectoryPreferredDcCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the active directory preferred dc collection get default response
func (o *ActiveDirectoryPreferredDcCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *ActiveDirectoryPreferredDcCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the active directory preferred dc collection get default response
func (o *ActiveDirectoryPreferredDcCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActiveDirectoryPreferredDcCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
