// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// ActiveDirectoryPreferredDcCreateURL generates an URL for the active directory preferred dc create operation
type ActiveDirectoryPreferredDcCreateURL struct {
	SvmUUID string

	ReturnRecords        *bool
	SkipConfigValidation *bool

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ActiveDirectoryPreferredDcCreateURL) WithBasePath(bp string) *ActiveDirectoryPreferredDcCreateURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ActiveDirectoryPreferredDcCreateURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *ActiveDirectoryPreferredDcCreateURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/protocols/active-directory/{svm.uuid}/preferred-domain-controllers"

	svmUUID := o.SvmUUID
	if svmUUID != "" {
		_path = strings.Replace(_path, "{svm.uuid}", svmUUID, -1)
	} else {
		return nil, errors.New("svmUuid is required on ActiveDirectoryPreferredDcCreateURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var returnRecordsQ string
	if o.ReturnRecords != nil {
		returnRecordsQ = swag.FormatBool(*o.ReturnRecords)
	}
	if returnRecordsQ != "" {
		qs.Set("return_records", returnRecordsQ)
	}

	var skipConfigValidationQ string
	if o.SkipConfigValidation != nil {
		skipConfigValidationQ = swag.FormatBool(*o.SkipConfigValidation)
	}
	if skipConfigValidationQ != "" {
		qs.Set("skip_config_validation", skipConfigValidationQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *ActiveDirectoryPreferredDcCreateURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *ActiveDirectoryPreferredDcCreateURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *ActiveDirectoryPreferredDcCreateURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on ActiveDirectoryPreferredDcCreateURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on ActiveDirectoryPreferredDcCreateURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *ActiveDirectoryPreferredDcCreateURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
