// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCifsShareACLGetParams creates a new CifsShareACLGetParams object
//
// There are no default values defined in the spec.
func NewCifsShareACLGetParams() CifsShareACLGetParams {

	return CifsShareACLGetParams{}
}

// CifsShareACLGetParams contains all the bound params for the cifs share acl get operation
// typically these are obtained from a http.Request
//
// swagger:parameters cifs_share_acl_get
type CifsShareACLGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Specify the fields to return.
	  In: query
	  Collection Format: csv
	*/
	Fields []string
	/*Share name
	  Required: true
	  In: path
	*/
	Share string
	/*UUID of the SVM to which this object belongs.
	  Required: true
	  In: path
	*/
	SvmUUID string
	/*User or group type
	  Required: true
	  In: path
	*/
	Type string
	/*User or group name
	  Required: true
	  In: path
	*/
	UserOrGroup string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCifsShareACLGetParams() beforehand.
func (o *CifsShareACLGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qFields, qhkFields, _ := qs.GetOK("fields")
	if err := o.bindFields(qFields, qhkFields, route.Formats); err != nil {
		res = append(res, err)
	}

	rShare, rhkShare, _ := route.Params.GetOK("share")
	if err := o.bindShare(rShare, rhkShare, route.Formats); err != nil {
		res = append(res, err)
	}

	rSvmUUID, rhkSvmUUID, _ := route.Params.GetOK("svm.uuid")
	if err := o.bindSvmUUID(rSvmUUID, rhkSvmUUID, route.Formats); err != nil {
		res = append(res, err)
	}

	rType, rhkType, _ := route.Params.GetOK("type")
	if err := o.bindType(rType, rhkType, route.Formats); err != nil {
		res = append(res, err)
	}

	rUserOrGroup, rhkUserOrGroup, _ := route.Params.GetOK("user_or_group")
	if err := o.bindUserOrGroup(rUserOrGroup, rhkUserOrGroup, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFields binds and validates array parameter Fields from query.
//
// Arrays are parsed according to CollectionFormat: "csv" (defaults to "csv" when empty).
func (o *CifsShareACLGetParams) bindFields(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var qvFields string
	if len(rawData) > 0 {
		qvFields = rawData[len(rawData)-1]
	}

	// CollectionFormat: csv
	fieldsIC := swag.SplitByFormat(qvFields, "csv")
	if len(fieldsIC) == 0 {
		return nil
	}

	var fieldsIR []string
	for _, fieldsIV := range fieldsIC {
		fieldsI := fieldsIV

		fieldsIR = append(fieldsIR, fieldsI)
	}

	o.Fields = fieldsIR

	return nil
}

// bindShare binds and validates parameter Share from path.
func (o *CifsShareACLGetParams) bindShare(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Share = raw

	return nil
}

// bindSvmUUID binds and validates parameter SvmUUID from path.
func (o *CifsShareACLGetParams) bindSvmUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SvmUUID = raw

	return nil
}

// bindType binds and validates parameter Type from path.
func (o *CifsShareACLGetParams) bindType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Type = raw

	return nil
}

// bindUserOrGroup binds and validates parameter UserOrGroup from path.
func (o *CifsShareACLGetParams) bindUserOrGroup(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.UserOrGroup = raw

	return nil
}
