// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CifsShareACLCreateHandlerFunc turns a function with the right signature into a cifs share acl create handler
type CifsShareACLCreateHandlerFunc func(CifsShareACLCreateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CifsShareACLCreateHandlerFunc) Handle(params CifsShareACLCreateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CifsShareACLCreateHandler interface for that can handle valid cifs share acl create params
type CifsShareACLCreateHandler interface {
	Handle(CifsShareACLCreateParams, interface{}) middleware.Responder
}

// NewCifsShareACLCreate creates a new http.Handler for the cifs share acl create operation
func NewCifsShareACLCreate(ctx *middleware.Context, handler CifsShareACLCreateHandler) *CifsShareACLCreate {
	return &CifsShareACLCreate{Context: ctx, Handler: handler}
}

/*
	CifsShareACLCreate swagger:route POST /protocols/cifs/shares/{svm.uuid}/{share}/acls NAS cifsShareAclCreate

Creates a share-level ACL on a CIFS share.
### Required properties
* `svm.uuid` or `svm.name` - Existing SVM in which to create the share acl.
* `share` - Existing CIFS share in which to create the share acl.
* `user_or_group` - Existing user or group name for which the acl is added on the CIFS share.
* `permission` - Access rights that a user or group has on the defined CIFS share.
### Default property values
* `type` - _windows_
### Related ONTAP commands
* `vserver cifs share access-control create`
### Learn more
* [`DOC /protocols/cifs/shares/{svm.uuid}/{share}/acls`](#docs-NAS-protocols_cifs_shares_{svm.uuid}_{share}_acls)
*/
type CifsShareACLCreate struct {
	Context *middleware.Context
	Handler CifsShareACLCreateHandler
}

func (o *CifsShareACLCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCifsShareACLCreateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
