// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// CifsServiceCollectionGetOKCode is the HTTP code returned for type CifsServiceCollectionGetOK
const CifsServiceCollectionGetOKCode int = 200

/*
CifsServiceCollectionGetOK OK

swagger:response cifsServiceCollectionGetOK
*/
type CifsServiceCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.CifsServiceResponse `json:"body,omitempty"`
}

// NewCifsServiceCollectionGetOK creates CifsServiceCollectionGetOK with default headers values
func NewCifsServiceCollectionGetOK() *CifsServiceCollectionGetOK {

	return &CifsServiceCollectionGetOK{}
}

// WithPayload adds the payload to the cifs service collection get o k response
func (o *CifsServiceCollectionGetOK) WithPayload(payload *models.CifsServiceResponse) *CifsServiceCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cifs service collection get o k response
func (o *CifsServiceCollectionGetOK) SetPayload(payload *models.CifsServiceResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CifsServiceCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
CifsServiceCollectionGetDefault Error

swagger:response cifsServiceCollectionGetDefault
*/
type CifsServiceCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewCifsServiceCollectionGetDefault creates CifsServiceCollectionGetDefault with default headers values
func NewCifsServiceCollectionGetDefault(code int) *CifsServiceCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &CifsServiceCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the cifs service collection get default response
func (o *CifsServiceCollectionGetDefault) WithStatusCode(code int) *CifsServiceCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the cifs service collection get default response
func (o *CifsServiceCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the cifs service collection get default response
func (o *CifsServiceCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *CifsServiceCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cifs service collection get default response
func (o *CifsServiceCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CifsServiceCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
