// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// CifsSessionDeleteURL generates an URL for the cifs session delete operation
type CifsSessionDeleteURL struct {
	ConnectionID int64
	Identifier   int64
	NodeUUID     string
	SvmUUID      string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *CifsSessionDeleteURL) WithBasePath(bp string) *CifsSessionDeleteURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *CifsSessionDeleteURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *CifsSessionDeleteURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/protocols/cifs/sessions/{node.uuid}/{svm.uuid}/{identifier}/{connection_id}"

	connectionID := swag.FormatInt64(o.ConnectionID)
	if connectionID != "" {
		_path = strings.Replace(_path, "{connection_id}", connectionID, -1)
	} else {
		return nil, errors.New("connectionId is required on CifsSessionDeleteURL")
	}

	identifier := swag.FormatInt64(o.Identifier)
	if identifier != "" {
		_path = strings.Replace(_path, "{identifier}", identifier, -1)
	} else {
		return nil, errors.New("identifier is required on CifsSessionDeleteURL")
	}

	nodeUUID := o.NodeUUID
	if nodeUUID != "" {
		_path = strings.Replace(_path, "{node.uuid}", nodeUUID, -1)
	} else {
		return nil, errors.New("nodeUuid is required on CifsSessionDeleteURL")
	}

	svmUUID := o.SvmUUID
	if svmUUID != "" {
		_path = strings.Replace(_path, "{svm.uuid}", svmUUID, -1)
	} else {
		return nil, errors.New("svmUuid is required on CifsSessionDeleteURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *CifsSessionDeleteURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *CifsSessionDeleteURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *CifsSessionDeleteURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on CifsSessionDeleteURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on CifsSessionDeleteURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *CifsSessionDeleteURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
