// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CifsServiceDeleteHandlerFunc turns a function with the right signature into a cifs service delete handler
type CifsServiceDeleteHandlerFunc func(CifsServiceDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CifsServiceDeleteHandlerFunc) Handle(params CifsServiceDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CifsServiceDeleteHandler interface for that can handle valid cifs service delete params
type CifsServiceDeleteHandler interface {
	Handle(CifsServiceDeleteParams, interface{}) middleware.Responder
}

// NewCifsServiceDelete creates a new http.Handler for the cifs service delete operation
func NewCifsServiceDelete(ctx *middleware.Context, handler CifsServiceDeleteHandler) *CifsServiceDelete {
	return &CifsServiceDelete{Context: ctx, Handler: handler}
}

/*
	CifsServiceDelete swagger:route DELETE /protocols/cifs/services/{svm.uuid} NAS cifsServiceDelete

Deletes a CIFS server and related CIFS configurations.<br/>
</br>Important notes:
* The default value for the "force" field is false.
* If the "force" field is set along with user login credentials, the local CIFS configuration will be deleted irrespective of any communication errors.
* If the "force" field alone is set without passing the user login credentials, the local CIFS configuration will be deleted by not making any request to Active Directory.
### Related ONTAP commands
* `vserver cifs server delete`
* `vserver cifs remove-netbios-aliases`
### Learn more
* [`DOC /protocols/cifs/services`](#docs-NAS-protocols_cifs_services)
*/
type CifsServiceDelete struct {
	Context *middleware.Context
	Handler CifsServiceDeleteHandler
}

func (o *CifsServiceDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCifsServiceDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
