// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FileDirectorySecurityACLCreateHandlerFunc turns a function with the right signature into a file directory security acl create handler
type FileDirectorySecurityACLCreateHandlerFunc func(FileDirectorySecurityACLCreateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn FileDirectorySecurityACLCreateHandlerFunc) Handle(params FileDirectorySecurityACLCreateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// FileDirectorySecurityACLCreateHandler interface for that can handle valid file directory security acl create params
type FileDirectorySecurityACLCreateHandler interface {
	Handle(FileDirectorySecurityACLCreateParams, interface{}) middleware.Responder
}

// NewFileDirectorySecurityACLCreate creates a new http.Handler for the file directory security acl create operation
func NewFileDirectorySecurityACLCreate(ctx *middleware.Context, handler FileDirectorySecurityACLCreateHandler) *FileDirectorySecurityACLCreate {
	return &FileDirectorySecurityACLCreate{Context: ctx, Handler: handler}
}

/*
	FileDirectorySecurityACLCreate swagger:route POST /protocols/file-security/permissions/{svm.uuid}/{path}/acl NAS fileDirectorySecurityAclCreate

Adds the new SACL/DACL ACE.
You must keep the following points in mind while using these endpoints:
* SLAG applies to all files and/or directories in a volume hence, inheritance is not required to be propagated.
* Set access_control field to slag while adding SLAG ACE.
* Set access_control field to file_directory while adding file-directory ACE. By Default access_control field is set to file_directory.
* For SLAG, valid apply_to combinations are "this-folder, sub-folders", "files", "this-folder, sub-folders, files".
### Required properties
* `user` - Name of the user to which the ACE applies.
* `access` - Specifies whether the ACE is for DACL or SACL.
### Related ONTAP commands
* `vserver security file-directory ntfs dacl add`
* `vserver security file-directory ntfs sacl add`
*/
type FileDirectorySecurityACLCreate struct {
	Context *middleware.Context
	Handler FileDirectorySecurityACLCreateHandler
}

func (o *FileDirectorySecurityACLCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFileDirectorySecurityACLCreateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
