// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// FpolicyPolicyCollectionGetOKCode is the HTTP code returned for type FpolicyPolicyCollectionGetOK
const FpolicyPolicyCollectionGetOKCode int = 200

/*
FpolicyPolicyCollectionGetOK OK

swagger:response fpolicyPolicyCollectionGetOK
*/
type FpolicyPolicyCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.FpolicyPolicyResponse `json:"body,omitempty"`
}

// NewFpolicyPolicyCollectionGetOK creates FpolicyPolicyCollectionGetOK with default headers values
func NewFpolicyPolicyCollectionGetOK() *FpolicyPolicyCollectionGetOK {

	return &FpolicyPolicyCollectionGetOK{}
}

// WithPayload adds the payload to the fpolicy policy collection get o k response
func (o *FpolicyPolicyCollectionGetOK) WithPayload(payload *models.FpolicyPolicyResponse) *FpolicyPolicyCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fpolicy policy collection get o k response
func (o *FpolicyPolicyCollectionGetOK) SetPayload(payload *models.FpolicyPolicyResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FpolicyPolicyCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
FpolicyPolicyCollectionGetDefault Error

swagger:response fpolicyPolicyCollectionGetDefault
*/
type FpolicyPolicyCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFpolicyPolicyCollectionGetDefault creates FpolicyPolicyCollectionGetDefault with default headers values
func NewFpolicyPolicyCollectionGetDefault(code int) *FpolicyPolicyCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &FpolicyPolicyCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the fpolicy policy collection get default response
func (o *FpolicyPolicyCollectionGetDefault) WithStatusCode(code int) *FpolicyPolicyCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the fpolicy policy collection get default response
func (o *FpolicyPolicyCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the fpolicy policy collection get default response
func (o *FpolicyPolicyCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *FpolicyPolicyCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fpolicy policy collection get default response
func (o *FpolicyPolicyCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FpolicyPolicyCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
