// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// FpolicyEventCollectionGetOKCode is the HTTP code returned for type FpolicyEventCollectionGetOK
const FpolicyEventCollectionGetOKCode int = 200

/*
FpolicyEventCollectionGetOK OK

swagger:response fpolicyEventCollectionGetOK
*/
type FpolicyEventCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.FpolicyEventResponse `json:"body,omitempty"`
}

// NewFpolicyEventCollectionGetOK creates FpolicyEventCollectionGetOK with default headers values
func NewFpolicyEventCollectionGetOK() *FpolicyEventCollectionGetOK {

	return &FpolicyEventCollectionGetOK{}
}

// WithPayload adds the payload to the fpolicy event collection get o k response
func (o *FpolicyEventCollectionGetOK) WithPayload(payload *models.FpolicyEventResponse) *FpolicyEventCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fpolicy event collection get o k response
func (o *FpolicyEventCollectionGetOK) SetPayload(payload *models.FpolicyEventResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FpolicyEventCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
FpolicyEventCollectionGetDefault Error

swagger:response fpolicyEventCollectionGetDefault
*/
type FpolicyEventCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFpolicyEventCollectionGetDefault creates FpolicyEventCollectionGetDefault with default headers values
func NewFpolicyEventCollectionGetDefault(code int) *FpolicyEventCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &FpolicyEventCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the fpolicy event collection get default response
func (o *FpolicyEventCollectionGetDefault) WithStatusCode(code int) *FpolicyEventCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the fpolicy event collection get default response
func (o *FpolicyEventCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the fpolicy event collection get default response
func (o *FpolicyEventCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *FpolicyEventCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fpolicy event collection get default response
func (o *FpolicyEventCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FpolicyEventCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
