// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FpolicyPolicyDeleteHandlerFunc turns a function with the right signature into a fpolicy policy delete handler
type FpolicyPolicyDeleteHandlerFunc func(FpolicyPolicyDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn FpolicyPolicyDeleteHandlerFunc) Handle(params FpolicyPolicyDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// FpolicyPolicyDeleteHandler interface for that can handle valid fpolicy policy delete params
type FpolicyPolicyDeleteHandler interface {
	Handle(FpolicyPolicyDeleteParams, interface{}) middleware.Responder
}

// NewFpolicyPolicyDelete creates a new http.Handler for the fpolicy policy delete operation
func NewFpolicyPolicyDelete(ctx *middleware.Context, handler FpolicyPolicyDeleteHandler) *FpolicyPolicyDelete {
	return &FpolicyPolicyDelete{Context: ctx, Handler: handler}
}

/*
	FpolicyPolicyDelete swagger:route DELETE /protocols/fpolicy/{svm.uuid}/policies/{name} NAS fpolicyPolicyDelete

Deletes a particular FPolicy policy configuration for a specified SVM. To delete a policy, you must first disable the policy.
### Related ONTAP commands
* `fpolicy policy scope delete`
* `fpolicy policy delete`
### Learn more
* [`DOC /protocols/fpolicy/{svm.uuid}/policies`](#docs-NAS-protocols_fpolicy_{svm.uuid}_policies)
*/
type FpolicyPolicyDelete struct {
	Context *middleware.Context
	Handler FpolicyPolicyDeleteHandler
}

func (o *FpolicyPolicyDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFpolicyPolicyDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
