// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// KerberosRealmDeleteHandlerFunc turns a function with the right signature into a kerberos realm delete handler
type KerberosRealmDeleteHandlerFunc func(KerberosRealmDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn KerberosRealmDeleteHandlerFunc) Handle(params KerberosRealmDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// KerberosRealmDeleteHandler interface for that can handle valid kerberos realm delete params
type KerberosRealmDeleteHandler interface {
	Handle(KerberosRealmDeleteParams, interface{}) middleware.Responder
}

// NewKerberosRealmDelete creates a new http.Handler for the kerberos realm delete operation
func NewKerberosRealmDelete(ctx *middleware.Context, handler KerberosRealmDeleteHandler) *KerberosRealmDelete {
	return &KerberosRealmDelete{Context: ctx, Handler: handler}
}

/*
	KerberosRealmDelete swagger:route DELETE /protocols/nfs/kerberos/realms/{svm.uuid}/{name} NAS kerberosRealmDelete

Deletes a Kerberos realm.
* `vserver nfs kerberos realm delete`
### Learn more
* [`DOC /protocols/nfs/kerberos/realms`](#docs-NAS-protocols_nfs_kerberos_realms)
*/
type KerberosRealmDelete struct {
	Context *middleware.Context
	Handler KerberosRealmDeleteHandler
}

func (o *KerberosRealmDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewKerberosRealmDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
