// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// KerberosInterfaceCollectionGetOKCode is the HTTP code returned for type KerberosInterfaceCollectionGetOK
const KerberosInterfaceCollectionGetOKCode int = 200

/*
KerberosInterfaceCollectionGetOK OK

swagger:response kerberosInterfaceCollectionGetOK
*/
type KerberosInterfaceCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.KerberosInterfaceResponse `json:"body,omitempty"`
}

// NewKerberosInterfaceCollectionGetOK creates KerberosInterfaceCollectionGetOK with default headers values
func NewKerberosInterfaceCollectionGetOK() *KerberosInterfaceCollectionGetOK {

	return &KerberosInterfaceCollectionGetOK{}
}

// WithPayload adds the payload to the kerberos interface collection get o k response
func (o *KerberosInterfaceCollectionGetOK) WithPayload(payload *models.KerberosInterfaceResponse) *KerberosInterfaceCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the kerberos interface collection get o k response
func (o *KerberosInterfaceCollectionGetOK) SetPayload(payload *models.KerberosInterfaceResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *KerberosInterfaceCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
KerberosInterfaceCollectionGetDefault Error

swagger:response kerberosInterfaceCollectionGetDefault
*/
type KerberosInterfaceCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewKerberosInterfaceCollectionGetDefault creates KerberosInterfaceCollectionGetDefault with default headers values
func NewKerberosInterfaceCollectionGetDefault(code int) *KerberosInterfaceCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &KerberosInterfaceCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the kerberos interface collection get default response
func (o *KerberosInterfaceCollectionGetDefault) WithStatusCode(code int) *KerberosInterfaceCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the kerberos interface collection get default response
func (o *KerberosInterfaceCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the kerberos interface collection get default response
func (o *KerberosInterfaceCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *KerberosInterfaceCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the kerberos interface collection get default response
func (o *KerberosInterfaceCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *KerberosInterfaceCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
