// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// KerberosInterfaceGetOKCode is the HTTP code returned for type KerberosInterfaceGetOK
const KerberosInterfaceGetOKCode int = 200

/*
KerberosInterfaceGetOK OK

swagger:response kerberosInterfaceGetOK
*/
type KerberosInterfaceGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.KerberosInterface `json:"body,omitempty"`
}

// NewKerberosInterfaceGetOK creates KerberosInterfaceGetOK with default headers values
func NewKerberosInterfaceGetOK() *KerberosInterfaceGetOK {

	return &KerberosInterfaceGetOK{}
}

// WithPayload adds the payload to the kerberos interface get o k response
func (o *KerberosInterfaceGetOK) WithPayload(payload *models.KerberosInterface) *KerberosInterfaceGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the kerberos interface get o k response
func (o *KerberosInterfaceGetOK) SetPayload(payload *models.KerberosInterface) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *KerberosInterfaceGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
KerberosInterfaceGetDefault Error

swagger:response kerberosInterfaceGetDefault
*/
type KerberosInterfaceGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewKerberosInterfaceGetDefault creates KerberosInterfaceGetDefault with default headers values
func NewKerberosInterfaceGetDefault(code int) *KerberosInterfaceGetDefault {
	if code <= 0 {
		code = 500
	}

	return &KerberosInterfaceGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the kerberos interface get default response
func (o *KerberosInterfaceGetDefault) WithStatusCode(code int) *KerberosInterfaceGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the kerberos interface get default response
func (o *KerberosInterfaceGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the kerberos interface get default response
func (o *KerberosInterfaceGetDefault) WithPayload(payload *models.ErrorResponse) *KerberosInterfaceGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the kerberos interface get default response
func (o *KerberosInterfaceGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *KerberosInterfaceGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
