// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// LocalCifsUserGetHandlerFunc turns a function with the right signature into a local cifs user get handler
type LocalCifsUserGetHandlerFunc func(LocalCifsUserGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn LocalCifsUserGetHandlerFunc) Handle(params LocalCifsUserGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// LocalCifsUserGetHandler interface for that can handle valid local cifs user get params
type LocalCifsUserGetHandler interface {
	Handle(LocalCifsUserGetParams, interface{}) middleware.Responder
}

// NewLocalCifsUserGet creates a new http.Handler for the local cifs user get operation
func NewLocalCifsUserGet(ctx *middleware.Context, handler LocalCifsUserGetHandler) *LocalCifsUserGet {
	return &LocalCifsUserGet{Context: ctx, Handler: handler}
}

/*
	LocalCifsUserGet swagger:route GET /protocols/cifs/local-users/{svm.uuid}/{sid} NAS localCifsUserGet

Retrieves local user information for the specified user and SVM.
### Advanced properties
* `membership`
### Related ONTAP commands
* `vserver cifs users-and-groups local-user show`
* `vserver cifs users-and-groups local-user show-membership`
### Learn more
* [`DOC /protocols/cifs/local-users`](#docs-NAS-protocols_cifs_local-users)
*/
type LocalCifsUserGet struct {
	Context *middleware.Context
	Handler LocalCifsUserGetHandler
}

func (o *LocalCifsUserGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewLocalCifsUserGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
