// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// NfsClientsGetHandlerFunc turns a function with the right signature into a nfs clients get handler
type NfsClientsGetHandlerFunc func(NfsClientsGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn NfsClientsGetHandlerFunc) Handle(params NfsClientsGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// NfsClientsGetHandler interface for that can handle valid nfs clients get params
type NfsClientsGetHandler interface {
	Handle(NfsClientsGetParams, interface{}) middleware.Responder
}

// NewNfsClientsGet creates a new http.Handler for the nfs clients get operation
func NewNfsClientsGet(ctx *middleware.Context, handler NfsClientsGetHandler) *NfsClientsGet {
	return &NfsClientsGet{Context: ctx, Handler: handler}
}

/*
	NfsClientsGet swagger:route GET /protocols/nfs/connected-clients NAS nfsClientsGet

Retrieves the NFS configuration of SVMs.
### Expensive properties
export_policy.id is expensive field. It is not included by default in GET results and must be explicitly requested using the `fields` query parameter. See [`Requesting specific fields`](#Requesting_specific_fields) to learn more.
* `export_policy.id`
*/
type NfsClientsGet struct {
	Context *middleware.Context
	Handler NfsClientsGetHandler
}

func (o *NfsClientsGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewNfsClientsGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
