// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// S3AuditCreateCreatedCode is the HTTP code returned for type S3AuditCreateCreated
const S3AuditCreateCreatedCode int = 201

/*
S3AuditCreateCreated Created

swagger:response s3AuditCreateCreated
*/
type S3AuditCreateCreated struct {
	/*Useful for tracking the resource location

	 */
	Location string `json:"Location"`

	/*
	  In: Body
	*/
	Payload *models.S3AuditResponse `json:"body,omitempty"`
}

// NewS3AuditCreateCreated creates S3AuditCreateCreated with default headers values
func NewS3AuditCreateCreated() *S3AuditCreateCreated {

	return &S3AuditCreateCreated{}
}

// WithLocation adds the location to the s3 audit create created response
func (o *S3AuditCreateCreated) WithLocation(location string) *S3AuditCreateCreated {
	o.Location = location
	return o
}

// SetLocation sets the location to the s3 audit create created response
func (o *S3AuditCreateCreated) SetLocation(location string) {
	o.Location = location
}

// WithPayload adds the payload to the s3 audit create created response
func (o *S3AuditCreateCreated) WithPayload(payload *models.S3AuditResponse) *S3AuditCreateCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the s3 audit create created response
func (o *S3AuditCreateCreated) SetPayload(payload *models.S3AuditResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *S3AuditCreateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// S3AuditCreateAcceptedCode is the HTTP code returned for type S3AuditCreateAccepted
const S3AuditCreateAcceptedCode int = 202

/*
S3AuditCreateAccepted Accepted

swagger:response s3AuditCreateAccepted
*/
type S3AuditCreateAccepted struct {
	/*Useful for tracking the resource location

	 */
	Location string `json:"Location"`

	/*
	  In: Body
	*/
	Payload *models.S3AuditResponse `json:"body,omitempty"`
}

// NewS3AuditCreateAccepted creates S3AuditCreateAccepted with default headers values
func NewS3AuditCreateAccepted() *S3AuditCreateAccepted {

	return &S3AuditCreateAccepted{}
}

// WithLocation adds the location to the s3 audit create accepted response
func (o *S3AuditCreateAccepted) WithLocation(location string) *S3AuditCreateAccepted {
	o.Location = location
	return o
}

// SetLocation sets the location to the s3 audit create accepted response
func (o *S3AuditCreateAccepted) SetLocation(location string) {
	o.Location = location
}

// WithPayload adds the payload to the s3 audit create accepted response
func (o *S3AuditCreateAccepted) WithPayload(payload *models.S3AuditResponse) *S3AuditCreateAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the s3 audit create accepted response
func (o *S3AuditCreateAccepted) SetPayload(payload *models.S3AuditResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *S3AuditCreateAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
S3AuditCreateDefault ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 140902401 | Failed to create an audit configuration for the SVM. |
| 140902402 | Audit configuration is already present. |
| 140902402 | Audit configuration is already enabled. |
| 140902403 | Failed to create staging volume. |
| 140902415 | Failed to modify an audit configuration because no audit configuration exists for the SVM. |
| 140902416 | Failed to modify audit configuration for SVM. |
| 140902422 | Final consolidation is in progress, audit delete failed. |
| 140902423 | Failed to delete the audit configuration for the SVM. |
| 140902425 | Audit configuration is not available for disabling. |
| 140902430 | Audit configuration is not available for enabling. |
| 140902431 | Audit enable failed, audit configuration already enabled for the SVM. |
| 140902432 | Final consolidation is in progress, audit enable failed. |
| 140902445 | Audit disable failed, audit configuration does not exist for the SVM. |
| 140902446 | Audit disable failed, audit configuration does not exist for the SVM. |
| 140902447 | Audit disable failed. |
| 140902456 | The specified log_path does not exist. |
| 140902457 | The log_path must be a directory. |
| 140902458 | The log_path must be a canonical path in the SVM's namespace. |
| 140902459 | The log_path cannot be empty. |
| 140902460 | Rotate size must be greater than or equal to 1024 KB. |
| 140902461 | The destination path must not contain a symbolic link. |
| 140902470 | The log_path exceeds a maximum supported length of characters. |
| 140902471 | The log_path contains an unsupported read-only (DP/LS) volume. |
| 140902472 | The log_path is not a valid destination for the SVM. |
| 140902474 | The log_path contains an unsupported Snaplock volume. |
| 140902478 | The log_path validation failed. |
| 140902478 | The log_path cannot be accessed for validation. |
| 140902490 | Audit configuration is absent for rotate. |
| 140902491 | Failed to rotate audit log. |
| 140902492 | Cannot rotate audit log, auditing is not enabled for this SVM. |
Also see the table of common errors in the <a href="#Response_body">Response body</a> overview section of this documentation.
ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 9699340    | SVM UUID lookup failed                                                        |
| 9699407    | Additional fields are provided                                                |

swagger:response s3AuditCreateDefault
*/
type S3AuditCreateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewS3AuditCreateDefault creates S3AuditCreateDefault with default headers values
func NewS3AuditCreateDefault(code int) *S3AuditCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &S3AuditCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the s3 audit create default response
func (o *S3AuditCreateDefault) WithStatusCode(code int) *S3AuditCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the s3 audit create default response
func (o *S3AuditCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the s3 audit create default response
func (o *S3AuditCreateDefault) WithPayload(payload *models.ErrorResponse) *S3AuditCreateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the s3 audit create default response
func (o *S3AuditCreateDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *S3AuditCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
