// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// VscanScannerPoolGetOKCode is the HTTP code returned for type VscanScannerPoolGetOK
const VscanScannerPoolGetOKCode int = 200

/*
VscanScannerPoolGetOK OK

swagger:response vscanScannerPoolGetOK
*/
type VscanScannerPoolGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.VscanScannerPool `json:"body,omitempty"`
}

// NewVscanScannerPoolGetOK creates VscanScannerPoolGetOK with default headers values
func NewVscanScannerPoolGetOK() *VscanScannerPoolGetOK {

	return &VscanScannerPoolGetOK{}
}

// WithPayload adds the payload to the vscan scanner pool get o k response
func (o *VscanScannerPoolGetOK) WithPayload(payload *models.VscanScannerPool) *VscanScannerPoolGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the vscan scanner pool get o k response
func (o *VscanScannerPoolGetOK) SetPayload(payload *models.VscanScannerPool) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VscanScannerPoolGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
VscanScannerPoolGetDefault Error

swagger:response vscanScannerPoolGetDefault
*/
type VscanScannerPoolGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewVscanScannerPoolGetDefault creates VscanScannerPoolGetDefault with default headers values
func NewVscanScannerPoolGetDefault(code int) *VscanScannerPoolGetDefault {
	if code <= 0 {
		code = 500
	}

	return &VscanScannerPoolGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the vscan scanner pool get default response
func (o *VscanScannerPoolGetDefault) WithStatusCode(code int) *VscanScannerPoolGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the vscan scanner pool get default response
func (o *VscanScannerPoolGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the vscan scanner pool get default response
func (o *VscanScannerPoolGetDefault) WithPayload(payload *models.ErrorResponse) *VscanScannerPoolGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the vscan scanner pool get default response
func (o *VscanScannerPoolGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VscanScannerPoolGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
