// Code generated by go-swagger; DO NOT EDIT.

package name_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// DNSCollectionGetOKCode is the HTTP code returned for type DNSCollectionGetOK
const DNSCollectionGetOKCode int = 200

/*
DNSCollectionGetOK OK

swagger:response dnsCollectionGetOK
*/
type DNSCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.DNSResponse `json:"body,omitempty"`
}

// NewDNSCollectionGetOK creates DNSCollectionGetOK with default headers values
func NewDNSCollectionGetOK() *DNSCollectionGetOK {

	return &DNSCollectionGetOK{}
}

// WithPayload adds the payload to the dns collection get o k response
func (o *DNSCollectionGetOK) WithPayload(payload *models.DNSResponse) *DNSCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the dns collection get o k response
func (o *DNSCollectionGetOK) SetPayload(payload *models.DNSResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DNSCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
DNSCollectionGetDefault Error

swagger:response dnsCollectionGetDefault
*/
type DNSCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDNSCollectionGetDefault creates DNSCollectionGetDefault with default headers values
func NewDNSCollectionGetDefault(code int) *DNSCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &DNSCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the dns collection get default response
func (o *DNSCollectionGetDefault) WithStatusCode(code int) *DNSCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the dns collection get default response
func (o *DNSCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the dns collection get default response
func (o *DNSCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *DNSCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the dns collection get default response
func (o *DNSCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DNSCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
