// Code generated by go-swagger; DO NOT EDIT.

package name_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// LdapSchemaGetHandlerFunc turns a function with the right signature into a ldap schema get handler
type LdapSchemaGetHandlerFunc func(LdapSchemaGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn LdapSchemaGetHandlerFunc) Handle(params LdapSchemaGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// LdapSchemaGetHandler interface for that can handle valid ldap schema get params
type LdapSchemaGetHandler interface {
	Handle(LdapSchemaGetParams, interface{}) middleware.Responder
}

// NewLdapSchemaGet creates a new http.Handler for the ldap schema get operation
func NewLdapSchemaGet(ctx *middleware.Context, handler LdapSchemaGetHandler) *LdapSchemaGet {
	return &LdapSchemaGet{Context: ctx, Handler: handler}
}

/*
	LdapSchemaGet swagger:route GET /name-services/ldap-schemas/{owner.uuid}/{name} Name-Services ldapSchemaGet

Retrieves LDAP schema details for a given owner and schema.
### Related ONTAP commands
* `vserver services name-service ldap client schema show`
*/
type LdapSchemaGet struct {
	Context *middleware.Context
	Handler LdapSchemaGetHandler
}

func (o *LdapSchemaGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewLdapSchemaGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
