// Code generated by go-swagger; DO NOT EDIT.

package name_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// NameMappingCreateCreatedCode is the HTTP code returned for type NameMappingCreateCreated
const NameMappingCreateCreatedCode int = 201

/*
NameMappingCreateCreated Created

swagger:response nameMappingCreateCreated
*/
type NameMappingCreateCreated struct {
	/*Useful for tracking the resource location

	 */
	Location string `json:"Location"`

	/*
	  In: Body
	*/
	Payload *models.NameMappingResponse `json:"body,omitempty"`
}

// NewNameMappingCreateCreated creates NameMappingCreateCreated with default headers values
func NewNameMappingCreateCreated() *NameMappingCreateCreated {

	return &NameMappingCreateCreated{}
}

// WithLocation adds the location to the name mapping create created response
func (o *NameMappingCreateCreated) WithLocation(location string) *NameMappingCreateCreated {
	o.Location = location
	return o
}

// SetLocation sets the location to the name mapping create created response
func (o *NameMappingCreateCreated) SetLocation(location string) {
	o.Location = location
}

// WithPayload adds the payload to the name mapping create created response
func (o *NameMappingCreateCreated) WithPayload(payload *models.NameMappingResponse) *NameMappingCreateCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the name mapping create created response
func (o *NameMappingCreateCreated) SetPayload(payload *models.NameMappingResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NameMappingCreateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
NameMappingCreateDefault ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 65798185   | Failed to resolve the specified hostname   |
| 65798173   | The name mapping pattern already exists with a more generic IP qualifier   |
| 65798149   | Invalid index for the name mapping entry   |
| 2621706    | The specified svm.uuid and svm.name refer to different SVMs   |

swagger:response nameMappingCreateDefault
*/
type NameMappingCreateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewNameMappingCreateDefault creates NameMappingCreateDefault with default headers values
func NewNameMappingCreateDefault(code int) *NameMappingCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &NameMappingCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the name mapping create default response
func (o *NameMappingCreateDefault) WithStatusCode(code int) *NameMappingCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the name mapping create default response
func (o *NameMappingCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the name mapping create default response
func (o *NameMappingCreateDefault) WithPayload(payload *models.ErrorResponse) *NameMappingCreateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the name mapping create default response
func (o *NameMappingCreateDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NameMappingCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
