// Code generated by go-swagger; DO NOT EDIT.

package name_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// NetgroupsSettingsCollectionGetURL generates an URL for the netgroups settings collection get operation
type NetgroupsSettingsCollectionGetURL struct {
	Enabled                    *bool
	Fields                     []string
	MaxRecords                 *int64
	NegativeCacheEnabledByhost *bool
	NegativeTTLByhost          *string
	OrderBy                    []string
	ReturnRecords              *bool
	ReturnTimeout              *int64
	SvmName                    *string
	SvmUUID                    *string
	TTLByhost                  *string
	TTLForMembers              *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *NetgroupsSettingsCollectionGetURL) WithBasePath(bp string) *NetgroupsSettingsCollectionGetURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *NetgroupsSettingsCollectionGetURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *NetgroupsSettingsCollectionGetURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/name-services/cache/netgroup/settings"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var enabledQ string
	if o.Enabled != nil {
		enabledQ = swag.FormatBool(*o.Enabled)
	}
	if enabledQ != "" {
		qs.Set("enabled", enabledQ)
	}

	var fieldsIR []string
	for _, fieldsI := range o.Fields {
		fieldsIS := fieldsI
		if fieldsIS != "" {
			fieldsIR = append(fieldsIR, fieldsIS)
		}
	}

	fields := swag.JoinByFormat(fieldsIR, "csv")

	if len(fields) > 0 {
		qsv := fields[0]
		if qsv != "" {
			qs.Set("fields", qsv)
		}
	}

	var maxRecordsQ string
	if o.MaxRecords != nil {
		maxRecordsQ = swag.FormatInt64(*o.MaxRecords)
	}
	if maxRecordsQ != "" {
		qs.Set("max_records", maxRecordsQ)
	}

	var negativeCacheEnabledByhostQ string
	if o.NegativeCacheEnabledByhost != nil {
		negativeCacheEnabledByhostQ = swag.FormatBool(*o.NegativeCacheEnabledByhost)
	}
	if negativeCacheEnabledByhostQ != "" {
		qs.Set("negative_cache_enabled_byhost", negativeCacheEnabledByhostQ)
	}

	var negativeTTLByhostQ string
	if o.NegativeTTLByhost != nil {
		negativeTTLByhostQ = *o.NegativeTTLByhost
	}
	if negativeTTLByhostQ != "" {
		qs.Set("negative_ttl_byhost", negativeTTLByhostQ)
	}

	var orderByIR []string
	for _, orderByI := range o.OrderBy {
		orderByIS := orderByI
		if orderByIS != "" {
			orderByIR = append(orderByIR, orderByIS)
		}
	}

	orderBy := swag.JoinByFormat(orderByIR, "csv")

	if len(orderBy) > 0 {
		qsv := orderBy[0]
		if qsv != "" {
			qs.Set("order_by", qsv)
		}
	}

	var returnRecordsQ string
	if o.ReturnRecords != nil {
		returnRecordsQ = swag.FormatBool(*o.ReturnRecords)
	}
	if returnRecordsQ != "" {
		qs.Set("return_records", returnRecordsQ)
	}

	var returnTimeoutQ string
	if o.ReturnTimeout != nil {
		returnTimeoutQ = swag.FormatInt64(*o.ReturnTimeout)
	}
	if returnTimeoutQ != "" {
		qs.Set("return_timeout", returnTimeoutQ)
	}

	var svmNameQ string
	if o.SvmName != nil {
		svmNameQ = *o.SvmName
	}
	if svmNameQ != "" {
		qs.Set("svm.name", svmNameQ)
	}

	var svmUUIDQ string
	if o.SvmUUID != nil {
		svmUUIDQ = *o.SvmUUID
	}
	if svmUUIDQ != "" {
		qs.Set("svm.uuid", svmUUIDQ)
	}

	var tTLByhostQ string
	if o.TTLByhost != nil {
		tTLByhostQ = *o.TTLByhost
	}
	if tTLByhostQ != "" {
		qs.Set("ttl_byhost", tTLByhostQ)
	}

	var tTLForMembersQ string
	if o.TTLForMembers != nil {
		tTLForMembersQ = *o.TTLForMembers
	}
	if tTLForMembersQ != "" {
		qs.Set("ttl_for_members", tTLForMembersQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *NetgroupsSettingsCollectionGetURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *NetgroupsSettingsCollectionGetURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *NetgroupsSettingsCollectionGetURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on NetgroupsSettingsCollectionGetURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on NetgroupsSettingsCollectionGetURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *NetgroupsSettingsCollectionGetURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
