// Code generated by go-swagger; DO NOT EDIT.

package name_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// NisGetHandlerFunc turns a function with the right signature into a nis get handler
type NisGetHandlerFunc func(NisGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn NisGetHandlerFunc) Handle(params NisGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// NisGetHandler interface for that can handle valid nis get params
type NisGetHandler interface {
	Handle(NisGetParams, interface{}) middleware.Responder
}

// NewNisGet creates a new http.Handler for the nis get operation
func NewNisGet(ctx *middleware.Context, handler NisGetHandler) *NisGet {
	return &NisGet{Context: ctx, Handler: handler}
}

/*
	NisGet swagger:route GET /name-services/nis/{svm.uuid} Name-Services nisGet

Retrieves NIS domain and server configurations of an SVM. Both NIS domain and servers are displayed by default. The bound_servers field indicates the successfully bound NIS servers.
### Related ONTAP commands
* `vserver services name-service nis-domain show`
* `vserver services name-service nis-domain show-bound`
* `vserver services name-service nis-domain show-bound-debug`
### Learn more
* [`DOC /name-services/nis`](#docs-name-services-name-services_nis)
*/
type NisGet struct {
	Context *middleware.Context
	Handler NisGetHandler
}

func (o *NisGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewNisGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
