// Code generated by go-swagger; DO NOT EDIT.

package name_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UnixUserSettingsCollectionGetHandlerFunc turns a function with the right signature into a unix user settings collection get handler
type UnixUserSettingsCollectionGetHandlerFunc func(UnixUserSettingsCollectionGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UnixUserSettingsCollectionGetHandlerFunc) Handle(params UnixUserSettingsCollectionGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UnixUserSettingsCollectionGetHandler interface for that can handle valid unix user settings collection get params
type UnixUserSettingsCollectionGetHandler interface {
	Handle(UnixUserSettingsCollectionGetParams, interface{}) middleware.Responder
}

// NewUnixUserSettingsCollectionGet creates a new http.Handler for the unix user settings collection get operation
func NewUnixUserSettingsCollectionGet(ctx *middleware.Context, handler UnixUserSettingsCollectionGetHandler) *UnixUserSettingsCollectionGet {
	return &UnixUserSettingsCollectionGet{Context: ctx, Handler: handler}
}

/*
	UnixUserSettingsCollectionGet swagger:route GET /name-services/cache/unix-user/settings Name-Services unixUserSettingsCollectionGet

Retrieves unix-user cache settings.
### Related ONTAP commands
* `vserver services name-service cache unix-user settings show`
### Learn more
* [`DOC /name-services/cache/unix-user/settings`](#docs-name-services-name-services_cache_unix-user_settings)
*/
type UnixUserSettingsCollectionGet struct {
	Context *middleware.Context
	Handler UnixUserSettingsCollectionGetHandler
}

func (o *UnixUserSettingsCollectionGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUnixUserSettingsCollectionGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
