// Code generated by go-swagger; DO NOT EDIT.

package name_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// UnixGroupGetOKCode is the HTTP code returned for type UnixGroupGetOK
const UnixGroupGetOKCode int = 200

/*
UnixGroupGetOK OK

swagger:response unixGroupGetOK
*/
type UnixGroupGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.UnixGroup `json:"body,omitempty"`
}

// NewUnixGroupGetOK creates UnixGroupGetOK with default headers values
func NewUnixGroupGetOK() *UnixGroupGetOK {

	return &UnixGroupGetOK{}
}

// WithPayload adds the payload to the unix group get o k response
func (o *UnixGroupGetOK) WithPayload(payload *models.UnixGroup) *UnixGroupGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the unix group get o k response
func (o *UnixGroupGetOK) SetPayload(payload *models.UnixGroup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UnixGroupGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
UnixGroupGetDefault Error

swagger:response unixGroupGetDefault
*/
type UnixGroupGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewUnixGroupGetDefault creates UnixGroupGetDefault with default headers values
func NewUnixGroupGetDefault(code int) *UnixGroupGetDefault {
	if code <= 0 {
		code = 500
	}

	return &UnixGroupGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the unix group get default response
func (o *UnixGroupGetDefault) WithStatusCode(code int) *UnixGroupGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the unix group get default response
func (o *UnixGroupGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the unix group get default response
func (o *UnixGroupGetDefault) WithPayload(payload *models.ErrorResponse) *UnixGroupGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the unix group get default response
func (o *UnixGroupGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UnixGroupGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
