// Code generated by go-swagger; DO NOT EDIT.

package support

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// AutoUpdateConfigurationGetOKCode is the HTTP code returned for type AutoUpdateConfigurationGetOK
const AutoUpdateConfigurationGetOKCode int = 200

/*
AutoUpdateConfigurationGetOK OK

swagger:response autoUpdateConfigurationGetOK
*/
type AutoUpdateConfigurationGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.AutoUpdateConfiguration `json:"body,omitempty"`
}

// NewAutoUpdateConfigurationGetOK creates AutoUpdateConfigurationGetOK with default headers values
func NewAutoUpdateConfigurationGetOK() *AutoUpdateConfigurationGetOK {

	return &AutoUpdateConfigurationGetOK{}
}

// WithPayload adds the payload to the auto update configuration get o k response
func (o *AutoUpdateConfigurationGetOK) WithPayload(payload *models.AutoUpdateConfiguration) *AutoUpdateConfigurationGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auto update configuration get o k response
func (o *AutoUpdateConfigurationGetOK) SetPayload(payload *models.AutoUpdateConfiguration) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AutoUpdateConfigurationGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
AutoUpdateConfigurationGetDefault Error

swagger:response autoUpdateConfigurationGetDefault
*/
type AutoUpdateConfigurationGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewAutoUpdateConfigurationGetDefault creates AutoUpdateConfigurationGetDefault with default headers values
func NewAutoUpdateConfigurationGetDefault(code int) *AutoUpdateConfigurationGetDefault {
	if code <= 0 {
		code = 500
	}

	return &AutoUpdateConfigurationGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the auto update configuration get default response
func (o *AutoUpdateConfigurationGetDefault) WithStatusCode(code int) *AutoUpdateConfigurationGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the auto update configuration get default response
func (o *AutoUpdateConfigurationGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the auto update configuration get default response
func (o *AutoUpdateConfigurationGetDefault) WithPayload(payload *models.ErrorResponse) *AutoUpdateConfigurationGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auto update configuration get default response
func (o *AutoUpdateConfigurationGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AutoUpdateConfigurationGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
