// Code generated by go-swagger; DO NOT EDIT.

package support

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// AutoUpdateStatusCollectionGetURL generates an URL for the auto update status collection get operation
type AutoUpdateStatusCollectionGetURL struct {
	ContentCategory        *string
	ContentType            *string
	CreationTime           *string
	Description            *string
	EndTime                *string
	ExpiryTime             *string
	Fields                 []string
	LastStateChangeTime    *string
	MaxRecords             *int64
	OrderBy                []string
	PackageID              *string
	PercentComplete        *int64
	RemainingTime          *string
	ReturnRecords          *bool
	ReturnTimeout          *int64
	ScheduledTime          *string
	StartTime              *string
	State                  *string
	StatusArgumentsCode    *string
	StatusArgumentsMessage *string
	StatusCode             *string
	StatusMessage          *string
	UUID                   *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *AutoUpdateStatusCollectionGetURL) WithBasePath(bp string) *AutoUpdateStatusCollectionGetURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *AutoUpdateStatusCollectionGetURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *AutoUpdateStatusCollectionGetURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/support/auto-update/updates"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var contentCategoryQ string
	if o.ContentCategory != nil {
		contentCategoryQ = *o.ContentCategory
	}
	if contentCategoryQ != "" {
		qs.Set("content_category", contentCategoryQ)
	}

	var contentTypeQ string
	if o.ContentType != nil {
		contentTypeQ = *o.ContentType
	}
	if contentTypeQ != "" {
		qs.Set("content_type", contentTypeQ)
	}

	var creationTimeQ string
	if o.CreationTime != nil {
		creationTimeQ = *o.CreationTime
	}
	if creationTimeQ != "" {
		qs.Set("creation_time", creationTimeQ)
	}

	var descriptionQ string
	if o.Description != nil {
		descriptionQ = *o.Description
	}
	if descriptionQ != "" {
		qs.Set("description", descriptionQ)
	}

	var endTimeQ string
	if o.EndTime != nil {
		endTimeQ = *o.EndTime
	}
	if endTimeQ != "" {
		qs.Set("end_time", endTimeQ)
	}

	var expiryTimeQ string
	if o.ExpiryTime != nil {
		expiryTimeQ = *o.ExpiryTime
	}
	if expiryTimeQ != "" {
		qs.Set("expiry_time", expiryTimeQ)
	}

	var fieldsIR []string
	for _, fieldsI := range o.Fields {
		fieldsIS := fieldsI
		if fieldsIS != "" {
			fieldsIR = append(fieldsIR, fieldsIS)
		}
	}

	fields := swag.JoinByFormat(fieldsIR, "csv")

	if len(fields) > 0 {
		qsv := fields[0]
		if qsv != "" {
			qs.Set("fields", qsv)
		}
	}

	var lastStateChangeTimeQ string
	if o.LastStateChangeTime != nil {
		lastStateChangeTimeQ = *o.LastStateChangeTime
	}
	if lastStateChangeTimeQ != "" {
		qs.Set("last_state_change_time", lastStateChangeTimeQ)
	}

	var maxRecordsQ string
	if o.MaxRecords != nil {
		maxRecordsQ = swag.FormatInt64(*o.MaxRecords)
	}
	if maxRecordsQ != "" {
		qs.Set("max_records", maxRecordsQ)
	}

	var orderByIR []string
	for _, orderByI := range o.OrderBy {
		orderByIS := orderByI
		if orderByIS != "" {
			orderByIR = append(orderByIR, orderByIS)
		}
	}

	orderBy := swag.JoinByFormat(orderByIR, "csv")

	if len(orderBy) > 0 {
		qsv := orderBy[0]
		if qsv != "" {
			qs.Set("order_by", qsv)
		}
	}

	var packageIDQ string
	if o.PackageID != nil {
		packageIDQ = *o.PackageID
	}
	if packageIDQ != "" {
		qs.Set("package_id", packageIDQ)
	}

	var percentCompleteQ string
	if o.PercentComplete != nil {
		percentCompleteQ = swag.FormatInt64(*o.PercentComplete)
	}
	if percentCompleteQ != "" {
		qs.Set("percent_complete", percentCompleteQ)
	}

	var remainingTimeQ string
	if o.RemainingTime != nil {
		remainingTimeQ = *o.RemainingTime
	}
	if remainingTimeQ != "" {
		qs.Set("remaining_time", remainingTimeQ)
	}

	var returnRecordsQ string
	if o.ReturnRecords != nil {
		returnRecordsQ = swag.FormatBool(*o.ReturnRecords)
	}
	if returnRecordsQ != "" {
		qs.Set("return_records", returnRecordsQ)
	}

	var returnTimeoutQ string
	if o.ReturnTimeout != nil {
		returnTimeoutQ = swag.FormatInt64(*o.ReturnTimeout)
	}
	if returnTimeoutQ != "" {
		qs.Set("return_timeout", returnTimeoutQ)
	}

	var scheduledTimeQ string
	if o.ScheduledTime != nil {
		scheduledTimeQ = *o.ScheduledTime
	}
	if scheduledTimeQ != "" {
		qs.Set("scheduled_time", scheduledTimeQ)
	}

	var startTimeQ string
	if o.StartTime != nil {
		startTimeQ = *o.StartTime
	}
	if startTimeQ != "" {
		qs.Set("start_time", startTimeQ)
	}

	var stateQ string
	if o.State != nil {
		stateQ = *o.State
	}
	if stateQ != "" {
		qs.Set("state", stateQ)
	}

	var statusArgumentsCodeQ string
	if o.StatusArgumentsCode != nil {
		statusArgumentsCodeQ = *o.StatusArgumentsCode
	}
	if statusArgumentsCodeQ != "" {
		qs.Set("status.arguments.code", statusArgumentsCodeQ)
	}

	var statusArgumentsMessageQ string
	if o.StatusArgumentsMessage != nil {
		statusArgumentsMessageQ = *o.StatusArgumentsMessage
	}
	if statusArgumentsMessageQ != "" {
		qs.Set("status.arguments.message", statusArgumentsMessageQ)
	}

	var statusCodeQ string
	if o.StatusCode != nil {
		statusCodeQ = *o.StatusCode
	}
	if statusCodeQ != "" {
		qs.Set("status.code", statusCodeQ)
	}

	var statusMessageQ string
	if o.StatusMessage != nil {
		statusMessageQ = *o.StatusMessage
	}
	if statusMessageQ != "" {
		qs.Set("status.message", statusMessageQ)
	}

	var uuidQ string
	if o.UUID != nil {
		uuidQ = *o.UUID
	}
	if uuidQ != "" {
		qs.Set("uuid", uuidQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *AutoUpdateStatusCollectionGetURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *AutoUpdateStatusCollectionGetURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *AutoUpdateStatusCollectionGetURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on AutoUpdateStatusCollectionGetURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on AutoUpdateStatusCollectionGetURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *AutoUpdateStatusCollectionGetURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
