// Code generated by go-swagger; DO NOT EDIT.

package support

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ConfigurationBackupGetHandlerFunc turns a function with the right signature into a configuration backup get handler
type ConfigurationBackupGetHandlerFunc func(ConfigurationBackupGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ConfigurationBackupGetHandlerFunc) Handle(params ConfigurationBackupGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ConfigurationBackupGetHandler interface for that can handle valid configuration backup get params
type ConfigurationBackupGetHandler interface {
	Handle(ConfigurationBackupGetParams, interface{}) middleware.Responder
}

// NewConfigurationBackupGet creates a new http.Handler for the configuration backup get operation
func NewConfigurationBackupGet(ctx *middleware.Context, handler ConfigurationBackupGetHandler) *ConfigurationBackupGet {
	return &ConfigurationBackupGet{Context: ctx, Handler: handler}
}

/*
	ConfigurationBackupGet swagger:route GET /support/configuration-backup Support configurationBackupGet

Retrieves the cluster configuration backup information.
*/
type ConfigurationBackupGet struct {
	Context *middleware.Context
	Handler ConfigurationBackupGetHandler
}

func (o *ConfigurationBackupGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewConfigurationBackupGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
