// Code generated by go-swagger; DO NOT EDIT.

package support

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// EmsFilterRuleModifyURL generates an URL for the ems filter rule modify operation
type EmsFilterRuleModifyURL struct {
	Index string
	Name  string

	NewIndex *int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *EmsFilterRuleModifyURL) WithBasePath(bp string) *EmsFilterRuleModifyURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *EmsFilterRuleModifyURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *EmsFilterRuleModifyURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/support/ems/filters/{name}/rules/{index}"

	index := o.Index
	if index != "" {
		_path = strings.Replace(_path, "{index}", index, -1)
	} else {
		return nil, errors.New("index is required on EmsFilterRuleModifyURL")
	}

	name := o.Name
	if name != "" {
		_path = strings.Replace(_path, "{name}", name, -1)
	} else {
		return nil, errors.New("name is required on EmsFilterRuleModifyURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var newIndexQ string
	if o.NewIndex != nil {
		newIndexQ = swag.FormatInt64(*o.NewIndex)
	}
	if newIndexQ != "" {
		qs.Set("new_index", newIndexQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *EmsFilterRuleModifyURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *EmsFilterRuleModifyURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *EmsFilterRuleModifyURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on EmsFilterRuleModifyURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on EmsFilterRuleModifyURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *EmsFilterRuleModifyURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
