// Code generated by go-swagger; DO NOT EDIT.

package support

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// SnmpUsersCollectionGetURL generates an URL for the snmp users collection get operation
type SnmpUsersCollectionGetURL struct {
	AuthenticationMethod         *string
	Comment                      *string
	EngineID                     *string
	Fields                       []string
	MaxRecords                   *int64
	Name                         *string
	OrderBy                      []string
	OwnerName                    *string
	OwnerUUID                    *string
	ReturnRecords                *bool
	ReturnTimeout                *int64
	Scope                        *string
	Snmpv3AuthenticationProtocol *string
	Snmpv3PrivacyProtocol        *string
	SwitchAddress                *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SnmpUsersCollectionGetURL) WithBasePath(bp string) *SnmpUsersCollectionGetURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SnmpUsersCollectionGetURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *SnmpUsersCollectionGetURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/support/snmp/users"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var authenticationMethodQ string
	if o.AuthenticationMethod != nil {
		authenticationMethodQ = *o.AuthenticationMethod
	}
	if authenticationMethodQ != "" {
		qs.Set("authentication_method", authenticationMethodQ)
	}

	var commentQ string
	if o.Comment != nil {
		commentQ = *o.Comment
	}
	if commentQ != "" {
		qs.Set("comment", commentQ)
	}

	var engineIDQ string
	if o.EngineID != nil {
		engineIDQ = *o.EngineID
	}
	if engineIDQ != "" {
		qs.Set("engine_id", engineIDQ)
	}

	var fieldsIR []string
	for _, fieldsI := range o.Fields {
		fieldsIS := fieldsI
		if fieldsIS != "" {
			fieldsIR = append(fieldsIR, fieldsIS)
		}
	}

	fields := swag.JoinByFormat(fieldsIR, "csv")

	if len(fields) > 0 {
		qsv := fields[0]
		if qsv != "" {
			qs.Set("fields", qsv)
		}
	}

	var maxRecordsQ string
	if o.MaxRecords != nil {
		maxRecordsQ = swag.FormatInt64(*o.MaxRecords)
	}
	if maxRecordsQ != "" {
		qs.Set("max_records", maxRecordsQ)
	}

	var nameQ string
	if o.Name != nil {
		nameQ = *o.Name
	}
	if nameQ != "" {
		qs.Set("name", nameQ)
	}

	var orderByIR []string
	for _, orderByI := range o.OrderBy {
		orderByIS := orderByI
		if orderByIS != "" {
			orderByIR = append(orderByIR, orderByIS)
		}
	}

	orderBy := swag.JoinByFormat(orderByIR, "csv")

	if len(orderBy) > 0 {
		qsv := orderBy[0]
		if qsv != "" {
			qs.Set("order_by", qsv)
		}
	}

	var ownerNameQ string
	if o.OwnerName != nil {
		ownerNameQ = *o.OwnerName
	}
	if ownerNameQ != "" {
		qs.Set("owner.name", ownerNameQ)
	}

	var ownerUUIDQ string
	if o.OwnerUUID != nil {
		ownerUUIDQ = *o.OwnerUUID
	}
	if ownerUUIDQ != "" {
		qs.Set("owner.uuid", ownerUUIDQ)
	}

	var returnRecordsQ string
	if o.ReturnRecords != nil {
		returnRecordsQ = swag.FormatBool(*o.ReturnRecords)
	}
	if returnRecordsQ != "" {
		qs.Set("return_records", returnRecordsQ)
	}

	var returnTimeoutQ string
	if o.ReturnTimeout != nil {
		returnTimeoutQ = swag.FormatInt64(*o.ReturnTimeout)
	}
	if returnTimeoutQ != "" {
		qs.Set("return_timeout", returnTimeoutQ)
	}

	var scopeQ string
	if o.Scope != nil {
		scopeQ = *o.Scope
	}
	if scopeQ != "" {
		qs.Set("scope", scopeQ)
	}

	var snmpv3AuthenticationProtocolQ string
	if o.Snmpv3AuthenticationProtocol != nil {
		snmpv3AuthenticationProtocolQ = *o.Snmpv3AuthenticationProtocol
	}
	if snmpv3AuthenticationProtocolQ != "" {
		qs.Set("snmpv3.authentication_protocol", snmpv3AuthenticationProtocolQ)
	}

	var snmpv3PrivacyProtocolQ string
	if o.Snmpv3PrivacyProtocol != nil {
		snmpv3PrivacyProtocolQ = *o.Snmpv3PrivacyProtocol
	}
	if snmpv3PrivacyProtocolQ != "" {
		qs.Set("snmpv3.privacy_protocol", snmpv3PrivacyProtocolQ)
	}

	var switchAddressQ string
	if o.SwitchAddress != nil {
		switchAddressQ = *o.SwitchAddress
	}
	if switchAddressQ != "" {
		qs.Set("switch_address", switchAddressQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *SnmpUsersCollectionGetURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *SnmpUsersCollectionGetURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *SnmpUsersCollectionGetURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on SnmpUsersCollectionGetURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on SnmpUsersCollectionGetURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *SnmpUsersCollectionGetURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
