// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// FabricCollectionGetURL generates an URL for the fabric collection get operation
type FabricCollectionGetURL struct {
	CacheAge                       *string
	CacheIsCurrent                 *bool
	CacheMaximumAge                *string
	CacheUpdateTime                *string
	ConnectionsClusterPortName     *string
	ConnectionsClusterPortNodeName *string
	ConnectionsClusterPortUUID     *string
	ConnectionsClusterPortWwpn     *string
	ConnectionsSwitchPortWwpn      *string
	ConnectionsSwitchWwn           *string
	Fields                         []string
	MaxRecords                     *int64
	Name                           *string
	OrderBy                        []string
	ReturnRecords                  *bool
	ReturnTimeout                  *int64
	ZonesetName                    *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *FabricCollectionGetURL) WithBasePath(bp string) *FabricCollectionGetURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *FabricCollectionGetURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *FabricCollectionGetURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/network/fc/fabrics"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var cacheAgeQ string
	if o.CacheAge != nil {
		cacheAgeQ = *o.CacheAge
	}
	if cacheAgeQ != "" {
		qs.Set("cache.age", cacheAgeQ)
	}

	var cacheIsCurrentQ string
	if o.CacheIsCurrent != nil {
		cacheIsCurrentQ = swag.FormatBool(*o.CacheIsCurrent)
	}
	if cacheIsCurrentQ != "" {
		qs.Set("cache.is_current", cacheIsCurrentQ)
	}

	var cacheMaximumAgeQ string
	if o.CacheMaximumAge != nil {
		cacheMaximumAgeQ = *o.CacheMaximumAge
	}
	if cacheMaximumAgeQ != "" {
		qs.Set("cache.maximum_age", cacheMaximumAgeQ)
	}

	var cacheUpdateTimeQ string
	if o.CacheUpdateTime != nil {
		cacheUpdateTimeQ = *o.CacheUpdateTime
	}
	if cacheUpdateTimeQ != "" {
		qs.Set("cache.update_time", cacheUpdateTimeQ)
	}

	var connectionsClusterPortNameQ string
	if o.ConnectionsClusterPortName != nil {
		connectionsClusterPortNameQ = *o.ConnectionsClusterPortName
	}
	if connectionsClusterPortNameQ != "" {
		qs.Set("connections.cluster_port.name", connectionsClusterPortNameQ)
	}

	var connectionsClusterPortNodeNameQ string
	if o.ConnectionsClusterPortNodeName != nil {
		connectionsClusterPortNodeNameQ = *o.ConnectionsClusterPortNodeName
	}
	if connectionsClusterPortNodeNameQ != "" {
		qs.Set("connections.cluster_port.node.name", connectionsClusterPortNodeNameQ)
	}

	var connectionsClusterPortUUIDQ string
	if o.ConnectionsClusterPortUUID != nil {
		connectionsClusterPortUUIDQ = *o.ConnectionsClusterPortUUID
	}
	if connectionsClusterPortUUIDQ != "" {
		qs.Set("connections.cluster_port.uuid", connectionsClusterPortUUIDQ)
	}

	var connectionsClusterPortWwpnQ string
	if o.ConnectionsClusterPortWwpn != nil {
		connectionsClusterPortWwpnQ = *o.ConnectionsClusterPortWwpn
	}
	if connectionsClusterPortWwpnQ != "" {
		qs.Set("connections.cluster_port.wwpn", connectionsClusterPortWwpnQ)
	}

	var connectionsSwitchPortWwpnQ string
	if o.ConnectionsSwitchPortWwpn != nil {
		connectionsSwitchPortWwpnQ = *o.ConnectionsSwitchPortWwpn
	}
	if connectionsSwitchPortWwpnQ != "" {
		qs.Set("connections.switch.port.wwpn", connectionsSwitchPortWwpnQ)
	}

	var connectionsSwitchWwnQ string
	if o.ConnectionsSwitchWwn != nil {
		connectionsSwitchWwnQ = *o.ConnectionsSwitchWwn
	}
	if connectionsSwitchWwnQ != "" {
		qs.Set("connections.switch.wwn", connectionsSwitchWwnQ)
	}

	var fieldsIR []string
	for _, fieldsI := range o.Fields {
		fieldsIS := fieldsI
		if fieldsIS != "" {
			fieldsIR = append(fieldsIR, fieldsIS)
		}
	}

	fields := swag.JoinByFormat(fieldsIR, "csv")

	if len(fields) > 0 {
		qsv := fields[0]
		if qsv != "" {
			qs.Set("fields", qsv)
		}
	}

	var maxRecordsQ string
	if o.MaxRecords != nil {
		maxRecordsQ = swag.FormatInt64(*o.MaxRecords)
	}
	if maxRecordsQ != "" {
		qs.Set("max_records", maxRecordsQ)
	}

	var nameQ string
	if o.Name != nil {
		nameQ = *o.Name
	}
	if nameQ != "" {
		qs.Set("name", nameQ)
	}

	var orderByIR []string
	for _, orderByI := range o.OrderBy {
		orderByIS := orderByI
		if orderByIS != "" {
			orderByIR = append(orderByIR, orderByIS)
		}
	}

	orderBy := swag.JoinByFormat(orderByIR, "csv")

	if len(orderBy) > 0 {
		qsv := orderBy[0]
		if qsv != "" {
			qs.Set("order_by", qsv)
		}
	}

	var returnRecordsQ string
	if o.ReturnRecords != nil {
		returnRecordsQ = swag.FormatBool(*o.ReturnRecords)
	}
	if returnRecordsQ != "" {
		qs.Set("return_records", returnRecordsQ)
	}

	var returnTimeoutQ string
	if o.ReturnTimeout != nil {
		returnTimeoutQ = swag.FormatInt64(*o.ReturnTimeout)
	}
	if returnTimeoutQ != "" {
		qs.Set("return_timeout", returnTimeoutQ)
	}

	var zonesetNameQ string
	if o.ZonesetName != nil {
		zonesetNameQ = *o.ZonesetName
	}
	if zonesetNameQ != "" {
		qs.Set("zoneset.name", zonesetNameQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *FabricCollectionGetURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *FabricCollectionGetURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *FabricCollectionGetURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on FabricCollectionGetURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on FabricCollectionGetURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *FabricCollectionGetURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
