// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFcSwitchGetParams creates a new FcSwitchGetParams object
// with the default values initialized.
func NewFcSwitchGetParams() FcSwitchGetParams {

	var (
		// initialize parameters with default values

		cacheMaximumAgeDefault = string("15 minutes")
	)

	return FcSwitchGetParams{
		CacheMaximumAge: &cacheMaximumAgeDefault,
	}
}

// FcSwitchGetParams contains all the bound params for the fc switch get operation
// typically these are obtained from a http.Request
//
// swagger:parameters fc_switch_get
type FcSwitchGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The maximum age of data in the Fibre Channel fabric cache before it should be refreshed from the fabric. The default is 15 minutes.
	  In: query
	  Default: "15 minutes"
	*/
	CacheMaximumAge *string
	/*The WWN of the primary switch of the Fibre Channel fabric.

	  Required: true
	  In: path
	*/
	FabricName string
	/*Specify the fields to return.
	  In: query
	  Collection Format: csv
	*/
	Fields []string
	/*The WWN of the Fibre Channel switch.

	  Required: true
	  In: path
	*/
	Wwn string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewFcSwitchGetParams() beforehand.
func (o *FcSwitchGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qCacheMaximumAge, qhkCacheMaximumAge, _ := qs.GetOK("cache.maximum_age")
	if err := o.bindCacheMaximumAge(qCacheMaximumAge, qhkCacheMaximumAge, route.Formats); err != nil {
		res = append(res, err)
	}

	rFabricName, rhkFabricName, _ := route.Params.GetOK("fabric.name")
	if err := o.bindFabricName(rFabricName, rhkFabricName, route.Formats); err != nil {
		res = append(res, err)
	}

	qFields, qhkFields, _ := qs.GetOK("fields")
	if err := o.bindFields(qFields, qhkFields, route.Formats); err != nil {
		res = append(res, err)
	}

	rWwn, rhkWwn, _ := route.Params.GetOK("wwn")
	if err := o.bindWwn(rWwn, rhkWwn, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCacheMaximumAge binds and validates parameter CacheMaximumAge from query.
func (o *FcSwitchGetParams) bindCacheMaximumAge(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewFcSwitchGetParams()
		return nil
	}
	o.CacheMaximumAge = &raw

	return nil
}

// bindFabricName binds and validates parameter FabricName from path.
func (o *FcSwitchGetParams) bindFabricName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.FabricName = raw

	return nil
}

// bindFields binds and validates array parameter Fields from query.
//
// Arrays are parsed according to CollectionFormat: "csv" (defaults to "csv" when empty).
func (o *FcSwitchGetParams) bindFields(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var qvFields string
	if len(rawData) > 0 {
		qvFields = rawData[len(rawData)-1]
	}

	// CollectionFormat: csv
	fieldsIC := swag.SplitByFormat(qvFields, "csv")
	if len(fieldsIC) == 0 {
		return nil
	}

	var fieldsIR []string
	for _, fieldsIV := range fieldsIC {
		fieldsI := fieldsIV

		fieldsIR = append(fieldsIR, fieldsI)
	}

	o.Fields = fieldsIR

	return nil
}

// bindWwn binds and validates parameter Wwn from path.
func (o *FcSwitchGetParams) bindWwn(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Wwn = raw

	return nil
}
