// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FcSwitchGetHandlerFunc turns a function with the right signature into a fc switch get handler
type FcSwitchGetHandlerFunc func(FcSwitchGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn FcSwitchGetHandlerFunc) Handle(params FcSwitchGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// FcSwitchGetHandler interface for that can handle valid fc switch get params
type FcSwitchGetHandler interface {
	Handle(FcSwitchGetParams, interface{}) middleware.Responder
}

// NewFcSwitchGet creates a new http.Handler for the fc switch get operation
func NewFcSwitchGet(ctx *middleware.Context, handler FcSwitchGetHandler) *FcSwitchGet {
	return &FcSwitchGet{Context: ctx, Handler: handler}
}

/*
	FcSwitchGet swagger:route GET /network/fc/fabrics/{fabric.name}/switches/{wwn} Networking fcSwitchGet

Retrieves a Fibre Channel switch.
### Expensive properties
There is an added computational cost to retrieving values for these properties. They are not included by default in GET results and must be explicitly requested using the `fields` query parameter. See [`Requesting specific fields`](#Requesting_specific_fields) to learn more.
* `ports`
### Related ONTAP commands
* `network fcp topology show`
### Learn more
* [`DOC /network/fc/fabrics`](#docs-networking-network_fc_fabrics)
*/
type FcSwitchGet struct {
	Context *middleware.Context
	Handler FcSwitchGetHandler
}

func (o *FcSwitchGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFcSwitchGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
