// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// IPServicePolicyCreateHandlerFunc turns a function with the right signature into a ip service policy create handler
type IPServicePolicyCreateHandlerFunc func(IPServicePolicyCreateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn IPServicePolicyCreateHandlerFunc) Handle(params IPServicePolicyCreateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// IPServicePolicyCreateHandler interface for that can handle valid ip service policy create params
type IPServicePolicyCreateHandler interface {
	Handle(IPServicePolicyCreateParams, interface{}) middleware.Responder
}

// NewIPServicePolicyCreate creates a new http.Handler for the ip service policy create operation
func NewIPServicePolicyCreate(ctx *middleware.Context, handler IPServicePolicyCreateHandler) *IPServicePolicyCreate {
	return &IPServicePolicyCreate{Context: ctx, Handler: handler}
}

/*
	IPServicePolicyCreate swagger:route POST /network/ip/service-policies Networking ipServicePolicyCreate

Creates a service policy for network interfaces.
### Related ONTAP commands
* `network interface service-policy create`
### Required properties
* `name` - Name of the service policy to create.
* `ipspace.name` or `ipspace.uuid`
  - Required for cluster-scoped service policies.
  - Optional for SVM-scoped service policies.

* `svm.name` or `svm.uuid`
  - Required for SVM-scoped service policies.
  - Not valid for cluster-scoped service policies.

### Default property values
If not specified in POST, the following default property values are assigned:
* `scope`
  - svm if the svm parameter is specified
  - cluster if the svm parameter is not specified
*/
type IPServicePolicyCreate struct {
	Context *middleware.Context
	Handler IPServicePolicyCreateHandler
}

func (o *IPServicePolicyCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewIPServicePolicyCreateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
