// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// NewIPServicePolicyModifyParams creates a new IPServicePolicyModifyParams object
//
// There are no default values defined in the spec.
func NewIPServicePolicyModifyParams() IPServicePolicyModifyParams {

	return IPServicePolicyModifyParams{}
}

// IPServicePolicyModifyParams contains all the bound params for the ip service policy modify operation
// typically these are obtained from a http.Request
//
// swagger:parameters ip_service_policy_modify
type IPServicePolicyModifyParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*policy parameters
	  Required: true
	  In: body
	*/
	Info *models.IPServicePolicy
	/*UUID of the service policy
	  Required: true
	  In: path
	*/
	UUID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewIPServicePolicyModifyParams() beforehand.
func (o *IPServicePolicyModifyParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.IPServicePolicy
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("info", "body", ""))
			} else {
				res = append(res, errors.NewParseError("info", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Info = &body
			}
		}
	} else {
		res = append(res, errors.Required("info", "body", ""))
	}

	rUUID, rhkUUID, _ := route.Params.GetOK("uuid")
	if err := o.bindUUID(rUUID, rhkUUID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindUUID binds and validates parameter UUID from path.
func (o *IPServicePolicyModifyParams) bindUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.UUID = raw

	return nil
}
