// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// IPSubnetModifyOKCode is the HTTP code returned for type IPSubnetModifyOK
const IPSubnetModifyOKCode int = 200

/*
IPSubnetModifyOK OK

swagger:response ipSubnetModifyOK
*/
type IPSubnetModifyOK struct {
}

// NewIPSubnetModifyOK creates IPSubnetModifyOK with default headers values
func NewIPSubnetModifyOK() *IPSubnetModifyOK {

	return &IPSubnetModifyOK{}
}

// WriteResponse to the client
func (o *IPSubnetModifyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
IPSubnetModifyDefault Fill error codes below.
ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 1377658 | Invalid gateway for subnet in IPspace. |
| 1377659 | Subnet would overlap with existing subnet named in IPspace. |
| 1377660 | A subnet with the name already exists in the IPspace. |
| 1377661 | Subnet in IPspace cannot use subnet address because that address is already used by subnet in the same IPspace. |
| 1377662 | The IP range address is not within the subnet in IPspace. |
| 1377663 | The specified IP address range of subnet in IPspace contains an address already in use by a LIF. |
| 1377664 | The specified IP address range of subnet in IPspace contains an address already in use by the Service Processor. |
| 1377669 | The specified gateway address exists in a configured range. |
| 1377673 | The addresses provided must have the same address family. |
| 1377674 | Modifying the netmask is not supported because the subnet has one or more interfaces associated with it. |
| 1377675 | The netmask of the interface did not match the netmask of the subnet. |
| 1377681 | Cannot update LIF associations for LIF. The broadcast domain of the LIF does not match the broadcast domain of the subnet. |
| 1966269 | IPv4 Addresses must have a prefix length between 1 and 32. |
| 1966778 | IPv6 addresses must have a prefix length between 1 and 127. |
| 53282568 | The subnet.address must be specified together with subnet.netmask. |
| 53282569 | The specified subnet.netmask is not valid. |
| 53282570 | Each pair of ranges must have ip_ranges.start less than or equal to ip_ranges.end. |
| 53282571 | The ip_ranges.start and ip_ranges.end fields must have the same number of items. |
| 53282572 | PATCH partially succeeded with error. |
Also see the table of common errors in the <a href="#Response_body">Response body</a> overview section of this documentation.

swagger:response ipSubnetModifyDefault
*/
type IPSubnetModifyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewIPSubnetModifyDefault creates IPSubnetModifyDefault with default headers values
func NewIPSubnetModifyDefault(code int) *IPSubnetModifyDefault {
	if code <= 0 {
		code = 500
	}

	return &IPSubnetModifyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the ip subnet modify default response
func (o *IPSubnetModifyDefault) WithStatusCode(code int) *IPSubnetModifyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the ip subnet modify default response
func (o *IPSubnetModifyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the ip subnet modify default response
func (o *IPSubnetModifyDefault) WithPayload(payload *models.ErrorResponse) *IPSubnetModifyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the ip subnet modify default response
func (o *IPSubnetModifyDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IPSubnetModifyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
