// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// NetworkIPInterfaceDeleteOKCode is the HTTP code returned for type NetworkIPInterfaceDeleteOK
const NetworkIPInterfaceDeleteOKCode int = 200

/*
NetworkIPInterfaceDeleteOK OK

swagger:response networkIpInterfaceDeleteOK
*/
type NetworkIPInterfaceDeleteOK struct {
}

// NewNetworkIPInterfaceDeleteOK creates NetworkIPInterfaceDeleteOK with default headers values
func NewNetworkIPInterfaceDeleteOK() *NetworkIPInterfaceDeleteOK {

	return &NetworkIPInterfaceDeleteOK{}
}

// WriteResponse to the client
func (o *NetworkIPInterfaceDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
NetworkIPInterfaceDeleteDefault ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 1966465 | LIF cannot be removed because it is required to maintain quorum on the node. |
| 5376953 | The interface is part of one or more portsets. Remove the interface from all portsets before deleting it. |
| 53281112 | Failed to delete the interface because it has an associated BGP peer group. |
Also see the table of common errors in the <a href="#Response_body">Response body</a> overview section of this documentation.

swagger:response networkIpInterfaceDeleteDefault
*/
type NetworkIPInterfaceDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewNetworkIPInterfaceDeleteDefault creates NetworkIPInterfaceDeleteDefault with default headers values
func NewNetworkIPInterfaceDeleteDefault(code int) *NetworkIPInterfaceDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &NetworkIPInterfaceDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the network ip interface delete default response
func (o *NetworkIPInterfaceDeleteDefault) WithStatusCode(code int) *NetworkIPInterfaceDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the network ip interface delete default response
func (o *NetworkIPInterfaceDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the network ip interface delete default response
func (o *NetworkIPInterfaceDeleteDefault) WithPayload(payload *models.ErrorResponse) *NetworkIPInterfaceDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the network ip interface delete default response
func (o *NetworkIPInterfaceDeleteDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NetworkIPInterfaceDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
