// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// SwitchPortGetURL generates an URL for the switch port get operation
type SwitchPortGetURL struct {
	IdentityIndex int64
	IdentityName  string
	Switch        string

	Fields []string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SwitchPortGetURL) WithBasePath(bp string) *SwitchPortGetURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SwitchPortGetURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *SwitchPortGetURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/network/ethernet/switch/ports/{switch}/{identity.name}/{identity.index}"

	identityIndex := swag.FormatInt64(o.IdentityIndex)
	if identityIndex != "" {
		_path = strings.Replace(_path, "{identity.index}", identityIndex, -1)
	} else {
		return nil, errors.New("identityIndex is required on SwitchPortGetURL")
	}

	identityName := o.IdentityName
	if identityName != "" {
		_path = strings.Replace(_path, "{identity.name}", identityName, -1)
	} else {
		return nil, errors.New("identityName is required on SwitchPortGetURL")
	}

	switchVar := o.Switch
	if switchVar != "" {
		_path = strings.Replace(_path, "{switch}", switchVar, -1)
	} else {
		return nil, errors.New("switch is required on SwitchPortGetURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var fieldsIR []string
	for _, fieldsI := range o.Fields {
		fieldsIS := fieldsI
		if fieldsIS != "" {
			fieldsIR = append(fieldsIR, fieldsIS)
		}
	}

	fields := swag.JoinByFormat(fieldsIR, "csv")

	if len(fields) > 0 {
		qsv := fields[0]
		if qsv != "" {
			qs.Set("fields", qsv)
		}
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *SwitchPortGetURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *SwitchPortGetURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *SwitchPortGetURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on SwitchPortGetURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on SwitchPortGetURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *SwitchPortGetURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
