// Code generated by go-swagger; DO NOT EDIT.

package networking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewSwitchCollectionGetParams creates a new SwitchCollectionGetParams object
// with the default values initialized.
func NewSwitchCollectionGetParams() SwitchCollectionGetParams {

	var (
		// initialize parameters with default values

		returnRecordsDefault = bool(true)
		returnTimeoutDefault = int64(15)
	)

	return SwitchCollectionGetParams{
		ReturnRecords: &returnRecordsDefault,

		ReturnTimeout: &returnTimeoutDefault,
	}
}

// SwitchCollectionGetParams contains all the bound params for the switch collection get operation
// typically these are obtained from a http.Request
//
// swagger:parameters switch_collection_get
type SwitchCollectionGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Filter by address
	  In: query
	*/
	Address *string
	/*Filter by discovered
	  In: query
	*/
	Discovered *bool
	/*Specify the fields to return.
	  In: query
	  Collection Format: csv
	*/
	Fields []string
	/*Limit the number of records returned.
	  In: query
	*/
	MaxRecords *int64
	/*Filter by model
	  In: query
	*/
	Model *string
	/*Filter by monitoring.enabled
	  In: query
	*/
	MonitoringEnabled *bool
	/*Filter by monitoring.monitored
	  In: query
	*/
	MonitoringMonitored *bool
	/*Filter by monitoring.reason
	  In: query
	*/
	MonitoringReason *string
	/*Filter by name
	  In: query
	*/
	Name *string
	/*Filter by network
	  In: query
	*/
	Network *string
	/*Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.
	  In: query
	  Collection Format: csv
	*/
	OrderBy []string
	/*The default is true for GET calls.  When set to false, only the number of records is returned.
	  In: query
	  Default: true
	*/
	ReturnRecords *bool
	/*The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.
	  Maximum: 120
	  Minimum: 0
	  In: query
	  Default: 15
	*/
	ReturnTimeout *int64
	/*Filter by serial_number
	  In: query
	*/
	SerialNumber *string
	/*Filter by snmp.user
	  In: query
	*/
	SnmpUser *string
	/*Filter by snmp.version
	  In: query
	*/
	SnmpVersion *string
	/*Filter by version
	  In: query
	*/
	Version *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSwitchCollectionGetParams() beforehand.
func (o *SwitchCollectionGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qAddress, qhkAddress, _ := qs.GetOK("address")
	if err := o.bindAddress(qAddress, qhkAddress, route.Formats); err != nil {
		res = append(res, err)
	}

	qDiscovered, qhkDiscovered, _ := qs.GetOK("discovered")
	if err := o.bindDiscovered(qDiscovered, qhkDiscovered, route.Formats); err != nil {
		res = append(res, err)
	}

	qFields, qhkFields, _ := qs.GetOK("fields")
	if err := o.bindFields(qFields, qhkFields, route.Formats); err != nil {
		res = append(res, err)
	}

	qMaxRecords, qhkMaxRecords, _ := qs.GetOK("max_records")
	if err := o.bindMaxRecords(qMaxRecords, qhkMaxRecords, route.Formats); err != nil {
		res = append(res, err)
	}

	qModel, qhkModel, _ := qs.GetOK("model")
	if err := o.bindModel(qModel, qhkModel, route.Formats); err != nil {
		res = append(res, err)
	}

	qMonitoringEnabled, qhkMonitoringEnabled, _ := qs.GetOK("monitoring.enabled")
	if err := o.bindMonitoringEnabled(qMonitoringEnabled, qhkMonitoringEnabled, route.Formats); err != nil {
		res = append(res, err)
	}

	qMonitoringMonitored, qhkMonitoringMonitored, _ := qs.GetOK("monitoring.monitored")
	if err := o.bindMonitoringMonitored(qMonitoringMonitored, qhkMonitoringMonitored, route.Formats); err != nil {
		res = append(res, err)
	}

	qMonitoringReason, qhkMonitoringReason, _ := qs.GetOK("monitoring.reason")
	if err := o.bindMonitoringReason(qMonitoringReason, qhkMonitoringReason, route.Formats); err != nil {
		res = append(res, err)
	}

	qName, qhkName, _ := qs.GetOK("name")
	if err := o.bindName(qName, qhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	qNetwork, qhkNetwork, _ := qs.GetOK("network")
	if err := o.bindNetwork(qNetwork, qhkNetwork, route.Formats); err != nil {
		res = append(res, err)
	}

	qOrderBy, qhkOrderBy, _ := qs.GetOK("order_by")
	if err := o.bindOrderBy(qOrderBy, qhkOrderBy, route.Formats); err != nil {
		res = append(res, err)
	}

	qReturnRecords, qhkReturnRecords, _ := qs.GetOK("return_records")
	if err := o.bindReturnRecords(qReturnRecords, qhkReturnRecords, route.Formats); err != nil {
		res = append(res, err)
	}

	qReturnTimeout, qhkReturnTimeout, _ := qs.GetOK("return_timeout")
	if err := o.bindReturnTimeout(qReturnTimeout, qhkReturnTimeout, route.Formats); err != nil {
		res = append(res, err)
	}

	qSerialNumber, qhkSerialNumber, _ := qs.GetOK("serial_number")
	if err := o.bindSerialNumber(qSerialNumber, qhkSerialNumber, route.Formats); err != nil {
		res = append(res, err)
	}

	qSnmpUser, qhkSnmpUser, _ := qs.GetOK("snmp.user")
	if err := o.bindSnmpUser(qSnmpUser, qhkSnmpUser, route.Formats); err != nil {
		res = append(res, err)
	}

	qSnmpVersion, qhkSnmpVersion, _ := qs.GetOK("snmp.version")
	if err := o.bindSnmpVersion(qSnmpVersion, qhkSnmpVersion, route.Formats); err != nil {
		res = append(res, err)
	}

	qVersion, qhkVersion, _ := qs.GetOK("version")
	if err := o.bindVersion(qVersion, qhkVersion, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAddress binds and validates parameter Address from query.
func (o *SwitchCollectionGetParams) bindAddress(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Address = &raw

	return nil
}

// bindDiscovered binds and validates parameter Discovered from query.
func (o *SwitchCollectionGetParams) bindDiscovered(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("discovered", "query", "bool", raw)
	}
	o.Discovered = &value

	return nil
}

// bindFields binds and validates array parameter Fields from query.
//
// Arrays are parsed according to CollectionFormat: "csv" (defaults to "csv" when empty).
func (o *SwitchCollectionGetParams) bindFields(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var qvFields string
	if len(rawData) > 0 {
		qvFields = rawData[len(rawData)-1]
	}

	// CollectionFormat: csv
	fieldsIC := swag.SplitByFormat(qvFields, "csv")
	if len(fieldsIC) == 0 {
		return nil
	}

	var fieldsIR []string
	for _, fieldsIV := range fieldsIC {
		fieldsI := fieldsIV

		fieldsIR = append(fieldsIR, fieldsI)
	}

	o.Fields = fieldsIR

	return nil
}

// bindMaxRecords binds and validates parameter MaxRecords from query.
func (o *SwitchCollectionGetParams) bindMaxRecords(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("max_records", "query", "int64", raw)
	}
	o.MaxRecords = &value

	return nil
}

// bindModel binds and validates parameter Model from query.
func (o *SwitchCollectionGetParams) bindModel(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Model = &raw

	return nil
}

// bindMonitoringEnabled binds and validates parameter MonitoringEnabled from query.
func (o *SwitchCollectionGetParams) bindMonitoringEnabled(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("monitoring.enabled", "query", "bool", raw)
	}
	o.MonitoringEnabled = &value

	return nil
}

// bindMonitoringMonitored binds and validates parameter MonitoringMonitored from query.
func (o *SwitchCollectionGetParams) bindMonitoringMonitored(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("monitoring.monitored", "query", "bool", raw)
	}
	o.MonitoringMonitored = &value

	return nil
}

// bindMonitoringReason binds and validates parameter MonitoringReason from query.
func (o *SwitchCollectionGetParams) bindMonitoringReason(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.MonitoringReason = &raw

	return nil
}

// bindName binds and validates parameter Name from query.
func (o *SwitchCollectionGetParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Name = &raw

	return nil
}

// bindNetwork binds and validates parameter Network from query.
func (o *SwitchCollectionGetParams) bindNetwork(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Network = &raw

	return nil
}

// bindOrderBy binds and validates array parameter OrderBy from query.
//
// Arrays are parsed according to CollectionFormat: "csv" (defaults to "csv" when empty).
func (o *SwitchCollectionGetParams) bindOrderBy(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var qvOrderBy string
	if len(rawData) > 0 {
		qvOrderBy = rawData[len(rawData)-1]
	}

	// CollectionFormat: csv
	orderByIC := swag.SplitByFormat(qvOrderBy, "csv")
	if len(orderByIC) == 0 {
		return nil
	}

	var orderByIR []string
	for _, orderByIV := range orderByIC {
		orderByI := orderByIV

		orderByIR = append(orderByIR, orderByI)
	}

	o.OrderBy = orderByIR

	return nil
}

// bindReturnRecords binds and validates parameter ReturnRecords from query.
func (o *SwitchCollectionGetParams) bindReturnRecords(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewSwitchCollectionGetParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("return_records", "query", "bool", raw)
	}
	o.ReturnRecords = &value

	return nil
}

// bindReturnTimeout binds and validates parameter ReturnTimeout from query.
func (o *SwitchCollectionGetParams) bindReturnTimeout(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewSwitchCollectionGetParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("return_timeout", "query", "int64", raw)
	}
	o.ReturnTimeout = &value

	if err := o.validateReturnTimeout(formats); err != nil {
		return err
	}

	return nil
}

// validateReturnTimeout carries on validations for parameter ReturnTimeout
func (o *SwitchCollectionGetParams) validateReturnTimeout(formats strfmt.Registry) error {

	if err := validate.MinimumInt("return_timeout", "query", *o.ReturnTimeout, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("return_timeout", "query", *o.ReturnTimeout, 120, false); err != nil {
		return err
	}

	return nil
}

// bindSerialNumber binds and validates parameter SerialNumber from query.
func (o *SwitchCollectionGetParams) bindSerialNumber(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.SerialNumber = &raw

	return nil
}

// bindSnmpUser binds and validates parameter SnmpUser from query.
func (o *SwitchCollectionGetParams) bindSnmpUser(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.SnmpUser = &raw

	return nil
}

// bindSnmpVersion binds and validates parameter SnmpVersion from query.
func (o *SwitchCollectionGetParams) bindSnmpVersion(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.SnmpVersion = &raw

	return nil
}

// bindVersion binds and validates parameter Version from query.
func (o *SwitchCollectionGetParams) bindVersion(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Version = &raw

	return nil
}
