// Code generated by go-swagger; DO NOT EDIT.

package snap_lock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SnaplockLogCollectionGetHandlerFunc turns a function with the right signature into a snaplock log collection get handler
type SnaplockLogCollectionGetHandlerFunc func(SnaplockLogCollectionGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SnaplockLogCollectionGetHandlerFunc) Handle(params SnaplockLogCollectionGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SnaplockLogCollectionGetHandler interface for that can handle valid snaplock log collection get params
type SnaplockLogCollectionGetHandler interface {
	Handle(SnaplockLogCollectionGetParams, interface{}) middleware.Responder
}

// NewSnaplockLogCollectionGet creates a new http.Handler for the snaplock log collection get operation
func NewSnaplockLogCollectionGet(ctx *middleware.Context, handler SnaplockLogCollectionGetHandler) *SnaplockLogCollectionGet {
	return &SnaplockLogCollectionGet{Context: ctx, Handler: handler}
}

/*
	SnaplockLogCollectionGet swagger:route GET /storage/snaplock/audit-logs SnapLock snaplockLogCollectionGet

Retrieves a list of SVMs configured with audit log volumes.
### Related ONTAP commands
* `snaplock log show`
### Learn more
* [`DOC /storage/snaplock/audit-logs`](#docs-snaplock-storage_snaplock_audit-logs)
*/
type SnaplockLogCollectionGet struct {
	Context *middleware.Context
	Handler SnaplockLogCollectionGetHandler
}

func (o *SnaplockLogCollectionGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSnaplockLogCollectionGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
