// Code generated by go-swagger; DO NOT EDIT.

package snap_lock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// SnaplockRetentionPolicyModifyOKCode is the HTTP code returned for type SnaplockRetentionPolicyModifyOK
const SnaplockRetentionPolicyModifyOKCode int = 200

/*
SnaplockRetentionPolicyModifyOK OK

swagger:response snaplockRetentionPolicyModifyOK
*/
type SnaplockRetentionPolicyModifyOK struct {
}

// NewSnaplockRetentionPolicyModifyOK creates SnaplockRetentionPolicyModifyOK with default headers values
func NewSnaplockRetentionPolicyModifyOK() *SnaplockRetentionPolicyModifyOK {

	return &SnaplockRetentionPolicyModifyOK{}
}

// WriteResponse to the client
func (o *SnaplockRetentionPolicyModifyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
SnaplockRetentionPolicyModifyDefault ONTAP Error Response codes
| Error code  |  Description |
|-------------|--------------|
|   918253    | Incorrect format for the retention period, duration must be in the ISO-8601 format or infinite or unspecified. |
| 13763280    | Only a user with security login role \"vsadmin-snaplock\" is allowed to perform this operation.  |

swagger:response snaplockRetentionPolicyModifyDefault
*/
type SnaplockRetentionPolicyModifyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSnaplockRetentionPolicyModifyDefault creates SnaplockRetentionPolicyModifyDefault with default headers values
func NewSnaplockRetentionPolicyModifyDefault(code int) *SnaplockRetentionPolicyModifyDefault {
	if code <= 0 {
		code = 500
	}

	return &SnaplockRetentionPolicyModifyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the snaplock retention policy modify default response
func (o *SnaplockRetentionPolicyModifyDefault) WithStatusCode(code int) *SnaplockRetentionPolicyModifyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the snaplock retention policy modify default response
func (o *SnaplockRetentionPolicyModifyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the snaplock retention policy modify default response
func (o *SnaplockRetentionPolicyModifyDefault) WithPayload(payload *models.ErrorResponse) *SnaplockRetentionPolicyModifyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the snaplock retention policy modify default response
func (o *SnaplockRetentionPolicyModifyDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SnaplockRetentionPolicyModifyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
