// Code generated by go-swagger; DO NOT EDIT.

package snap_lock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSnaplockFileRetentionGetParams creates a new SnaplockFileRetentionGetParams object
//
// There are no default values defined in the spec.
func NewSnaplockFileRetentionGetParams() SnaplockFileRetentionGetParams {

	return SnaplockFileRetentionGetParams{}
}

// SnaplockFileRetentionGetParams contains all the bound params for the snaplock file retention get operation
// typically these are obtained from a http.Request
//
// swagger:parameters snaplock_file_retention_get
type SnaplockFileRetentionGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Specify the fields to return.
	  In: query
	  Collection Format: csv
	*/
	Fields []string
	/*Path of the file in the form "/\<dirpath\>/\<filename\>"
	  Required: true
	  In: path
	*/
	Path string
	/*Volume UUID
	  Required: true
	  In: path
	*/
	VolumeUUID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSnaplockFileRetentionGetParams() beforehand.
func (o *SnaplockFileRetentionGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qFields, qhkFields, _ := qs.GetOK("fields")
	if err := o.bindFields(qFields, qhkFields, route.Formats); err != nil {
		res = append(res, err)
	}

	rPath, rhkPath, _ := route.Params.GetOK("path")
	if err := o.bindPath(rPath, rhkPath, route.Formats); err != nil {
		res = append(res, err)
	}

	rVolumeUUID, rhkVolumeUUID, _ := route.Params.GetOK("volume.uuid")
	if err := o.bindVolumeUUID(rVolumeUUID, rhkVolumeUUID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFields binds and validates array parameter Fields from query.
//
// Arrays are parsed according to CollectionFormat: "csv" (defaults to "csv" when empty).
func (o *SnaplockFileRetentionGetParams) bindFields(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var qvFields string
	if len(rawData) > 0 {
		qvFields = rawData[len(rawData)-1]
	}

	// CollectionFormat: csv
	fieldsIC := swag.SplitByFormat(qvFields, "csv")
	if len(fieldsIC) == 0 {
		return nil
	}

	var fieldsIR []string
	for _, fieldsIV := range fieldsIC {
		fieldsI := fieldsIV

		fieldsIR = append(fieldsIR, fieldsI)
	}

	o.Fields = fieldsIR

	return nil
}

// bindPath binds and validates parameter Path from path.
func (o *SnaplockFileRetentionGetParams) bindPath(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Path = raw

	return nil
}

// bindVolumeUUID binds and validates parameter VolumeUUID from path.
func (o *SnaplockFileRetentionGetParams) bindVolumeUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.VolumeUUID = raw

	return nil
}
