// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// CloudStoreModifyOKCode is the HTTP code returned for type CloudStoreModifyOK
const CloudStoreModifyOKCode int = 200

/*
CloudStoreModifyOK OK

swagger:response cloudStoreModifyOK
*/
type CloudStoreModifyOK struct {

	/*
	  In: Body
	*/
	Payload *models.JobLinkResponse `json:"body,omitempty"`
}

// NewCloudStoreModifyOK creates CloudStoreModifyOK with default headers values
func NewCloudStoreModifyOK() *CloudStoreModifyOK {

	return &CloudStoreModifyOK{}
}

// WithPayload adds the payload to the cloud store modify o k response
func (o *CloudStoreModifyOK) WithPayload(payload *models.JobLinkResponse) *CloudStoreModifyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cloud store modify o k response
func (o *CloudStoreModifyOK) SetPayload(payload *models.JobLinkResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CloudStoreModifyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CloudStoreModifyAcceptedCode is the HTTP code returned for type CloudStoreModifyAccepted
const CloudStoreModifyAcceptedCode int = 202

/*
CloudStoreModifyAccepted Accepted

swagger:response cloudStoreModifyAccepted
*/
type CloudStoreModifyAccepted struct {

	/*
	  In: Body
	*/
	Payload *models.JobLinkResponse `json:"body,omitempty"`
}

// NewCloudStoreModifyAccepted creates CloudStoreModifyAccepted with default headers values
func NewCloudStoreModifyAccepted() *CloudStoreModifyAccepted {

	return &CloudStoreModifyAccepted{}
}

// WithPayload adds the payload to the cloud store modify accepted response
func (o *CloudStoreModifyAccepted) WithPayload(payload *models.JobLinkResponse) *CloudStoreModifyAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cloud store modify accepted response
func (o *CloudStoreModifyAccepted) SetPayload(payload *models.JobLinkResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CloudStoreModifyAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
CloudStoreModifyDefault ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 787154 | The Object stores are currently not synchronized. Check the mirror resync status. |
| 787156 | Modifying the attributes of a mirror object store is not allowed. |
Also see the table of common errors in the <a href="#Response_body">Response body</a> overview section of this documentation.

swagger:response cloudStoreModifyDefault
*/
type CloudStoreModifyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewCloudStoreModifyDefault creates CloudStoreModifyDefault with default headers values
func NewCloudStoreModifyDefault(code int) *CloudStoreModifyDefault {
	if code <= 0 {
		code = 500
	}

	return &CloudStoreModifyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the cloud store modify default response
func (o *CloudStoreModifyDefault) WithStatusCode(code int) *CloudStoreModifyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the cloud store modify default response
func (o *CloudStoreModifyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the cloud store modify default response
func (o *CloudStoreModifyDefault) WithPayload(payload *models.ErrorResponse) *CloudStoreModifyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cloud store modify default response
func (o *CloudStoreModifyDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CloudStoreModifyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
