// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// FileMoveCreateCreatedCode is the HTTP code returned for type FileMoveCreateCreated
const FileMoveCreateCreatedCode int = 201

/*
FileMoveCreateCreated Created

swagger:response fileMoveCreateCreated
*/
type FileMoveCreateCreated struct {
	/*Useful for tracking the resource location

	 */
	Location string `json:"Location"`
}

// NewFileMoveCreateCreated creates FileMoveCreateCreated with default headers values
func NewFileMoveCreateCreated() *FileMoveCreateCreated {

	return &FileMoveCreateCreated{}
}

// WithLocation adds the location to the file move create created response
func (o *FileMoveCreateCreated) WithLocation(location string) *FileMoveCreateCreated {
	o.Location = location
	return o
}

// SetLocation sets the location to the file move create created response
func (o *FileMoveCreateCreated) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *FileMoveCreateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*
FileMoveCreateDefault ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 918236 | The specified \"volume.uuid\" and \"volume.name\" do not refer to the same volume. |
| 2621462 | SVM `svm.name` does not exist. |
| 2621706 | The specified \"svm.uuid\" and \"svm.name\" do not refer to the same SVM. |
| 7012352 | File locations are inconsistent. All files must be on the same volume. |
| 7012353 | Exceeded the file operations supported number of files. |
| 7012354 | Unable to pair the number of source files to destination files. |
| 7012357 | Cannot start a file operation until all cluster nodes support the file operations capability. |
| 7012358 | The specified source path is invalid. |
| 7012359 | The specified destination path is invalid. |
| 7012360 | The SVMs are not in an intracluster peering relationship. |
| 7012361 | The SVMs peering relationship does not include application \"file-move\". |
| 7012362 | The SVMs are not yet in a peered state. |
| 7012363 | Cannot move files. All file operations must be managed by the destination SVM's administrator. |
| 7012364 | Cannot move file from SVM \"svm.name\" to SVM \"svm.name\". Moving a file between SVMs is not supported. |
| 7012365 | Copying a file between clusters is not supported. |
| 7012367 | A reference path may only be specified if multiple source paths are specified. |
| 7012368 | The reference path must have a matching source path. |
| 7012371 | The reference cutover time exceeds the maximum allowable time. |
| 7012374 | Source volume and destination volume have different home clusters. |
| 7012376 | Operation not allowed on a volume that is part of a SnapMirror Synchronous relationship. |
| 7012377 | Cannot start a file move operation on the volume because an active volume conversion is in progress. |
| 7013352 | One or more source files must be specified in \"files_to_move.sources\". |
| 7013353 | One or more destination files or directories must be specified in \"files_to_move.destinations\". |
| 7013354 | \"path\" must be specified. |
| 7013355 | Moving files between FlexVol volumes and FlexGroup volumes or constituents is not supported. |
| 7013356 | Moving files between FlexVol volumes and FlexGroup constituents is not supported. |
| 7013357 | The specified volume could not be found. |
| 7013358 | The specified SVM or volume UUID could not be found. |
| 7013359 | The SVM and volume must both be provided. |
| 7018861 | Cannot start the file operation. The volume is offline. |
| 7018877 | Maximum combined total (50) of file and LUN copy and move operations reached. When one or more of the operations has completed, try the command again. |
| 7018937 | The file is already on the destination constituent. |
| 13107222 | Internal error. |
| 13107415 | Failed to lookup a volume property. |
| 13107431 | Failed to lookup an SVM property. |
| 13109260 | Failed to enable granular data on the volume. |
| 144179201 | The file move start operation failed. |
| 144179206 | Source file does not exist. |
| 144179207 | Volume capacity balancing requires an effective cluster version of 9.10.1 or later. |
| 144180200 | Destination constituent not a member of FlexGroup volume. |
| 144180201 | Destination constituent not properly configured. |
| 144180203 | Volume capacity rebalancing is not supported on FlexCache volumes. |
| 144180204 | Volume capacity rebalancing is not supported on object store volumes. |
| 144180205 | The system is busy. |
| 144180207 | Volume capacity rebalancing is not supported on inactive MetroCluster configurations. |
| 144180208 | Disruptive file movement is not supported when granular data is enabled on the volume. Try the operation again using \"disruptive=false\". |
| 144181200 | Too many source or destination files are specified for a file move within a FlexGroup volume. There must be one source file identifying a file on a FlexGroup volume and either zero or one destination files identifying the destination constituent. |
| 144181201 | For a file move within a FlexGroup volume, the source volume must be a FlexGroup volume, and the destination volume must be a constituent. |
| 144181202 | The specified source volume UUID is for a constituent. For a file move within a FlexGroup volume, the source volume must be a FlexGroup volume, and the destination volume must be a constituent. |
| 144181203 | A destination constituent must be provided in \"files_to_move.destinations\" if it is not being selected automatically. Use the \"automatic\" query to enable automatic destination constituent selection. |
| 144181204 | A destination constituent is provided while automatic destination constituent selection is enabled with the \"automatic\" query. |
| 144181205 | The destination volume is not a constituent. For a file move within a FlexGroup volume, the destination volume must be a constituent of the source FlexGroup volume. |
| 144181207 | The destination constituent SVM is not the same as the source SVM. For a file move within a FlexGroup volume, the destination constituent must be a constituent of the source FlexGroup volume. |
| 144181208 | The destination file path is different from the source file path. For a file move within a FlexGroup volume, the path of the source file does not change. |
| 144181209 | The specified SVM for the destination constituent differs from the SVM of the source FlexGroup volume. For a file move within a FlexGroup volume, the destination constituent must be a constituent of the source FlexGroup volume. |
| 144181210 | The \"force\" parameter is not supported unless the \"disruptive\" parameter is specified as \"true\". |
| 144182201 | Volume capacity rebalancing using non-disruptive file move operations and granular data requires an effective cluster version of 9.11.1 or later. |
| 144182228 | Operation is not supported on FlexGroup volumes with only one constituent. |
| 196608143 | Cannot start the operation. The volume is undergoing a secure purge operation. |
Also see the table of common errors in the <a href="#Response_body">Response body</a> overview section of this documentation.

swagger:response fileMoveCreateDefault
*/
type FileMoveCreateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFileMoveCreateDefault creates FileMoveCreateDefault with default headers values
func NewFileMoveCreateDefault(code int) *FileMoveCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &FileMoveCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the file move create default response
func (o *FileMoveCreateDefault) WithStatusCode(code int) *FileMoveCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the file move create default response
func (o *FileMoveCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the file move create default response
func (o *FileMoveCreateDefault) WithPayload(payload *models.ErrorResponse) *FileMoveCreateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the file move create default response
func (o *FileMoveCreateDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FileMoveCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
