// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/metal-stack/ontap-go/api/models"
)

// NewFileMoveCreateParams creates a new FileMoveCreateParams object
// with the default values initialized.
func NewFileMoveCreateParams() FileMoveCreateParams {

	var (
		// initialize parameters with default values

		automaticDefault  = bool(false)
		disruptiveDefault = bool(false)
		forceDefault      = bool(false)

		returnRecordsDefault = bool(false)
	)

	return FileMoveCreateParams{
		Automatic: &automaticDefault,

		Disruptive: &disruptiveDefault,

		Force: &forceDefault,

		ReturnRecords: &returnRecordsDefault,
	}
}

// FileMoveCreateParams contains all the bound params for the file move create operation
// typically these are obtained from a http.Request
//
// swagger:parameters file_move_create
type FileMoveCreateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*If true, the FlexGroup volume file move operation selects the destination constituent automatically.
	  In: query
	  Default: false
	*/
	Automatic *bool
	/*If true, the FlexGroup volume file move operation is disruptive to the clients. The file handle of the file being moved changes. If false, the file handle remains the same. The non-disruptive file move operation is only available on FlexGroup volumes with granular data property enabled.
	  In: query
	  Default: false
	*/
	Disruptive *bool
	/*If true, the FlexGroup volume file move operation breaks the existing lock state on the file being moved. Breaking the lock state may cause a disruption for some client applications.
	  In: query
	  Default: false
	*/
	Force *bool
	/*Info specification
	  In: body
	*/
	Info *models.FileMove
	/*The default is false.  If set to true, the records are returned.
	  In: query
	  Default: false
	*/
	ReturnRecords *bool
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewFileMoveCreateParams() beforehand.
func (o *FileMoveCreateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qAutomatic, qhkAutomatic, _ := qs.GetOK("automatic")
	if err := o.bindAutomatic(qAutomatic, qhkAutomatic, route.Formats); err != nil {
		res = append(res, err)
	}

	qDisruptive, qhkDisruptive, _ := qs.GetOK("disruptive")
	if err := o.bindDisruptive(qDisruptive, qhkDisruptive, route.Formats); err != nil {
		res = append(res, err)
	}

	qForce, qhkForce, _ := qs.GetOK("force")
	if err := o.bindForce(qForce, qhkForce, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.FileMove
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("info", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Info = &body
			}
		}
	}

	qReturnRecords, qhkReturnRecords, _ := qs.GetOK("return_records")
	if err := o.bindReturnRecords(qReturnRecords, qhkReturnRecords, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAutomatic binds and validates parameter Automatic from query.
func (o *FileMoveCreateParams) bindAutomatic(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewFileMoveCreateParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("automatic", "query", "bool", raw)
	}
	o.Automatic = &value

	return nil
}

// bindDisruptive binds and validates parameter Disruptive from query.
func (o *FileMoveCreateParams) bindDisruptive(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewFileMoveCreateParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("disruptive", "query", "bool", raw)
	}
	o.Disruptive = &value

	return nil
}

// bindForce binds and validates parameter Force from query.
func (o *FileMoveCreateParams) bindForce(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewFileMoveCreateParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("force", "query", "bool", raw)
	}
	o.Force = &value

	return nil
}

// bindReturnRecords binds and validates parameter ReturnRecords from query.
func (o *FileMoveCreateParams) bindReturnRecords(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewFileMoveCreateParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("return_records", "query", "bool", raw)
	}
	o.ReturnRecords = &value

	return nil
}
