// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FlexcacheDeleteHandlerFunc turns a function with the right signature into a flexcache delete handler
type FlexcacheDeleteHandlerFunc func(FlexcacheDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn FlexcacheDeleteHandlerFunc) Handle(params FlexcacheDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// FlexcacheDeleteHandler interface for that can handle valid flexcache delete params
type FlexcacheDeleteHandler interface {
	Handle(FlexcacheDeleteParams, interface{}) middleware.Responder
}

// NewFlexcacheDelete creates a new http.Handler for the flexcache delete operation
func NewFlexcacheDelete(ctx *middleware.Context, handler FlexcacheDeleteHandler) *FlexcacheDelete {
	return &FlexcacheDelete{Context: ctx, Handler: handler}
}

/*
	FlexcacheDelete swagger:route DELETE /storage/flexcache/flexcaches/{uuid} Storage flexcacheDelete

Deletes a FlexCache. If a FlexCache volume is online, it is offlined before deletion.
### Related ONTAP commands
* `volume flexcache delete`
### Learn more
* [`DOC /storage/flexcache/flexcaches`](#docs-storage-storage_flexcache_flexcaches)
*/
type FlexcacheDelete struct {
	Context *middleware.Context
	Handler FlexcacheDeleteHandler
}

func (o *FlexcacheDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFlexcacheDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
