// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// ShelfCollectionGetOKCode is the HTTP code returned for type ShelfCollectionGetOK
const ShelfCollectionGetOKCode int = 200

/*
ShelfCollectionGetOK OK

swagger:response shelfCollectionGetOK
*/
type ShelfCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.ShelfResponse `json:"body,omitempty"`
}

// NewShelfCollectionGetOK creates ShelfCollectionGetOK with default headers values
func NewShelfCollectionGetOK() *ShelfCollectionGetOK {

	return &ShelfCollectionGetOK{}
}

// WithPayload adds the payload to the shelf collection get o k response
func (o *ShelfCollectionGetOK) WithPayload(payload *models.ShelfResponse) *ShelfCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the shelf collection get o k response
func (o *ShelfCollectionGetOK) SetPayload(payload *models.ShelfResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShelfCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
ShelfCollectionGetDefault Error

swagger:response shelfCollectionGetDefault
*/
type ShelfCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewShelfCollectionGetDefault creates ShelfCollectionGetDefault with default headers values
func NewShelfCollectionGetDefault(code int) *ShelfCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &ShelfCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the shelf collection get default response
func (o *ShelfCollectionGetDefault) WithStatusCode(code int) *ShelfCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the shelf collection get default response
func (o *ShelfCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the shelf collection get default response
func (o *ShelfCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *ShelfCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the shelf collection get default response
func (o *ShelfCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShelfCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
