// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/metal-stack/ontap-go/api/models"
)

// NewShelfModifyParams creates a new ShelfModifyParams object
//
// There are no default values defined in the spec.
func NewShelfModifyParams() ShelfModifyParams {

	return ShelfModifyParams{}
}

// ShelfModifyParams contains all the bound params for the shelf modify operation
// typically these are obtained from a http.Request
//
// swagger:parameters shelf_modify
type ShelfModifyParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The new property values for the shelf.
	  In: body
	*/
	Info *models.Shelf
	/*Shelf UID
	  Required: true
	  In: path
	*/
	UID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewShelfModifyParams() beforehand.
func (o *ShelfModifyParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Shelf
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("info", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Info = &body
			}
		}
	}

	rUID, rhkUID, _ := route.Params.GetOK("uid")
	if err := o.bindUID(rUID, rhkUID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindUID binds and validates parameter UID from path.
func (o *ShelfModifyParams) bindUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.UID = raw

	return nil
}
