// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SnapshotPolicyGetHandlerFunc turns a function with the right signature into a snapshot policy get handler
type SnapshotPolicyGetHandlerFunc func(SnapshotPolicyGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SnapshotPolicyGetHandlerFunc) Handle(params SnapshotPolicyGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SnapshotPolicyGetHandler interface for that can handle valid snapshot policy get params
type SnapshotPolicyGetHandler interface {
	Handle(SnapshotPolicyGetParams, interface{}) middleware.Responder
}

// NewSnapshotPolicyGet creates a new http.Handler for the snapshot policy get operation
func NewSnapshotPolicyGet(ctx *middleware.Context, handler SnapshotPolicyGetHandler) *SnapshotPolicyGet {
	return &SnapshotPolicyGet{Context: ctx, Handler: handler}
}

/*
	SnapshotPolicyGet swagger:route GET /storage/snapshot-policies/{uuid} Storage snapshotPolicyGet

Retrieves details of a specific Snapshot copy policy.
### Related ONTAP commands
* `snapshot policy show`
### Learn more
* [`DOC /storage/snapshot-policies`](#docs-storage-storage_snapshot-policies)
*/
type SnapshotPolicyGet struct {
	Context *middleware.Context
	Handler SnapshotPolicyGetHandler
}

func (o *SnapshotPolicyGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSnapshotPolicyGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
