// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// SnapshotCreateCreatedCode is the HTTP code returned for type SnapshotCreateCreated
const SnapshotCreateCreatedCode int = 201

/*
SnapshotCreateCreated Created

swagger:response snapshotCreateCreated
*/
type SnapshotCreateCreated struct {
	/*Useful for tracking the resource location

	 */
	Location string `json:"Location"`

	/*
	  In: Body
	*/
	Payload *models.JobLinkResponse `json:"body,omitempty"`
}

// NewSnapshotCreateCreated creates SnapshotCreateCreated with default headers values
func NewSnapshotCreateCreated() *SnapshotCreateCreated {

	return &SnapshotCreateCreated{}
}

// WithLocation adds the location to the snapshot create created response
func (o *SnapshotCreateCreated) WithLocation(location string) *SnapshotCreateCreated {
	o.Location = location
	return o
}

// SetLocation sets the location to the snapshot create created response
func (o *SnapshotCreateCreated) SetLocation(location string) {
	o.Location = location
}

// WithPayload adds the payload to the snapshot create created response
func (o *SnapshotCreateCreated) WithPayload(payload *models.JobLinkResponse) *SnapshotCreateCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the snapshot create created response
func (o *SnapshotCreateCreated) SetPayload(payload *models.JobLinkResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SnapshotCreateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SnapshotCreateAcceptedCode is the HTTP code returned for type SnapshotCreateAccepted
const SnapshotCreateAcceptedCode int = 202

/*
SnapshotCreateAccepted Accepted

swagger:response snapshotCreateAccepted
*/
type SnapshotCreateAccepted struct {
	/*Useful for tracking the resource location

	 */
	Location string `json:"Location"`

	/*
	  In: Body
	*/
	Payload *models.JobLinkResponse `json:"body,omitempty"`
}

// NewSnapshotCreateAccepted creates SnapshotCreateAccepted with default headers values
func NewSnapshotCreateAccepted() *SnapshotCreateAccepted {

	return &SnapshotCreateAccepted{}
}

// WithLocation adds the location to the snapshot create accepted response
func (o *SnapshotCreateAccepted) WithLocation(location string) *SnapshotCreateAccepted {
	o.Location = location
	return o
}

// SetLocation sets the location to the snapshot create accepted response
func (o *SnapshotCreateAccepted) SetLocation(location string) {
	o.Location = location
}

// WithPayload adds the payload to the snapshot create accepted response
func (o *SnapshotCreateAccepted) WithPayload(payload *models.JobLinkResponse) *SnapshotCreateAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the snapshot create accepted response
func (o *SnapshotCreateAccepted) SetPayload(payload *models.JobLinkResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SnapshotCreateAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
SnapshotCreateDefault ONTAP Error Response Code
| Error Code | Description |
| ---------- | ----------- |
| 524479     | The specified volume is not online or does not have enough space to create a Snapshot copy. |
| 525062     | Cannot exceed maximum number of Snapshot copies. |
| 2621462    | The specified SVM name does not exist. |
| 525059     | A Snapshot copy with the specified name already exists. |
| 1638461    | Snapshot copies can only be created on read/write (RW) volumes. |
| 1638477    | User-created Snapshot copy names cannot begin with the specified prefix. |
| 1638518    | The specified Snapshot copy name is invalid. |
| 1638532    | Failed to create the Snapshot copy on the specified volume because a revert operation is in progress. |
| 1638537    | Cannot determine the status of the Snapshot copy create operation for the specified volume. |
| 1638574    | The \"expiry-time\" parameter is not supported for FlexGroup volumes. |
| 1638616    | Bulk Snapshot copy create is not supported with multiple Snapshot copy names. |
| 1638617    | Bulk Snapshot copy create is not supported with volume names in a mixed-version cluster. |
| 1638618    | The property cannot be specified for Snapshot copy create. |
| 1638630    | Snapshot copy create operation is not supported on destination of SnapMirror active sync relationship with policy-type "automated-failover-duplex". |

swagger:response snapshotCreateDefault
*/
type SnapshotCreateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSnapshotCreateDefault creates SnapshotCreateDefault with default headers values
func NewSnapshotCreateDefault(code int) *SnapshotCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &SnapshotCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the snapshot create default response
func (o *SnapshotCreateDefault) WithStatusCode(code int) *SnapshotCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the snapshot create default response
func (o *SnapshotCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the snapshot create default response
func (o *SnapshotCreateDefault) WithPayload(payload *models.ErrorResponse) *SnapshotCreateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the snapshot create default response
func (o *SnapshotCreateDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SnapshotCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
