// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// SnapshotPolicyScheduleCollectionGetURL generates an URL for the snapshot policy schedule collection get operation
type SnapshotPolicyScheduleCollectionGetURL struct {
	SnapshotPolicyUUID string

	Count              *int64
	Fields             []string
	MaxRecords         *int64
	OrderBy            []string
	Prefix             *string
	RetentionPeriod    *string
	ReturnRecords      *bool
	ReturnTimeout      *int64
	ScheduleName       *string
	ScheduleUUID       *string
	SnapmirrorLabel    *string
	SnapshotPolicyName *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SnapshotPolicyScheduleCollectionGetURL) WithBasePath(bp string) *SnapshotPolicyScheduleCollectionGetURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SnapshotPolicyScheduleCollectionGetURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *SnapshotPolicyScheduleCollectionGetURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/storage/snapshot-policies/{snapshot_policy.uuid}/schedules"

	snapshotPolicyUUID := o.SnapshotPolicyUUID
	if snapshotPolicyUUID != "" {
		_path = strings.Replace(_path, "{snapshot_policy.uuid}", snapshotPolicyUUID, -1)
	} else {
		return nil, errors.New("snapshotPolicyUuid is required on SnapshotPolicyScheduleCollectionGetURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var countQ string
	if o.Count != nil {
		countQ = swag.FormatInt64(*o.Count)
	}
	if countQ != "" {
		qs.Set("count", countQ)
	}

	var fieldsIR []string
	for _, fieldsI := range o.Fields {
		fieldsIS := fieldsI
		if fieldsIS != "" {
			fieldsIR = append(fieldsIR, fieldsIS)
		}
	}

	fields := swag.JoinByFormat(fieldsIR, "csv")

	if len(fields) > 0 {
		qsv := fields[0]
		if qsv != "" {
			qs.Set("fields", qsv)
		}
	}

	var maxRecordsQ string
	if o.MaxRecords != nil {
		maxRecordsQ = swag.FormatInt64(*o.MaxRecords)
	}
	if maxRecordsQ != "" {
		qs.Set("max_records", maxRecordsQ)
	}

	var orderByIR []string
	for _, orderByI := range o.OrderBy {
		orderByIS := orderByI
		if orderByIS != "" {
			orderByIR = append(orderByIR, orderByIS)
		}
	}

	orderBy := swag.JoinByFormat(orderByIR, "csv")

	if len(orderBy) > 0 {
		qsv := orderBy[0]
		if qsv != "" {
			qs.Set("order_by", qsv)
		}
	}

	var prefixQ string
	if o.Prefix != nil {
		prefixQ = *o.Prefix
	}
	if prefixQ != "" {
		qs.Set("prefix", prefixQ)
	}

	var retentionPeriodQ string
	if o.RetentionPeriod != nil {
		retentionPeriodQ = *o.RetentionPeriod
	}
	if retentionPeriodQ != "" {
		qs.Set("retention_period", retentionPeriodQ)
	}

	var returnRecordsQ string
	if o.ReturnRecords != nil {
		returnRecordsQ = swag.FormatBool(*o.ReturnRecords)
	}
	if returnRecordsQ != "" {
		qs.Set("return_records", returnRecordsQ)
	}

	var returnTimeoutQ string
	if o.ReturnTimeout != nil {
		returnTimeoutQ = swag.FormatInt64(*o.ReturnTimeout)
	}
	if returnTimeoutQ != "" {
		qs.Set("return_timeout", returnTimeoutQ)
	}

	var scheduleNameQ string
	if o.ScheduleName != nil {
		scheduleNameQ = *o.ScheduleName
	}
	if scheduleNameQ != "" {
		qs.Set("schedule.name", scheduleNameQ)
	}

	var scheduleUUIDQ string
	if o.ScheduleUUID != nil {
		scheduleUUIDQ = *o.ScheduleUUID
	}
	if scheduleUUIDQ != "" {
		qs.Set("schedule.uuid", scheduleUUIDQ)
	}

	var snapmirrorLabelQ string
	if o.SnapmirrorLabel != nil {
		snapmirrorLabelQ = *o.SnapmirrorLabel
	}
	if snapmirrorLabelQ != "" {
		qs.Set("snapmirror_label", snapmirrorLabelQ)
	}

	var snapshotPolicyNameQ string
	if o.SnapshotPolicyName != nil {
		snapshotPolicyNameQ = *o.SnapshotPolicyName
	}
	if snapshotPolicyNameQ != "" {
		qs.Set("snapshot_policy.name", snapshotPolicyNameQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *SnapshotPolicyScheduleCollectionGetURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *SnapshotPolicyScheduleCollectionGetURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *SnapshotPolicyScheduleCollectionGetURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on SnapshotPolicyScheduleCollectionGetURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on SnapshotPolicyScheduleCollectionGetURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *SnapshotPolicyScheduleCollectionGetURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
