// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewSnapshotPolicyScheduleCollectionGetParams creates a new SnapshotPolicyScheduleCollectionGetParams object
// with the default values initialized.
func NewSnapshotPolicyScheduleCollectionGetParams() SnapshotPolicyScheduleCollectionGetParams {

	var (
		// initialize parameters with default values

		returnRecordsDefault = bool(true)
		returnTimeoutDefault = int64(15)
	)

	return SnapshotPolicyScheduleCollectionGetParams{
		ReturnRecords: &returnRecordsDefault,

		ReturnTimeout: &returnTimeoutDefault,
	}
}

// SnapshotPolicyScheduleCollectionGetParams contains all the bound params for the snapshot policy schedule collection get operation
// typically these are obtained from a http.Request
//
// swagger:parameters snapshot_policy_schedule_collection_get
type SnapshotPolicyScheduleCollectionGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Filter by count
	  In: query
	*/
	Count *int64
	/*Specify the fields to return.
	  In: query
	  Collection Format: csv
	*/
	Fields []string
	/*Limit the number of records returned.
	  In: query
	*/
	MaxRecords *int64
	/*Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.
	  In: query
	  Collection Format: csv
	*/
	OrderBy []string
	/*Filter by prefix
	  In: query
	*/
	Prefix *string
	/*Filter by retention_period
	  In: query
	*/
	RetentionPeriod *string
	/*The default is true for GET calls.  When set to false, only the number of records is returned.
	  In: query
	  Default: true
	*/
	ReturnRecords *bool
	/*The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.
	  Maximum: 120
	  Minimum: 0
	  In: query
	  Default: 15
	*/
	ReturnTimeout *int64
	/*Filter by schedule.name
	  In: query
	*/
	ScheduleName *string
	/*Filter by schedule.uuid
	  In: query
	*/
	ScheduleUUID *string
	/*Filter by snapmirror_label
	  In: query
	*/
	SnapmirrorLabel *string
	/*Filter by snapshot_policy.name
	  In: query
	*/
	SnapshotPolicyName *string
	/*Snapshot copy policy UUID
	  Required: true
	  In: path
	*/
	SnapshotPolicyUUID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSnapshotPolicyScheduleCollectionGetParams() beforehand.
func (o *SnapshotPolicyScheduleCollectionGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qCount, qhkCount, _ := qs.GetOK("count")
	if err := o.bindCount(qCount, qhkCount, route.Formats); err != nil {
		res = append(res, err)
	}

	qFields, qhkFields, _ := qs.GetOK("fields")
	if err := o.bindFields(qFields, qhkFields, route.Formats); err != nil {
		res = append(res, err)
	}

	qMaxRecords, qhkMaxRecords, _ := qs.GetOK("max_records")
	if err := o.bindMaxRecords(qMaxRecords, qhkMaxRecords, route.Formats); err != nil {
		res = append(res, err)
	}

	qOrderBy, qhkOrderBy, _ := qs.GetOK("order_by")
	if err := o.bindOrderBy(qOrderBy, qhkOrderBy, route.Formats); err != nil {
		res = append(res, err)
	}

	qPrefix, qhkPrefix, _ := qs.GetOK("prefix")
	if err := o.bindPrefix(qPrefix, qhkPrefix, route.Formats); err != nil {
		res = append(res, err)
	}

	qRetentionPeriod, qhkRetentionPeriod, _ := qs.GetOK("retention_period")
	if err := o.bindRetentionPeriod(qRetentionPeriod, qhkRetentionPeriod, route.Formats); err != nil {
		res = append(res, err)
	}

	qReturnRecords, qhkReturnRecords, _ := qs.GetOK("return_records")
	if err := o.bindReturnRecords(qReturnRecords, qhkReturnRecords, route.Formats); err != nil {
		res = append(res, err)
	}

	qReturnTimeout, qhkReturnTimeout, _ := qs.GetOK("return_timeout")
	if err := o.bindReturnTimeout(qReturnTimeout, qhkReturnTimeout, route.Formats); err != nil {
		res = append(res, err)
	}

	qScheduleName, qhkScheduleName, _ := qs.GetOK("schedule.name")
	if err := o.bindScheduleName(qScheduleName, qhkScheduleName, route.Formats); err != nil {
		res = append(res, err)
	}

	qScheduleUUID, qhkScheduleUUID, _ := qs.GetOK("schedule.uuid")
	if err := o.bindScheduleUUID(qScheduleUUID, qhkScheduleUUID, route.Formats); err != nil {
		res = append(res, err)
	}

	qSnapmirrorLabel, qhkSnapmirrorLabel, _ := qs.GetOK("snapmirror_label")
	if err := o.bindSnapmirrorLabel(qSnapmirrorLabel, qhkSnapmirrorLabel, route.Formats); err != nil {
		res = append(res, err)
	}

	qSnapshotPolicyName, qhkSnapshotPolicyName, _ := qs.GetOK("snapshot_policy.name")
	if err := o.bindSnapshotPolicyName(qSnapshotPolicyName, qhkSnapshotPolicyName, route.Formats); err != nil {
		res = append(res, err)
	}

	rSnapshotPolicyUUID, rhkSnapshotPolicyUUID, _ := route.Params.GetOK("snapshot_policy.uuid")
	if err := o.bindSnapshotPolicyUUID(rSnapshotPolicyUUID, rhkSnapshotPolicyUUID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCount binds and validates parameter Count from query.
func (o *SnapshotPolicyScheduleCollectionGetParams) bindCount(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("count", "query", "int64", raw)
	}
	o.Count = &value

	return nil
}

// bindFields binds and validates array parameter Fields from query.
//
// Arrays are parsed according to CollectionFormat: "csv" (defaults to "csv" when empty).
func (o *SnapshotPolicyScheduleCollectionGetParams) bindFields(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var qvFields string
	if len(rawData) > 0 {
		qvFields = rawData[len(rawData)-1]
	}

	// CollectionFormat: csv
	fieldsIC := swag.SplitByFormat(qvFields, "csv")
	if len(fieldsIC) == 0 {
		return nil
	}

	var fieldsIR []string
	for _, fieldsIV := range fieldsIC {
		fieldsI := fieldsIV

		fieldsIR = append(fieldsIR, fieldsI)
	}

	o.Fields = fieldsIR

	return nil
}

// bindMaxRecords binds and validates parameter MaxRecords from query.
func (o *SnapshotPolicyScheduleCollectionGetParams) bindMaxRecords(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("max_records", "query", "int64", raw)
	}
	o.MaxRecords = &value

	return nil
}

// bindOrderBy binds and validates array parameter OrderBy from query.
//
// Arrays are parsed according to CollectionFormat: "csv" (defaults to "csv" when empty).
func (o *SnapshotPolicyScheduleCollectionGetParams) bindOrderBy(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var qvOrderBy string
	if len(rawData) > 0 {
		qvOrderBy = rawData[len(rawData)-1]
	}

	// CollectionFormat: csv
	orderByIC := swag.SplitByFormat(qvOrderBy, "csv")
	if len(orderByIC) == 0 {
		return nil
	}

	var orderByIR []string
	for _, orderByIV := range orderByIC {
		orderByI := orderByIV

		orderByIR = append(orderByIR, orderByI)
	}

	o.OrderBy = orderByIR

	return nil
}

// bindPrefix binds and validates parameter Prefix from query.
func (o *SnapshotPolicyScheduleCollectionGetParams) bindPrefix(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Prefix = &raw

	return nil
}

// bindRetentionPeriod binds and validates parameter RetentionPeriod from query.
func (o *SnapshotPolicyScheduleCollectionGetParams) bindRetentionPeriod(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.RetentionPeriod = &raw

	return nil
}

// bindReturnRecords binds and validates parameter ReturnRecords from query.
func (o *SnapshotPolicyScheduleCollectionGetParams) bindReturnRecords(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewSnapshotPolicyScheduleCollectionGetParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("return_records", "query", "bool", raw)
	}
	o.ReturnRecords = &value

	return nil
}

// bindReturnTimeout binds and validates parameter ReturnTimeout from query.
func (o *SnapshotPolicyScheduleCollectionGetParams) bindReturnTimeout(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewSnapshotPolicyScheduleCollectionGetParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("return_timeout", "query", "int64", raw)
	}
	o.ReturnTimeout = &value

	if err := o.validateReturnTimeout(formats); err != nil {
		return err
	}

	return nil
}

// validateReturnTimeout carries on validations for parameter ReturnTimeout
func (o *SnapshotPolicyScheduleCollectionGetParams) validateReturnTimeout(formats strfmt.Registry) error {

	if err := validate.MinimumInt("return_timeout", "query", *o.ReturnTimeout, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("return_timeout", "query", *o.ReturnTimeout, 120, false); err != nil {
		return err
	}

	return nil
}

// bindScheduleName binds and validates parameter ScheduleName from query.
func (o *SnapshotPolicyScheduleCollectionGetParams) bindScheduleName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ScheduleName = &raw

	return nil
}

// bindScheduleUUID binds and validates parameter ScheduleUUID from query.
func (o *SnapshotPolicyScheduleCollectionGetParams) bindScheduleUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ScheduleUUID = &raw

	return nil
}

// bindSnapmirrorLabel binds and validates parameter SnapmirrorLabel from query.
func (o *SnapshotPolicyScheduleCollectionGetParams) bindSnapmirrorLabel(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.SnapmirrorLabel = &raw

	return nil
}

// bindSnapshotPolicyName binds and validates parameter SnapshotPolicyName from query.
func (o *SnapshotPolicyScheduleCollectionGetParams) bindSnapshotPolicyName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.SnapshotPolicyName = &raw

	return nil
}

// bindSnapshotPolicyUUID binds and validates parameter SnapshotPolicyUUID from path.
func (o *SnapshotPolicyScheduleCollectionGetParams) bindSnapshotPolicyUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SnapshotPolicyUUID = raw

	return nil
}
