// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// StoragePoolGetOKCode is the HTTP code returned for type StoragePoolGetOK
const StoragePoolGetOKCode int = 200

/*
StoragePoolGetOK OK

swagger:response storagePoolGetOK
*/
type StoragePoolGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.StoragePool `json:"body,omitempty"`
}

// NewStoragePoolGetOK creates StoragePoolGetOK with default headers values
func NewStoragePoolGetOK() *StoragePoolGetOK {

	return &StoragePoolGetOK{}
}

// WithPayload adds the payload to the storage pool get o k response
func (o *StoragePoolGetOK) WithPayload(payload *models.StoragePool) *StoragePoolGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the storage pool get o k response
func (o *StoragePoolGetOK) SetPayload(payload *models.StoragePool) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StoragePoolGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
StoragePoolGetDefault ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 11206662 | There is no storage pool matching the specified UUID or name. |
| 11215856 | The specified storage pool is not healthy. |
Also see the table of common errors in the <a href="#Response_body">Response body</a> overview section of this documentation.

swagger:response storagePoolGetDefault
*/
type StoragePoolGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewStoragePoolGetDefault creates StoragePoolGetDefault with default headers values
func NewStoragePoolGetDefault(code int) *StoragePoolGetDefault {
	if code <= 0 {
		code = 500
	}

	return &StoragePoolGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the storage pool get default response
func (o *StoragePoolGetDefault) WithStatusCode(code int) *StoragePoolGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the storage pool get default response
func (o *StoragePoolGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the storage pool get default response
func (o *StoragePoolGetDefault) WithPayload(payload *models.ErrorResponse) *StoragePoolGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the storage pool get default response
func (o *StoragePoolGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StoragePoolGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
