// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// StoragePoolDeleteHandlerFunc turns a function with the right signature into a storage pool delete handler
type StoragePoolDeleteHandlerFunc func(StoragePoolDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn StoragePoolDeleteHandlerFunc) Handle(params StoragePoolDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// StoragePoolDeleteHandler interface for that can handle valid storage pool delete params
type StoragePoolDeleteHandler interface {
	Handle(StoragePoolDeleteParams, interface{}) middleware.Responder
}

// NewStoragePoolDelete creates a new http.Handler for the storage pool delete operation
func NewStoragePoolDelete(ctx *middleware.Context, handler StoragePoolDeleteHandler) *StoragePoolDelete {
	return &StoragePoolDelete{Context: ctx, Handler: handler}
}

/*
	StoragePoolDelete swagger:route DELETE /storage/pools/{uuid} Storage storagePoolDelete

Deletes the storage pool specified by the UUID. This request starts a job and returns a link to that job.
### Related ONTAP commands
* `storage pool delete`
*/
type StoragePoolDelete struct {
	Context *middleware.Context
	Handler StoragePoolDeleteHandler
}

func (o *StoragePoolDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewStoragePoolDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
