// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// VolumeEfficiencyPolicyDeleteOKCode is the HTTP code returned for type VolumeEfficiencyPolicyDeleteOK
const VolumeEfficiencyPolicyDeleteOKCode int = 200

/*
VolumeEfficiencyPolicyDeleteOK OK

swagger:response volumeEfficiencyPolicyDeleteOK
*/
type VolumeEfficiencyPolicyDeleteOK struct {
}

// NewVolumeEfficiencyPolicyDeleteOK creates VolumeEfficiencyPolicyDeleteOK with default headers values
func NewVolumeEfficiencyPolicyDeleteOK() *VolumeEfficiencyPolicyDeleteOK {

	return &VolumeEfficiencyPolicyDeleteOK{}
}

// WriteResponse to the client
func (o *VolumeEfficiencyPolicyDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
VolumeEfficiencyPolicyDeleteDefault ONTAP Error Response Code
| Error Code | Description |
| ---------  | ----------- |
|  6881346   | The policy was not deleted because the policy is in use by at least one volume. |
|  6881347   | This operation cannot be performed because the specified policy is owned by the cluster admin. |
|  6881431   | The specified policy is a predefined policy and cannot be deleted. |

swagger:response volumeEfficiencyPolicyDeleteDefault
*/
type VolumeEfficiencyPolicyDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewVolumeEfficiencyPolicyDeleteDefault creates VolumeEfficiencyPolicyDeleteDefault with default headers values
func NewVolumeEfficiencyPolicyDeleteDefault(code int) *VolumeEfficiencyPolicyDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &VolumeEfficiencyPolicyDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the volume efficiency policy delete default response
func (o *VolumeEfficiencyPolicyDeleteDefault) WithStatusCode(code int) *VolumeEfficiencyPolicyDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the volume efficiency policy delete default response
func (o *VolumeEfficiencyPolicyDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the volume efficiency policy delete default response
func (o *VolumeEfficiencyPolicyDeleteDefault) WithPayload(payload *models.ErrorResponse) *VolumeEfficiencyPolicyDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the volume efficiency policy delete default response
func (o *VolumeEfficiencyPolicyDeleteDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VolumeEfficiencyPolicyDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
