// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AccountGetHandlerFunc turns a function with the right signature into a account get handler
type AccountGetHandlerFunc func(AccountGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AccountGetHandlerFunc) Handle(params AccountGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AccountGetHandler interface for that can handle valid account get params
type AccountGetHandler interface {
	Handle(AccountGetParams, interface{}) middleware.Responder
}

// NewAccountGet creates a new http.Handler for the account get operation
func NewAccountGet(ctx *middleware.Context, handler AccountGetHandler) *AccountGet {
	return &AccountGet{Context: ctx, Handler: handler}
}

/*
	AccountGet swagger:route GET /security/accounts/{owner.uuid}/{name} Security accountGet

Retrieves a specific user account.
### Related ONTAP commands
* `security login show`
### Learn more
* [`DOC /security/accounts/{owner.uuid}/{name}`](#docs-security-security_accounts_{owner.uuid}_{name})
* [`DOC /security/accounts`](#docs-security-security_accounts)
*/
type AccountGet struct {
	Context *middleware.Context
	Handler AccountGetHandler
}

func (o *AccountGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAccountGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
