// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// GcpKmsDeleteOKCode is the HTTP code returned for type GcpKmsDeleteOK
const GcpKmsDeleteOKCode int = 200

/*
GcpKmsDeleteOK OK

swagger:response gcpKmsDeleteOK
*/
type GcpKmsDeleteOK struct {
}

// NewGcpKmsDeleteOK creates GcpKmsDeleteOK with default headers values
func NewGcpKmsDeleteOK() *GcpKmsDeleteOK {

	return &GcpKmsDeleteOK{}
}

// WriteResponse to the client
func (o *GcpKmsDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GcpKmsDeleteAcceptedCode is the HTTP code returned for type GcpKmsDeleteAccepted
const GcpKmsDeleteAcceptedCode int = 202

/*
GcpKmsDeleteAccepted Accepted

swagger:response gcpKmsDeleteAccepted
*/
type GcpKmsDeleteAccepted struct {

	/*
	  In: Body
	*/
	Payload *models.JobLinkResponse `json:"body,omitempty"`
}

// NewGcpKmsDeleteAccepted creates GcpKmsDeleteAccepted with default headers values
func NewGcpKmsDeleteAccepted() *GcpKmsDeleteAccepted {

	return &GcpKmsDeleteAccepted{}
}

// WithPayload adds the payload to the gcp kms delete accepted response
func (o *GcpKmsDeleteAccepted) WithPayload(payload *models.JobLinkResponse) *GcpKmsDeleteAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the gcp kms delete accepted response
func (o *GcpKmsDeleteAccepted) SetPayload(payload *models.JobLinkResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GcpKmsDeleteAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GcpKmsDeleteDefault ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 65536817 | Internal error. Failed to determine if it is safe to disable key manager. |
| 65536827 | Internal error. Failed to determine if the given SVM has any encrypted volumes. |
| 65536834 | Internal error. Failed to get existing key-server details for the given SVM. |
| 65536867 | Volume encryption keys (VEK) for one or more encrypted volumes are stored on the key manager configured for the given SVM. |
| 65536883 | Internal error. Volume encryption key is missing for a volume. |
| 65536884 | Internal error. Volume encryption key is invalid for a volume. |
| 65537721 | The Google Cloud Key Management Service is not configured for the SVM. |
| 196608080 | One or more nodes in the cluster have the root volume encrypted using NVE (NetApp Volume Encryption). |
| 196608301 | Internal error. Failed to get encryption type. |
Also see the table of common errors in the <a href="#Response_body">Response body</a> overview section of this documentation.

swagger:response gcpKmsDeleteDefault
*/
type GcpKmsDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGcpKmsDeleteDefault creates GcpKmsDeleteDefault with default headers values
func NewGcpKmsDeleteDefault(code int) *GcpKmsDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &GcpKmsDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the gcp kms delete default response
func (o *GcpKmsDeleteDefault) WithStatusCode(code int) *GcpKmsDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the gcp kms delete default response
func (o *GcpKmsDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the gcp kms delete default response
func (o *GcpKmsDeleteDefault) WithPayload(payload *models.ErrorResponse) *GcpKmsDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the gcp kms delete default response
func (o *GcpKmsDeleteDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GcpKmsDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
