// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// LoginMessagesModifyOKCode is the HTTP code returned for type LoginMessagesModifyOK
const LoginMessagesModifyOKCode int = 200

/*
LoginMessagesModifyOK OK

swagger:response loginMessagesModifyOK
*/
type LoginMessagesModifyOK struct {
}

// NewLoginMessagesModifyOK creates LoginMessagesModifyOK with default headers values
func NewLoginMessagesModifyOK() *LoginMessagesModifyOK {

	return &LoginMessagesModifyOK{}
}

// WriteResponse to the client
func (o *LoginMessagesModifyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
LoginMessagesModifyDefault ONTAP Error Response codes
| Error codes | Description |
| ----------- | ----------- |
| 10225636    | Only a cluster administrator can modify the `show_cluster_message` property. |

swagger:response loginMessagesModifyDefault
*/
type LoginMessagesModifyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewLoginMessagesModifyDefault creates LoginMessagesModifyDefault with default headers values
func NewLoginMessagesModifyDefault(code int) *LoginMessagesModifyDefault {
	if code <= 0 {
		code = 500
	}

	return &LoginMessagesModifyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the login messages modify default response
func (o *LoginMessagesModifyDefault) WithStatusCode(code int) *LoginMessagesModifyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the login messages modify default response
func (o *LoginMessagesModifyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the login messages modify default response
func (o *LoginMessagesModifyDefault) WithPayload(payload *models.ErrorResponse) *LoginMessagesModifyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the login messages modify default response
func (o *LoginMessagesModifyDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LoginMessagesModifyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
