// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RoleGetHandlerFunc turns a function with the right signature into a role get handler
type RoleGetHandlerFunc func(RoleGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RoleGetHandlerFunc) Handle(params RoleGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RoleGetHandler interface for that can handle valid role get params
type RoleGetHandler interface {
	Handle(RoleGetParams, interface{}) middleware.Responder
}

// NewRoleGet creates a new http.Handler for the role get operation
func NewRoleGet(ctx *middleware.Context, handler RoleGetHandler) *RoleGet {
	return &RoleGet{Context: ctx, Handler: handler}
}

/*
	RoleGet swagger:route GET /security/roles/{owner.uuid}/{name} Security roleGet

Retrieves the details of the specified role.
### Related ONTAP commands
* `security login rest-role show`
* `security login role show`
### Learn more
* [`DOC /security/roles/{owner.uuid}/{name}`](#docs-security-security_roles_{owner.uuid}_{name})
* [`DOC /security/roles`](#docs-security-security_roles)
*/
type RoleGet struct {
	Context *middleware.Context
	Handler RoleGetHandler
}

func (o *RoleGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRoleGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
