// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// SecurityAssociationCollectionGetOKCode is the HTTP code returned for type SecurityAssociationCollectionGetOK
const SecurityAssociationCollectionGetOKCode int = 200

/*
SecurityAssociationCollectionGetOK OK

swagger:response securityAssociationCollectionGetOK
*/
type SecurityAssociationCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.SecurityAssociationResponse `json:"body,omitempty"`
}

// NewSecurityAssociationCollectionGetOK creates SecurityAssociationCollectionGetOK with default headers values
func NewSecurityAssociationCollectionGetOK() *SecurityAssociationCollectionGetOK {

	return &SecurityAssociationCollectionGetOK{}
}

// WithPayload adds the payload to the security association collection get o k response
func (o *SecurityAssociationCollectionGetOK) WithPayload(payload *models.SecurityAssociationResponse) *SecurityAssociationCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the security association collection get o k response
func (o *SecurityAssociationCollectionGetOK) SetPayload(payload *models.SecurityAssociationResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SecurityAssociationCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
SecurityAssociationCollectionGetDefault Error

swagger:response securityAssociationCollectionGetDefault
*/
type SecurityAssociationCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSecurityAssociationCollectionGetDefault creates SecurityAssociationCollectionGetDefault with default headers values
func NewSecurityAssociationCollectionGetDefault(code int) *SecurityAssociationCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &SecurityAssociationCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the security association collection get default response
func (o *SecurityAssociationCollectionGetDefault) WithStatusCode(code int) *SecurityAssociationCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the security association collection get default response
func (o *SecurityAssociationCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the security association collection get default response
func (o *SecurityAssociationCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *SecurityAssociationCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the security association collection get default response
func (o *SecurityAssociationCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SecurityAssociationCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
