// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SecurityOauth2CreateHandlerFunc turns a function with the right signature into a security oauth2 create handler
type SecurityOauth2CreateHandlerFunc func(SecurityOauth2CreateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SecurityOauth2CreateHandlerFunc) Handle(params SecurityOauth2CreateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SecurityOauth2CreateHandler interface for that can handle valid security oauth2 create params
type SecurityOauth2CreateHandler interface {
	Handle(SecurityOauth2CreateParams, interface{}) middleware.Responder
}

// NewSecurityOauth2Create creates a new http.Handler for the security oauth2 create operation
func NewSecurityOauth2Create(ctx *middleware.Context, handler SecurityOauth2CreateHandler) *SecurityOauth2Create {
	return &SecurityOauth2Create{Context: ctx, Handler: handler}
}

/*
	SecurityOauth2Create swagger:route POST /security/authentication/cluster/oauth2/clients Security securityOauth2Create

Creates the OAuth 2.0 configuration.
### Required properties
* `name`
* `application`
* `issuer`
### Optional properties
* `audience`
* `client_id`
* `client_secret`
* `introspection.endpoint_uri`
* `introspection.interval`
* `remote_user_claim`
* `jwks.provider_uri`
* `jwks.refresh_interval`
* `outgoing_proxy`
* `use_local_roles_if_present`
* `skip_uri_validation`
* `use_mutual_tls`
### Related ONTAP commands
* `security oauth2 client create`
*/
type SecurityOauth2Create struct {
	Context *middleware.Context
	Handler SecurityOauth2CreateHandler
}

func (o *SecurityOauth2Create) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSecurityOauth2CreateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
