// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// SecurityKeyManagerCollectionGetURL generates an URL for the security key manager collection get operation
type SecurityKeyManagerCollectionGetURL struct {
	ExternalClientCertificateName                  *string
	ExternalClientCertificateUUID                  *string
	ExternalServerCaCertificatesName               *string
	ExternalServerCaCertificatesUUID               *string
	ExternalServersConnectivityClusterAvailability *bool
	ExternalServersConnectivityNodeStatesNodeName  *string
	ExternalServersConnectivityNodeStatesNodeUUID  *string
	ExternalServersConnectivityNodeStatesState     *string
	ExternalServersSecondaryKeyServers             *string
	ExternalServersServer                          *string
	ExternalServersTimeout                         *int64
	ExternalServersUsername                        *string
	Fields                                         []string
	IsDefaultDataAtRestEncryptionDisabled          *bool
	MaxRecords                                     *int64
	OnboardEnabled                                 *bool
	OnboardKeyBackup                               *string
	OrderBy                                        []string
	Policy                                         *string
	ReturnRecords                                  *bool
	ReturnTimeout                                  *int64
	Scope                                          *string
	StatusCode                                     *int64
	StatusMessage                                  *string
	SvmName                                        *string
	SvmUUID                                        *string
	UUID                                           *string
	VolumeEncryptionCode                           *int64
	VolumeEncryptionMessage                        *string
	VolumeEncryptionSupported                      *bool

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SecurityKeyManagerCollectionGetURL) WithBasePath(bp string) *SecurityKeyManagerCollectionGetURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SecurityKeyManagerCollectionGetURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *SecurityKeyManagerCollectionGetURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/security/key-managers"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var externalClientCertificateNameQ string
	if o.ExternalClientCertificateName != nil {
		externalClientCertificateNameQ = *o.ExternalClientCertificateName
	}
	if externalClientCertificateNameQ != "" {
		qs.Set("external.client_certificate.name", externalClientCertificateNameQ)
	}

	var externalClientCertificateUUIDQ string
	if o.ExternalClientCertificateUUID != nil {
		externalClientCertificateUUIDQ = *o.ExternalClientCertificateUUID
	}
	if externalClientCertificateUUIDQ != "" {
		qs.Set("external.client_certificate.uuid", externalClientCertificateUUIDQ)
	}

	var externalServerCaCertificatesNameQ string
	if o.ExternalServerCaCertificatesName != nil {
		externalServerCaCertificatesNameQ = *o.ExternalServerCaCertificatesName
	}
	if externalServerCaCertificatesNameQ != "" {
		qs.Set("external.server_ca_certificates.name", externalServerCaCertificatesNameQ)
	}

	var externalServerCaCertificatesUUIDQ string
	if o.ExternalServerCaCertificatesUUID != nil {
		externalServerCaCertificatesUUIDQ = *o.ExternalServerCaCertificatesUUID
	}
	if externalServerCaCertificatesUUIDQ != "" {
		qs.Set("external.server_ca_certificates.uuid", externalServerCaCertificatesUUIDQ)
	}

	var externalServersConnectivityClusterAvailabilityQ string
	if o.ExternalServersConnectivityClusterAvailability != nil {
		externalServersConnectivityClusterAvailabilityQ = swag.FormatBool(*o.ExternalServersConnectivityClusterAvailability)
	}
	if externalServersConnectivityClusterAvailabilityQ != "" {
		qs.Set("external.servers.connectivity.cluster_availability", externalServersConnectivityClusterAvailabilityQ)
	}

	var externalServersConnectivityNodeStatesNodeNameQ string
	if o.ExternalServersConnectivityNodeStatesNodeName != nil {
		externalServersConnectivityNodeStatesNodeNameQ = *o.ExternalServersConnectivityNodeStatesNodeName
	}
	if externalServersConnectivityNodeStatesNodeNameQ != "" {
		qs.Set("external.servers.connectivity.node_states.node.name", externalServersConnectivityNodeStatesNodeNameQ)
	}

	var externalServersConnectivityNodeStatesNodeUUIDQ string
	if o.ExternalServersConnectivityNodeStatesNodeUUID != nil {
		externalServersConnectivityNodeStatesNodeUUIDQ = *o.ExternalServersConnectivityNodeStatesNodeUUID
	}
	if externalServersConnectivityNodeStatesNodeUUIDQ != "" {
		qs.Set("external.servers.connectivity.node_states.node.uuid", externalServersConnectivityNodeStatesNodeUUIDQ)
	}

	var externalServersConnectivityNodeStatesStateQ string
	if o.ExternalServersConnectivityNodeStatesState != nil {
		externalServersConnectivityNodeStatesStateQ = *o.ExternalServersConnectivityNodeStatesState
	}
	if externalServersConnectivityNodeStatesStateQ != "" {
		qs.Set("external.servers.connectivity.node_states.state", externalServersConnectivityNodeStatesStateQ)
	}

	var externalServersSecondaryKeyServersQ string
	if o.ExternalServersSecondaryKeyServers != nil {
		externalServersSecondaryKeyServersQ = *o.ExternalServersSecondaryKeyServers
	}
	if externalServersSecondaryKeyServersQ != "" {
		qs.Set("external.servers.secondary_key_servers", externalServersSecondaryKeyServersQ)
	}

	var externalServersServerQ string
	if o.ExternalServersServer != nil {
		externalServersServerQ = *o.ExternalServersServer
	}
	if externalServersServerQ != "" {
		qs.Set("external.servers.server", externalServersServerQ)
	}

	var externalServersTimeoutQ string
	if o.ExternalServersTimeout != nil {
		externalServersTimeoutQ = swag.FormatInt64(*o.ExternalServersTimeout)
	}
	if externalServersTimeoutQ != "" {
		qs.Set("external.servers.timeout", externalServersTimeoutQ)
	}

	var externalServersUsernameQ string
	if o.ExternalServersUsername != nil {
		externalServersUsernameQ = *o.ExternalServersUsername
	}
	if externalServersUsernameQ != "" {
		qs.Set("external.servers.username", externalServersUsernameQ)
	}

	var fieldsIR []string
	for _, fieldsI := range o.Fields {
		fieldsIS := fieldsI
		if fieldsIS != "" {
			fieldsIR = append(fieldsIR, fieldsIS)
		}
	}

	fields := swag.JoinByFormat(fieldsIR, "csv")

	if len(fields) > 0 {
		qsv := fields[0]
		if qsv != "" {
			qs.Set("fields", qsv)
		}
	}

	var isDefaultDataAtRestEncryptionDisabledQ string
	if o.IsDefaultDataAtRestEncryptionDisabled != nil {
		isDefaultDataAtRestEncryptionDisabledQ = swag.FormatBool(*o.IsDefaultDataAtRestEncryptionDisabled)
	}
	if isDefaultDataAtRestEncryptionDisabledQ != "" {
		qs.Set("is_default_data_at_rest_encryption_disabled", isDefaultDataAtRestEncryptionDisabledQ)
	}

	var maxRecordsQ string
	if o.MaxRecords != nil {
		maxRecordsQ = swag.FormatInt64(*o.MaxRecords)
	}
	if maxRecordsQ != "" {
		qs.Set("max_records", maxRecordsQ)
	}

	var onboardEnabledQ string
	if o.OnboardEnabled != nil {
		onboardEnabledQ = swag.FormatBool(*o.OnboardEnabled)
	}
	if onboardEnabledQ != "" {
		qs.Set("onboard.enabled", onboardEnabledQ)
	}

	var onboardKeyBackupQ string
	if o.OnboardKeyBackup != nil {
		onboardKeyBackupQ = *o.OnboardKeyBackup
	}
	if onboardKeyBackupQ != "" {
		qs.Set("onboard.key_backup", onboardKeyBackupQ)
	}

	var orderByIR []string
	for _, orderByI := range o.OrderBy {
		orderByIS := orderByI
		if orderByIS != "" {
			orderByIR = append(orderByIR, orderByIS)
		}
	}

	orderBy := swag.JoinByFormat(orderByIR, "csv")

	if len(orderBy) > 0 {
		qsv := orderBy[0]
		if qsv != "" {
			qs.Set("order_by", qsv)
		}
	}

	var policyQ string
	if o.Policy != nil {
		policyQ = *o.Policy
	}
	if policyQ != "" {
		qs.Set("policy", policyQ)
	}

	var returnRecordsQ string
	if o.ReturnRecords != nil {
		returnRecordsQ = swag.FormatBool(*o.ReturnRecords)
	}
	if returnRecordsQ != "" {
		qs.Set("return_records", returnRecordsQ)
	}

	var returnTimeoutQ string
	if o.ReturnTimeout != nil {
		returnTimeoutQ = swag.FormatInt64(*o.ReturnTimeout)
	}
	if returnTimeoutQ != "" {
		qs.Set("return_timeout", returnTimeoutQ)
	}

	var scopeQ string
	if o.Scope != nil {
		scopeQ = *o.Scope
	}
	if scopeQ != "" {
		qs.Set("scope", scopeQ)
	}

	var statusCodeQ string
	if o.StatusCode != nil {
		statusCodeQ = swag.FormatInt64(*o.StatusCode)
	}
	if statusCodeQ != "" {
		qs.Set("status.code", statusCodeQ)
	}

	var statusMessageQ string
	if o.StatusMessage != nil {
		statusMessageQ = *o.StatusMessage
	}
	if statusMessageQ != "" {
		qs.Set("status.message", statusMessageQ)
	}

	var svmNameQ string
	if o.SvmName != nil {
		svmNameQ = *o.SvmName
	}
	if svmNameQ != "" {
		qs.Set("svm.name", svmNameQ)
	}

	var svmUUIDQ string
	if o.SvmUUID != nil {
		svmUUIDQ = *o.SvmUUID
	}
	if svmUUIDQ != "" {
		qs.Set("svm.uuid", svmUUIDQ)
	}

	var uuidQ string
	if o.UUID != nil {
		uuidQ = *o.UUID
	}
	if uuidQ != "" {
		qs.Set("uuid", uuidQ)
	}

	var volumeEncryptionCodeQ string
	if o.VolumeEncryptionCode != nil {
		volumeEncryptionCodeQ = swag.FormatInt64(*o.VolumeEncryptionCode)
	}
	if volumeEncryptionCodeQ != "" {
		qs.Set("volume_encryption.code", volumeEncryptionCodeQ)
	}

	var volumeEncryptionMessageQ string
	if o.VolumeEncryptionMessage != nil {
		volumeEncryptionMessageQ = *o.VolumeEncryptionMessage
	}
	if volumeEncryptionMessageQ != "" {
		qs.Set("volume_encryption.message", volumeEncryptionMessageQ)
	}

	var volumeEncryptionSupportedQ string
	if o.VolumeEncryptionSupported != nil {
		volumeEncryptionSupportedQ = swag.FormatBool(*o.VolumeEncryptionSupported)
	}
	if volumeEncryptionSupportedQ != "" {
		qs.Set("volume_encryption.supported", volumeEncryptionSupportedQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *SecurityKeyManagerCollectionGetURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *SecurityKeyManagerCollectionGetURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *SecurityKeyManagerCollectionGetURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on SecurityKeyManagerCollectionGetURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on SecurityKeyManagerCollectionGetURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *SecurityKeyManagerCollectionGetURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
