// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SecurityCertificateSignHandlerFunc turns a function with the right signature into a security certificate sign handler
type SecurityCertificateSignHandlerFunc func(SecurityCertificateSignParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SecurityCertificateSignHandlerFunc) Handle(params SecurityCertificateSignParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SecurityCertificateSignHandler interface for that can handle valid security certificate sign params
type SecurityCertificateSignHandler interface {
	Handle(SecurityCertificateSignParams, interface{}) middleware.Responder
}

// NewSecurityCertificateSign creates a new http.Handler for the security certificate sign operation
func NewSecurityCertificateSign(ctx *middleware.Context, handler SecurityCertificateSignHandler) *SecurityCertificateSign {
	return &SecurityCertificateSign{Context: ctx, Handler: handler}
}

/*
	SecurityCertificateSign swagger:route POST /security/certificates/{ca.uuid}/sign Security securityCertificateSign

Signs a certificate.
### Required properties
* `signing_request` - Certificate signing request to be signed by the given certificate authority.
### Recommended optional properties
* `expiry_time` - Certificate expiration time. Specifying an expiration time for a signed certificate is recommended.
* `hash_function` - Hashing function. Specifying a strong hashing function is recommended when signing a certificate.
### Default property values
If not specified in POST, the following default property values are assigned:
* `expiry_time` - _P365DT_
* `hash_function` - _sha256_
### Related ONTAP commands
* `security certificate sign`
This API is used to sign a certificate request using a pre-existing self-signed root certificate. The self-signed root certificate acts as a certificate authority within its scope and maintains the records of its signed certificates. <br/>
The root certificate can be created for a given SVM or for the cluster using [`POST security/certificates`].<br/>
*/
type SecurityCertificateSign struct {
	Context *middleware.Context
	Handler SecurityCertificateSignHandler
}

func (o *SecurityCertificateSign) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSecurityCertificateSignParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
