// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// SecurityLogForwardingDeleteOKCode is the HTTP code returned for type SecurityLogForwardingDeleteOK
const SecurityLogForwardingDeleteOKCode int = 200

/*
SecurityLogForwardingDeleteOK OK

swagger:response securityLogForwardingDeleteOK
*/
type SecurityLogForwardingDeleteOK struct {
}

// NewSecurityLogForwardingDeleteOK creates SecurityLogForwardingDeleteOK with default headers values
func NewSecurityLogForwardingDeleteOK() *SecurityLogForwardingDeleteOK {

	return &SecurityLogForwardingDeleteOK{}
}

// WriteResponse to the client
func (o *SecurityLogForwardingDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
SecurityLogForwardingDeleteDefault Error

swagger:response securityLogForwardingDeleteDefault
*/
type SecurityLogForwardingDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSecurityLogForwardingDeleteDefault creates SecurityLogForwardingDeleteDefault with default headers values
func NewSecurityLogForwardingDeleteDefault(code int) *SecurityLogForwardingDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &SecurityLogForwardingDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the security log forwarding delete default response
func (o *SecurityLogForwardingDeleteDefault) WithStatusCode(code int) *SecurityLogForwardingDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the security log forwarding delete default response
func (o *SecurityLogForwardingDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the security log forwarding delete default response
func (o *SecurityLogForwardingDeleteDefault) WithPayload(payload *models.ErrorResponse) *SecurityLogForwardingDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the security log forwarding delete default response
func (o *SecurityLogForwardingDeleteDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SecurityLogForwardingDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
