// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SecurityKeyManagerKeyServersCreateHandlerFunc turns a function with the right signature into a security key manager key servers create handler
type SecurityKeyManagerKeyServersCreateHandlerFunc func(SecurityKeyManagerKeyServersCreateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SecurityKeyManagerKeyServersCreateHandlerFunc) Handle(params SecurityKeyManagerKeyServersCreateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SecurityKeyManagerKeyServersCreateHandler interface for that can handle valid security key manager key servers create params
type SecurityKeyManagerKeyServersCreateHandler interface {
	Handle(SecurityKeyManagerKeyServersCreateParams, interface{}) middleware.Responder
}

// NewSecurityKeyManagerKeyServersCreate creates a new http.Handler for the security key manager key servers create operation
func NewSecurityKeyManagerKeyServersCreate(ctx *middleware.Context, handler SecurityKeyManagerKeyServersCreateHandler) *SecurityKeyManagerKeyServersCreate {
	return &SecurityKeyManagerKeyServersCreate{Context: ctx, Handler: handler}
}

/*
	SecurityKeyManagerKeyServersCreate swagger:route POST /security/key-managers/{uuid}/key-servers Security securityKeyManagerKeyServersCreate

Adds primary key servers to a configured external key manager.
### Required properties
* `uuid` - UUID of the external key manager.
* `server` - Primary Key server name.
### Related ONTAP commands
* `security key-manager external add-servers`
*/
type SecurityKeyManagerKeyServersCreate struct {
	Context *middleware.Context
	Handler SecurityKeyManagerKeyServersCreateHandler
}

func (o *SecurityKeyManagerKeyServersCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSecurityKeyManagerKeyServersCreateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
