// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewSecurityKeyManagerCollectionGetParams creates a new SecurityKeyManagerCollectionGetParams object
// with the default values initialized.
func NewSecurityKeyManagerCollectionGetParams() SecurityKeyManagerCollectionGetParams {

	var (
		// initialize parameters with default values

		returnRecordsDefault = bool(true)
		returnTimeoutDefault = int64(15)
	)

	return SecurityKeyManagerCollectionGetParams{
		ReturnRecords: &returnRecordsDefault,

		ReturnTimeout: &returnTimeoutDefault,
	}
}

// SecurityKeyManagerCollectionGetParams contains all the bound params for the security key manager collection get operation
// typically these are obtained from a http.Request
//
// swagger:parameters security_key_manager_collection_get
type SecurityKeyManagerCollectionGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Filter by external.client_certificate.name
	  In: query
	*/
	ExternalClientCertificateName *string
	/*Filter by external.client_certificate.uuid
	  In: query
	*/
	ExternalClientCertificateUUID *string
	/*Filter by external.server_ca_certificates.name
	  In: query
	*/
	ExternalServerCaCertificatesName *string
	/*Filter by external.server_ca_certificates.uuid
	  In: query
	*/
	ExternalServerCaCertificatesUUID *string
	/*Filter by external.servers.connectivity.cluster_availability
	  In: query
	*/
	ExternalServersConnectivityClusterAvailability *bool
	/*Filter by external.servers.connectivity.node_states.node.name
	  In: query
	*/
	ExternalServersConnectivityNodeStatesNodeName *string
	/*Filter by external.servers.connectivity.node_states.node.uuid
	  In: query
	*/
	ExternalServersConnectivityNodeStatesNodeUUID *string
	/*Filter by external.servers.connectivity.node_states.state
	  In: query
	*/
	ExternalServersConnectivityNodeStatesState *string
	/*Filter by external.servers.secondary_key_servers
	  In: query
	*/
	ExternalServersSecondaryKeyServers *string
	/*Filter by external.servers.server
	  In: query
	*/
	ExternalServersServer *string
	/*Filter by external.servers.timeout
	  Maximum: 60
	  Minimum: 1
	  In: query
	*/
	ExternalServersTimeout *int64
	/*Filter by external.servers.username
	  In: query
	*/
	ExternalServersUsername *string
	/*Specify the fields to return.
	  In: query
	  Collection Format: csv
	*/
	Fields []string
	/*Filter by is_default_data_at_rest_encryption_disabled
	  In: query
	*/
	IsDefaultDataAtRestEncryptionDisabled *bool
	/*Limit the number of records returned.
	  In: query
	*/
	MaxRecords *int64
	/*Filter by onboard.enabled
	  In: query
	*/
	OnboardEnabled *bool
	/*Filter by onboard.key_backup
	  In: query
	*/
	OnboardKeyBackup *string
	/*Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.
	  In: query
	  Collection Format: csv
	*/
	OrderBy []string
	/*Filter by policy
	  In: query
	*/
	Policy *string
	/*The default is true for GET calls.  When set to false, only the number of records is returned.
	  In: query
	  Default: true
	*/
	ReturnRecords *bool
	/*The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.
	  Maximum: 120
	  Minimum: 0
	  In: query
	  Default: 15
	*/
	ReturnTimeout *int64
	/*Filter by scope
	  In: query
	*/
	Scope *string
	/*Filter by status.code
	  In: query
	*/
	StatusCode *int64
	/*Filter by status.message
	  In: query
	*/
	StatusMessage *string
	/*Filter by svm.name
	  In: query
	*/
	SvmName *string
	/*Filter by svm.uuid
	  In: query
	*/
	SvmUUID *string
	/*Filter by uuid
	  In: query
	*/
	UUID *string
	/*Filter by volume_encryption.code
	  In: query
	*/
	VolumeEncryptionCode *int64
	/*Filter by volume_encryption.message
	  In: query
	*/
	VolumeEncryptionMessage *string
	/*Filter by volume_encryption.supported
	  In: query
	*/
	VolumeEncryptionSupported *bool
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSecurityKeyManagerCollectionGetParams() beforehand.
func (o *SecurityKeyManagerCollectionGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qExternalClientCertificateName, qhkExternalClientCertificateName, _ := qs.GetOK("external.client_certificate.name")
	if err := o.bindExternalClientCertificateName(qExternalClientCertificateName, qhkExternalClientCertificateName, route.Formats); err != nil {
		res = append(res, err)
	}

	qExternalClientCertificateUUID, qhkExternalClientCertificateUUID, _ := qs.GetOK("external.client_certificate.uuid")
	if err := o.bindExternalClientCertificateUUID(qExternalClientCertificateUUID, qhkExternalClientCertificateUUID, route.Formats); err != nil {
		res = append(res, err)
	}

	qExternalServerCaCertificatesName, qhkExternalServerCaCertificatesName, _ := qs.GetOK("external.server_ca_certificates.name")
	if err := o.bindExternalServerCaCertificatesName(qExternalServerCaCertificatesName, qhkExternalServerCaCertificatesName, route.Formats); err != nil {
		res = append(res, err)
	}

	qExternalServerCaCertificatesUUID, qhkExternalServerCaCertificatesUUID, _ := qs.GetOK("external.server_ca_certificates.uuid")
	if err := o.bindExternalServerCaCertificatesUUID(qExternalServerCaCertificatesUUID, qhkExternalServerCaCertificatesUUID, route.Formats); err != nil {
		res = append(res, err)
	}

	qExternalServersConnectivityClusterAvailability, qhkExternalServersConnectivityClusterAvailability, _ := qs.GetOK("external.servers.connectivity.cluster_availability")
	if err := o.bindExternalServersConnectivityClusterAvailability(qExternalServersConnectivityClusterAvailability, qhkExternalServersConnectivityClusterAvailability, route.Formats); err != nil {
		res = append(res, err)
	}

	qExternalServersConnectivityNodeStatesNodeName, qhkExternalServersConnectivityNodeStatesNodeName, _ := qs.GetOK("external.servers.connectivity.node_states.node.name")
	if err := o.bindExternalServersConnectivityNodeStatesNodeName(qExternalServersConnectivityNodeStatesNodeName, qhkExternalServersConnectivityNodeStatesNodeName, route.Formats); err != nil {
		res = append(res, err)
	}

	qExternalServersConnectivityNodeStatesNodeUUID, qhkExternalServersConnectivityNodeStatesNodeUUID, _ := qs.GetOK("external.servers.connectivity.node_states.node.uuid")
	if err := o.bindExternalServersConnectivityNodeStatesNodeUUID(qExternalServersConnectivityNodeStatesNodeUUID, qhkExternalServersConnectivityNodeStatesNodeUUID, route.Formats); err != nil {
		res = append(res, err)
	}

	qExternalServersConnectivityNodeStatesState, qhkExternalServersConnectivityNodeStatesState, _ := qs.GetOK("external.servers.connectivity.node_states.state")
	if err := o.bindExternalServersConnectivityNodeStatesState(qExternalServersConnectivityNodeStatesState, qhkExternalServersConnectivityNodeStatesState, route.Formats); err != nil {
		res = append(res, err)
	}

	qExternalServersSecondaryKeyServers, qhkExternalServersSecondaryKeyServers, _ := qs.GetOK("external.servers.secondary_key_servers")
	if err := o.bindExternalServersSecondaryKeyServers(qExternalServersSecondaryKeyServers, qhkExternalServersSecondaryKeyServers, route.Formats); err != nil {
		res = append(res, err)
	}

	qExternalServersServer, qhkExternalServersServer, _ := qs.GetOK("external.servers.server")
	if err := o.bindExternalServersServer(qExternalServersServer, qhkExternalServersServer, route.Formats); err != nil {
		res = append(res, err)
	}

	qExternalServersTimeout, qhkExternalServersTimeout, _ := qs.GetOK("external.servers.timeout")
	if err := o.bindExternalServersTimeout(qExternalServersTimeout, qhkExternalServersTimeout, route.Formats); err != nil {
		res = append(res, err)
	}

	qExternalServersUsername, qhkExternalServersUsername, _ := qs.GetOK("external.servers.username")
	if err := o.bindExternalServersUsername(qExternalServersUsername, qhkExternalServersUsername, route.Formats); err != nil {
		res = append(res, err)
	}

	qFields, qhkFields, _ := qs.GetOK("fields")
	if err := o.bindFields(qFields, qhkFields, route.Formats); err != nil {
		res = append(res, err)
	}

	qIsDefaultDataAtRestEncryptionDisabled, qhkIsDefaultDataAtRestEncryptionDisabled, _ := qs.GetOK("is_default_data_at_rest_encryption_disabled")
	if err := o.bindIsDefaultDataAtRestEncryptionDisabled(qIsDefaultDataAtRestEncryptionDisabled, qhkIsDefaultDataAtRestEncryptionDisabled, route.Formats); err != nil {
		res = append(res, err)
	}

	qMaxRecords, qhkMaxRecords, _ := qs.GetOK("max_records")
	if err := o.bindMaxRecords(qMaxRecords, qhkMaxRecords, route.Formats); err != nil {
		res = append(res, err)
	}

	qOnboardEnabled, qhkOnboardEnabled, _ := qs.GetOK("onboard.enabled")
	if err := o.bindOnboardEnabled(qOnboardEnabled, qhkOnboardEnabled, route.Formats); err != nil {
		res = append(res, err)
	}

	qOnboardKeyBackup, qhkOnboardKeyBackup, _ := qs.GetOK("onboard.key_backup")
	if err := o.bindOnboardKeyBackup(qOnboardKeyBackup, qhkOnboardKeyBackup, route.Formats); err != nil {
		res = append(res, err)
	}

	qOrderBy, qhkOrderBy, _ := qs.GetOK("order_by")
	if err := o.bindOrderBy(qOrderBy, qhkOrderBy, route.Formats); err != nil {
		res = append(res, err)
	}

	qPolicy, qhkPolicy, _ := qs.GetOK("policy")
	if err := o.bindPolicy(qPolicy, qhkPolicy, route.Formats); err != nil {
		res = append(res, err)
	}

	qReturnRecords, qhkReturnRecords, _ := qs.GetOK("return_records")
	if err := o.bindReturnRecords(qReturnRecords, qhkReturnRecords, route.Formats); err != nil {
		res = append(res, err)
	}

	qReturnTimeout, qhkReturnTimeout, _ := qs.GetOK("return_timeout")
	if err := o.bindReturnTimeout(qReturnTimeout, qhkReturnTimeout, route.Formats); err != nil {
		res = append(res, err)
	}

	qScope, qhkScope, _ := qs.GetOK("scope")
	if err := o.bindScope(qScope, qhkScope, route.Formats); err != nil {
		res = append(res, err)
	}

	qStatusCode, qhkStatusCode, _ := qs.GetOK("status.code")
	if err := o.bindStatusCode(qStatusCode, qhkStatusCode, route.Formats); err != nil {
		res = append(res, err)
	}

	qStatusMessage, qhkStatusMessage, _ := qs.GetOK("status.message")
	if err := o.bindStatusMessage(qStatusMessage, qhkStatusMessage, route.Formats); err != nil {
		res = append(res, err)
	}

	qSvmName, qhkSvmName, _ := qs.GetOK("svm.name")
	if err := o.bindSvmName(qSvmName, qhkSvmName, route.Formats); err != nil {
		res = append(res, err)
	}

	qSvmUUID, qhkSvmUUID, _ := qs.GetOK("svm.uuid")
	if err := o.bindSvmUUID(qSvmUUID, qhkSvmUUID, route.Formats); err != nil {
		res = append(res, err)
	}

	qUUID, qhkUUID, _ := qs.GetOK("uuid")
	if err := o.bindUUID(qUUID, qhkUUID, route.Formats); err != nil {
		res = append(res, err)
	}

	qVolumeEncryptionCode, qhkVolumeEncryptionCode, _ := qs.GetOK("volume_encryption.code")
	if err := o.bindVolumeEncryptionCode(qVolumeEncryptionCode, qhkVolumeEncryptionCode, route.Formats); err != nil {
		res = append(res, err)
	}

	qVolumeEncryptionMessage, qhkVolumeEncryptionMessage, _ := qs.GetOK("volume_encryption.message")
	if err := o.bindVolumeEncryptionMessage(qVolumeEncryptionMessage, qhkVolumeEncryptionMessage, route.Formats); err != nil {
		res = append(res, err)
	}

	qVolumeEncryptionSupported, qhkVolumeEncryptionSupported, _ := qs.GetOK("volume_encryption.supported")
	if err := o.bindVolumeEncryptionSupported(qVolumeEncryptionSupported, qhkVolumeEncryptionSupported, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindExternalClientCertificateName binds and validates parameter ExternalClientCertificateName from query.
func (o *SecurityKeyManagerCollectionGetParams) bindExternalClientCertificateName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ExternalClientCertificateName = &raw

	return nil
}

// bindExternalClientCertificateUUID binds and validates parameter ExternalClientCertificateUUID from query.
func (o *SecurityKeyManagerCollectionGetParams) bindExternalClientCertificateUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ExternalClientCertificateUUID = &raw

	return nil
}

// bindExternalServerCaCertificatesName binds and validates parameter ExternalServerCaCertificatesName from query.
func (o *SecurityKeyManagerCollectionGetParams) bindExternalServerCaCertificatesName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ExternalServerCaCertificatesName = &raw

	return nil
}

// bindExternalServerCaCertificatesUUID binds and validates parameter ExternalServerCaCertificatesUUID from query.
func (o *SecurityKeyManagerCollectionGetParams) bindExternalServerCaCertificatesUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ExternalServerCaCertificatesUUID = &raw

	return nil
}

// bindExternalServersConnectivityClusterAvailability binds and validates parameter ExternalServersConnectivityClusterAvailability from query.
func (o *SecurityKeyManagerCollectionGetParams) bindExternalServersConnectivityClusterAvailability(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("external.servers.connectivity.cluster_availability", "query", "bool", raw)
	}
	o.ExternalServersConnectivityClusterAvailability = &value

	return nil
}

// bindExternalServersConnectivityNodeStatesNodeName binds and validates parameter ExternalServersConnectivityNodeStatesNodeName from query.
func (o *SecurityKeyManagerCollectionGetParams) bindExternalServersConnectivityNodeStatesNodeName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ExternalServersConnectivityNodeStatesNodeName = &raw

	return nil
}

// bindExternalServersConnectivityNodeStatesNodeUUID binds and validates parameter ExternalServersConnectivityNodeStatesNodeUUID from query.
func (o *SecurityKeyManagerCollectionGetParams) bindExternalServersConnectivityNodeStatesNodeUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ExternalServersConnectivityNodeStatesNodeUUID = &raw

	return nil
}

// bindExternalServersConnectivityNodeStatesState binds and validates parameter ExternalServersConnectivityNodeStatesState from query.
func (o *SecurityKeyManagerCollectionGetParams) bindExternalServersConnectivityNodeStatesState(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ExternalServersConnectivityNodeStatesState = &raw

	return nil
}

// bindExternalServersSecondaryKeyServers binds and validates parameter ExternalServersSecondaryKeyServers from query.
func (o *SecurityKeyManagerCollectionGetParams) bindExternalServersSecondaryKeyServers(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ExternalServersSecondaryKeyServers = &raw

	return nil
}

// bindExternalServersServer binds and validates parameter ExternalServersServer from query.
func (o *SecurityKeyManagerCollectionGetParams) bindExternalServersServer(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ExternalServersServer = &raw

	return nil
}

// bindExternalServersTimeout binds and validates parameter ExternalServersTimeout from query.
func (o *SecurityKeyManagerCollectionGetParams) bindExternalServersTimeout(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("external.servers.timeout", "query", "int64", raw)
	}
	o.ExternalServersTimeout = &value

	if err := o.validateExternalServersTimeout(formats); err != nil {
		return err
	}

	return nil
}

// validateExternalServersTimeout carries on validations for parameter ExternalServersTimeout
func (o *SecurityKeyManagerCollectionGetParams) validateExternalServersTimeout(formats strfmt.Registry) error {

	if err := validate.MinimumInt("external.servers.timeout", "query", *o.ExternalServersTimeout, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("external.servers.timeout", "query", *o.ExternalServersTimeout, 60, false); err != nil {
		return err
	}

	return nil
}

// bindExternalServersUsername binds and validates parameter ExternalServersUsername from query.
func (o *SecurityKeyManagerCollectionGetParams) bindExternalServersUsername(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ExternalServersUsername = &raw

	return nil
}

// bindFields binds and validates array parameter Fields from query.
//
// Arrays are parsed according to CollectionFormat: "csv" (defaults to "csv" when empty).
func (o *SecurityKeyManagerCollectionGetParams) bindFields(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var qvFields string
	if len(rawData) > 0 {
		qvFields = rawData[len(rawData)-1]
	}

	// CollectionFormat: csv
	fieldsIC := swag.SplitByFormat(qvFields, "csv")
	if len(fieldsIC) == 0 {
		return nil
	}

	var fieldsIR []string
	for _, fieldsIV := range fieldsIC {
		fieldsI := fieldsIV

		fieldsIR = append(fieldsIR, fieldsI)
	}

	o.Fields = fieldsIR

	return nil
}

// bindIsDefaultDataAtRestEncryptionDisabled binds and validates parameter IsDefaultDataAtRestEncryptionDisabled from query.
func (o *SecurityKeyManagerCollectionGetParams) bindIsDefaultDataAtRestEncryptionDisabled(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("is_default_data_at_rest_encryption_disabled", "query", "bool", raw)
	}
	o.IsDefaultDataAtRestEncryptionDisabled = &value

	return nil
}

// bindMaxRecords binds and validates parameter MaxRecords from query.
func (o *SecurityKeyManagerCollectionGetParams) bindMaxRecords(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("max_records", "query", "int64", raw)
	}
	o.MaxRecords = &value

	return nil
}

// bindOnboardEnabled binds and validates parameter OnboardEnabled from query.
func (o *SecurityKeyManagerCollectionGetParams) bindOnboardEnabled(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("onboard.enabled", "query", "bool", raw)
	}
	o.OnboardEnabled = &value

	return nil
}

// bindOnboardKeyBackup binds and validates parameter OnboardKeyBackup from query.
func (o *SecurityKeyManagerCollectionGetParams) bindOnboardKeyBackup(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.OnboardKeyBackup = &raw

	return nil
}

// bindOrderBy binds and validates array parameter OrderBy from query.
//
// Arrays are parsed according to CollectionFormat: "csv" (defaults to "csv" when empty).
func (o *SecurityKeyManagerCollectionGetParams) bindOrderBy(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var qvOrderBy string
	if len(rawData) > 0 {
		qvOrderBy = rawData[len(rawData)-1]
	}

	// CollectionFormat: csv
	orderByIC := swag.SplitByFormat(qvOrderBy, "csv")
	if len(orderByIC) == 0 {
		return nil
	}

	var orderByIR []string
	for _, orderByIV := range orderByIC {
		orderByI := orderByIV

		orderByIR = append(orderByIR, orderByI)
	}

	o.OrderBy = orderByIR

	return nil
}

// bindPolicy binds and validates parameter Policy from query.
func (o *SecurityKeyManagerCollectionGetParams) bindPolicy(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Policy = &raw

	return nil
}

// bindReturnRecords binds and validates parameter ReturnRecords from query.
func (o *SecurityKeyManagerCollectionGetParams) bindReturnRecords(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewSecurityKeyManagerCollectionGetParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("return_records", "query", "bool", raw)
	}
	o.ReturnRecords = &value

	return nil
}

// bindReturnTimeout binds and validates parameter ReturnTimeout from query.
func (o *SecurityKeyManagerCollectionGetParams) bindReturnTimeout(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewSecurityKeyManagerCollectionGetParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("return_timeout", "query", "int64", raw)
	}
	o.ReturnTimeout = &value

	if err := o.validateReturnTimeout(formats); err != nil {
		return err
	}

	return nil
}

// validateReturnTimeout carries on validations for parameter ReturnTimeout
func (o *SecurityKeyManagerCollectionGetParams) validateReturnTimeout(formats strfmt.Registry) error {

	if err := validate.MinimumInt("return_timeout", "query", *o.ReturnTimeout, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("return_timeout", "query", *o.ReturnTimeout, 120, false); err != nil {
		return err
	}

	return nil
}

// bindScope binds and validates parameter Scope from query.
func (o *SecurityKeyManagerCollectionGetParams) bindScope(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Scope = &raw

	return nil
}

// bindStatusCode binds and validates parameter StatusCode from query.
func (o *SecurityKeyManagerCollectionGetParams) bindStatusCode(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("status.code", "query", "int64", raw)
	}
	o.StatusCode = &value

	return nil
}

// bindStatusMessage binds and validates parameter StatusMessage from query.
func (o *SecurityKeyManagerCollectionGetParams) bindStatusMessage(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.StatusMessage = &raw

	return nil
}

// bindSvmName binds and validates parameter SvmName from query.
func (o *SecurityKeyManagerCollectionGetParams) bindSvmName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.SvmName = &raw

	return nil
}

// bindSvmUUID binds and validates parameter SvmUUID from query.
func (o *SecurityKeyManagerCollectionGetParams) bindSvmUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.SvmUUID = &raw

	return nil
}

// bindUUID binds and validates parameter UUID from query.
func (o *SecurityKeyManagerCollectionGetParams) bindUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.UUID = &raw

	return nil
}

// bindVolumeEncryptionCode binds and validates parameter VolumeEncryptionCode from query.
func (o *SecurityKeyManagerCollectionGetParams) bindVolumeEncryptionCode(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("volume_encryption.code", "query", "int64", raw)
	}
	o.VolumeEncryptionCode = &value

	return nil
}

// bindVolumeEncryptionMessage binds and validates parameter VolumeEncryptionMessage from query.
func (o *SecurityKeyManagerCollectionGetParams) bindVolumeEncryptionMessage(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.VolumeEncryptionMessage = &raw

	return nil
}

// bindVolumeEncryptionSupported binds and validates parameter VolumeEncryptionSupported from query.
func (o *SecurityKeyManagerCollectionGetParams) bindVolumeEncryptionSupported(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("volume_encryption.supported", "query", "bool", raw)
	}
	o.VolumeEncryptionSupported = &value

	return nil
}
