// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// ConsistencyGroupCollectionGetOKCode is the HTTP code returned for type ConsistencyGroupCollectionGetOK
const ConsistencyGroupCollectionGetOKCode int = 200

/*
ConsistencyGroupCollectionGetOK OK

swagger:response consistencyGroupCollectionGetOK
*/
type ConsistencyGroupCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.ConsistencyGroupResponse `json:"body,omitempty"`
}

// NewConsistencyGroupCollectionGetOK creates ConsistencyGroupCollectionGetOK with default headers values
func NewConsistencyGroupCollectionGetOK() *ConsistencyGroupCollectionGetOK {

	return &ConsistencyGroupCollectionGetOK{}
}

// WithPayload adds the payload to the consistency group collection get o k response
func (o *ConsistencyGroupCollectionGetOK) WithPayload(payload *models.ConsistencyGroupResponse) *ConsistencyGroupCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the consistency group collection get o k response
func (o *ConsistencyGroupCollectionGetOK) SetPayload(payload *models.ConsistencyGroupResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConsistencyGroupCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
ConsistencyGroupCollectionGetDefault Error

swagger:response consistencyGroupCollectionGetDefault
*/
type ConsistencyGroupCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewConsistencyGroupCollectionGetDefault creates ConsistencyGroupCollectionGetDefault with default headers values
func NewConsistencyGroupCollectionGetDefault(code int) *ConsistencyGroupCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &ConsistencyGroupCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the consistency group collection get default response
func (o *ConsistencyGroupCollectionGetDefault) WithStatusCode(code int) *ConsistencyGroupCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the consistency group collection get default response
func (o *ConsistencyGroupCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the consistency group collection get default response
func (o *ConsistencyGroupCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *ConsistencyGroupCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the consistency group collection get default response
func (o *ConsistencyGroupCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConsistencyGroupCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
