// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ConsistencyGroupSnapshotDeleteHandlerFunc turns a function with the right signature into a consistency group snapshot delete handler
type ConsistencyGroupSnapshotDeleteHandlerFunc func(ConsistencyGroupSnapshotDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ConsistencyGroupSnapshotDeleteHandlerFunc) Handle(params ConsistencyGroupSnapshotDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ConsistencyGroupSnapshotDeleteHandler interface for that can handle valid consistency group snapshot delete params
type ConsistencyGroupSnapshotDeleteHandler interface {
	Handle(ConsistencyGroupSnapshotDeleteParams, interface{}) middleware.Responder
}

// NewConsistencyGroupSnapshotDelete creates a new http.Handler for the consistency group snapshot delete operation
func NewConsistencyGroupSnapshotDelete(ctx *middleware.Context, handler ConsistencyGroupSnapshotDeleteHandler) *ConsistencyGroupSnapshotDelete {
	return &ConsistencyGroupSnapshotDelete{Context: ctx, Handler: handler}
}

/*
	ConsistencyGroupSnapshotDelete swagger:route DELETE /application/consistency-groups/{consistency_group.uuid}/snapshots/{uuid} Application consistencyGroupSnapshotDelete

Deletes a Snapshot copy of a consistency group.
## Examples
*/
type ConsistencyGroupSnapshotDelete struct {
	Context *middleware.Context
	Handler ConsistencyGroupSnapshotDeleteHandler
}

func (o *ConsistencyGroupSnapshotDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewConsistencyGroupSnapshotDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
