// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// ConsistencyGroupSnapshotDeleteOKCode is the HTTP code returned for type ConsistencyGroupSnapshotDeleteOK
const ConsistencyGroupSnapshotDeleteOKCode int = 200

/*
ConsistencyGroupSnapshotDeleteOK OK

swagger:response consistencyGroupSnapshotDeleteOK
*/
type ConsistencyGroupSnapshotDeleteOK struct {
}

// NewConsistencyGroupSnapshotDeleteOK creates ConsistencyGroupSnapshotDeleteOK with default headers values
func NewConsistencyGroupSnapshotDeleteOK() *ConsistencyGroupSnapshotDeleteOK {

	return &ConsistencyGroupSnapshotDeleteOK{}
}

// WriteResponse to the client
func (o *ConsistencyGroupSnapshotDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// ConsistencyGroupSnapshotDeleteAcceptedCode is the HTTP code returned for type ConsistencyGroupSnapshotDeleteAccepted
const ConsistencyGroupSnapshotDeleteAcceptedCode int = 202

/*
ConsistencyGroupSnapshotDeleteAccepted Accepted

swagger:response consistencyGroupSnapshotDeleteAccepted
*/
type ConsistencyGroupSnapshotDeleteAccepted struct {
}

// NewConsistencyGroupSnapshotDeleteAccepted creates ConsistencyGroupSnapshotDeleteAccepted with default headers values
func NewConsistencyGroupSnapshotDeleteAccepted() *ConsistencyGroupSnapshotDeleteAccepted {

	return &ConsistencyGroupSnapshotDeleteAccepted{}
}

// WriteResponse to the client
func (o *ConsistencyGroupSnapshotDeleteAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(202)
}

/*
ConsistencyGroupSnapshotDeleteDefault Error

swagger:response consistencyGroupSnapshotDeleteDefault
*/
type ConsistencyGroupSnapshotDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewConsistencyGroupSnapshotDeleteDefault creates ConsistencyGroupSnapshotDeleteDefault with default headers values
func NewConsistencyGroupSnapshotDeleteDefault(code int) *ConsistencyGroupSnapshotDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &ConsistencyGroupSnapshotDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the consistency group snapshot delete default response
func (o *ConsistencyGroupSnapshotDeleteDefault) WithStatusCode(code int) *ConsistencyGroupSnapshotDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the consistency group snapshot delete default response
func (o *ConsistencyGroupSnapshotDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the consistency group snapshot delete default response
func (o *ConsistencyGroupSnapshotDeleteDefault) WithPayload(payload *models.ErrorResponse) *ConsistencyGroupSnapshotDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the consistency group snapshot delete default response
func (o *ConsistencyGroupSnapshotDeleteDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConsistencyGroupSnapshotDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
