// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ConsistencyGroupSnapshotCollectionGetHandlerFunc turns a function with the right signature into a consistency group snapshot collection get handler
type ConsistencyGroupSnapshotCollectionGetHandlerFunc func(ConsistencyGroupSnapshotCollectionGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ConsistencyGroupSnapshotCollectionGetHandlerFunc) Handle(params ConsistencyGroupSnapshotCollectionGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ConsistencyGroupSnapshotCollectionGetHandler interface for that can handle valid consistency group snapshot collection get params
type ConsistencyGroupSnapshotCollectionGetHandler interface {
	Handle(ConsistencyGroupSnapshotCollectionGetParams, interface{}) middleware.Responder
}

// NewConsistencyGroupSnapshotCollectionGet creates a new http.Handler for the consistency group snapshot collection get operation
func NewConsistencyGroupSnapshotCollectionGet(ctx *middleware.Context, handler ConsistencyGroupSnapshotCollectionGetHandler) *ConsistencyGroupSnapshotCollectionGet {
	return &ConsistencyGroupSnapshotCollectionGet{Context: ctx, Handler: handler}
}

/*
	ConsistencyGroupSnapshotCollectionGet swagger:route GET /application/consistency-groups/{consistency_group.uuid}/snapshots Application consistencyGroupSnapshotCollectionGet

Retrieves Snapshot copies for a consistency group.
## Expensive properties
There is an added computational cost to retrieving values for these properties. They are not included by default in GET results and must be explicitly requested using the `fields` query parameter. See [`DOC Requesting specific fields`](#docs-docs-Requesting-specific-fields) to learn more.
* `is_partial`
* `missing_voumes.uuid`
* `missing_voumes.name`
*/
type ConsistencyGroupSnapshotCollectionGet struct {
	Context *middleware.Context
	Handler ConsistencyGroupSnapshotCollectionGetHandler
}

func (o *ConsistencyGroupSnapshotCollectionGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewConsistencyGroupSnapshotCollectionGetParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
