// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// ConsistencyGroupSnapshotGetOKCode is the HTTP code returned for type ConsistencyGroupSnapshotGetOK
const ConsistencyGroupSnapshotGetOKCode int = 200

/*
ConsistencyGroupSnapshotGetOK OK

swagger:response consistencyGroupSnapshotGetOK
*/
type ConsistencyGroupSnapshotGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.ConsistencyGroupSnapshot `json:"body,omitempty"`
}

// NewConsistencyGroupSnapshotGetOK creates ConsistencyGroupSnapshotGetOK with default headers values
func NewConsistencyGroupSnapshotGetOK() *ConsistencyGroupSnapshotGetOK {

	return &ConsistencyGroupSnapshotGetOK{}
}

// WithPayload adds the payload to the consistency group snapshot get o k response
func (o *ConsistencyGroupSnapshotGetOK) WithPayload(payload *models.ConsistencyGroupSnapshot) *ConsistencyGroupSnapshotGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the consistency group snapshot get o k response
func (o *ConsistencyGroupSnapshotGetOK) SetPayload(payload *models.ConsistencyGroupSnapshot) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConsistencyGroupSnapshotGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
ConsistencyGroupSnapshotGetDefault Error

swagger:response consistencyGroupSnapshotGetDefault
*/
type ConsistencyGroupSnapshotGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewConsistencyGroupSnapshotGetDefault creates ConsistencyGroupSnapshotGetDefault with default headers values
func NewConsistencyGroupSnapshotGetDefault(code int) *ConsistencyGroupSnapshotGetDefault {
	if code <= 0 {
		code = 500
	}

	return &ConsistencyGroupSnapshotGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the consistency group snapshot get default response
func (o *ConsistencyGroupSnapshotGetDefault) WithStatusCode(code int) *ConsistencyGroupSnapshotGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the consistency group snapshot get default response
func (o *ConsistencyGroupSnapshotGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the consistency group snapshot get default response
func (o *ConsistencyGroupSnapshotGetDefault) WithPayload(payload *models.ErrorResponse) *ConsistencyGroupSnapshotGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the consistency group snapshot get default response
func (o *ConsistencyGroupSnapshotGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConsistencyGroupSnapshotGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
