// Code generated by go-swagger; DO NOT EDIT.

package s_vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// SvmMigrationCollectionGetOKCode is the HTTP code returned for type SvmMigrationCollectionGetOK
const SvmMigrationCollectionGetOKCode int = 200

/*
SvmMigrationCollectionGetOK OK

swagger:response svmMigrationCollectionGetOK
*/
type SvmMigrationCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.SvmMigrationResponse `json:"body,omitempty"`
}

// NewSvmMigrationCollectionGetOK creates SvmMigrationCollectionGetOK with default headers values
func NewSvmMigrationCollectionGetOK() *SvmMigrationCollectionGetOK {

	return &SvmMigrationCollectionGetOK{}
}

// WithPayload adds the payload to the svm migration collection get o k response
func (o *SvmMigrationCollectionGetOK) WithPayload(payload *models.SvmMigrationResponse) *SvmMigrationCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the svm migration collection get o k response
func (o *SvmMigrationCollectionGetOK) SetPayload(payload *models.SvmMigrationResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SvmMigrationCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
SvmMigrationCollectionGetDefault ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 13172783 | Migrate RDB lookup failed |
Also see the table of common errors in the <a href="#Response_body">Response body</a> overview section of this documentation.

swagger:response svmMigrationCollectionGetDefault
*/
type SvmMigrationCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSvmMigrationCollectionGetDefault creates SvmMigrationCollectionGetDefault with default headers values
func NewSvmMigrationCollectionGetDefault(code int) *SvmMigrationCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &SvmMigrationCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the svm migration collection get default response
func (o *SvmMigrationCollectionGetDefault) WithStatusCode(code int) *SvmMigrationCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the svm migration collection get default response
func (o *SvmMigrationCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the svm migration collection get default response
func (o *SvmMigrationCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *SvmMigrationCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the svm migration collection get default response
func (o *SvmMigrationCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SvmMigrationCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
