// Code generated by go-swagger; DO NOT EDIT.

package s_vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// SvmMigrationModifyURL generates an URL for the svm migration modify operation
type SvmMigrationModifyURL struct {
	UUID string

	Action            *string
	AutoCutover       *bool
	AutoSourceCleanup *bool
	ReturnTimeout     *int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SvmMigrationModifyURL) WithBasePath(bp string) *SvmMigrationModifyURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SvmMigrationModifyURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *SvmMigrationModifyURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/svm/migrations/{uuid}"

	uuid := o.UUID
	if uuid != "" {
		_path = strings.Replace(_path, "{uuid}", uuid, -1)
	} else {
		return nil, errors.New("uuid is required on SvmMigrationModifyURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var actionQ string
	if o.Action != nil {
		actionQ = *o.Action
	}
	if actionQ != "" {
		qs.Set("action", actionQ)
	}

	var autoCutoverQ string
	if o.AutoCutover != nil {
		autoCutoverQ = swag.FormatBool(*o.AutoCutover)
	}
	if autoCutoverQ != "" {
		qs.Set("auto_cutover", autoCutoverQ)
	}

	var autoSourceCleanupQ string
	if o.AutoSourceCleanup != nil {
		autoSourceCleanupQ = swag.FormatBool(*o.AutoSourceCleanup)
	}
	if autoSourceCleanupQ != "" {
		qs.Set("auto_source_cleanup", autoSourceCleanupQ)
	}

	var returnTimeoutQ string
	if o.ReturnTimeout != nil {
		returnTimeoutQ = swag.FormatInt64(*o.ReturnTimeout)
	}
	if returnTimeoutQ != "" {
		qs.Set("return_timeout", returnTimeoutQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *SvmMigrationModifyURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *SvmMigrationModifyURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *SvmMigrationModifyURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on SvmMigrationModifyURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on SvmMigrationModifyURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *SvmMigrationModifyURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
