// Code generated by go-swagger; DO NOT EDIT.

package s_vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/pkg/server/models"
)

// SvmMigrationVolumeCollectionGetOKCode is the HTTP code returned for type SvmMigrationVolumeCollectionGetOK
const SvmMigrationVolumeCollectionGetOKCode int = 200

/*
SvmMigrationVolumeCollectionGetOK OK

swagger:response svmMigrationVolumeCollectionGetOK
*/
type SvmMigrationVolumeCollectionGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.SvmMigrationVolumeResponse `json:"body,omitempty"`
}

// NewSvmMigrationVolumeCollectionGetOK creates SvmMigrationVolumeCollectionGetOK with default headers values
func NewSvmMigrationVolumeCollectionGetOK() *SvmMigrationVolumeCollectionGetOK {

	return &SvmMigrationVolumeCollectionGetOK{}
}

// WithPayload adds the payload to the svm migration volume collection get o k response
func (o *SvmMigrationVolumeCollectionGetOK) WithPayload(payload *models.SvmMigrationVolumeResponse) *SvmMigrationVolumeCollectionGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the svm migration volume collection get o k response
func (o *SvmMigrationVolumeCollectionGetOK) SetPayload(payload *models.SvmMigrationVolumeResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SvmMigrationVolumeCollectionGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
SvmMigrationVolumeCollectionGetDefault ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 13172783 | Migrate RDB lookup failed |
Also see the table of common errors in the <a href="#Response_body">Response body</a> overview section of this documentation.

swagger:response svmMigrationVolumeCollectionGetDefault
*/
type SvmMigrationVolumeCollectionGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSvmMigrationVolumeCollectionGetDefault creates SvmMigrationVolumeCollectionGetDefault with default headers values
func NewSvmMigrationVolumeCollectionGetDefault(code int) *SvmMigrationVolumeCollectionGetDefault {
	if code <= 0 {
		code = 500
	}

	return &SvmMigrationVolumeCollectionGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the svm migration volume collection get default response
func (o *SvmMigrationVolumeCollectionGetDefault) WithStatusCode(code int) *SvmMigrationVolumeCollectionGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the svm migration volume collection get default response
func (o *SvmMigrationVolumeCollectionGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the svm migration volume collection get default response
func (o *SvmMigrationVolumeCollectionGetDefault) WithPayload(payload *models.ErrorResponse) *SvmMigrationVolumeCollectionGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the svm migration volume collection get default response
func (o *SvmMigrationVolumeCollectionGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SvmMigrationVolumeCollectionGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
