// Code generated by go-swagger; DO NOT EDIT.

package n_v_me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// NvmeServiceCreateHandlerFunc turns a function with the right signature into a nvme service create handler
type NvmeServiceCreateHandlerFunc func(NvmeServiceCreateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn NvmeServiceCreateHandlerFunc) Handle(params NvmeServiceCreateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// NvmeServiceCreateHandler interface for that can handle valid nvme service create params
type NvmeServiceCreateHandler interface {
	Handle(NvmeServiceCreateParams, interface{}) middleware.Responder
}

// NewNvmeServiceCreate creates a new http.Handler for the nvme service create operation
func NewNvmeServiceCreate(ctx *middleware.Context, handler NvmeServiceCreateHandler) *NvmeServiceCreate {
	return &NvmeServiceCreate{Context: ctx, Handler: handler}
}

/*
	NvmeServiceCreate swagger:route POST /protocols/nvme/services NVMe nvmeServiceCreate

Creates an NVMe service.

### Required properties
* `svm.uuid` or `svm.name` - The existing SVM in which to create the NVMe service.
### Related ONTAP commands
* `vserver nvme create`
### Learn more
* [`DOC /protocols/nvme/services`](#docs-NVMe-protocols_nvme_services)
*/
type NvmeServiceCreate struct {
	Context *middleware.Context
	Handler NvmeServiceCreateHandler
}

func (o *NvmeServiceCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewNvmeServiceCreateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
