// Code generated by go-swagger; DO NOT EDIT.

package n_v_me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// NvmeSubsystemMapDeleteHandlerFunc turns a function with the right signature into a nvme subsystem map delete handler
type NvmeSubsystemMapDeleteHandlerFunc func(NvmeSubsystemMapDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn NvmeSubsystemMapDeleteHandlerFunc) Handle(params NvmeSubsystemMapDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// NvmeSubsystemMapDeleteHandler interface for that can handle valid nvme subsystem map delete params
type NvmeSubsystemMapDeleteHandler interface {
	Handle(NvmeSubsystemMapDeleteParams, interface{}) middleware.Responder
}

// NewNvmeSubsystemMapDelete creates a new http.Handler for the nvme subsystem map delete operation
func NewNvmeSubsystemMapDelete(ctx *middleware.Context, handler NvmeSubsystemMapDeleteHandler) *NvmeSubsystemMapDelete {
	return &NvmeSubsystemMapDelete{Context: ctx, Handler: handler}
}

/*
	NvmeSubsystemMapDelete swagger:route DELETE /protocols/nvme/subsystem-maps/{subsystem.uuid}/{namespace.uuid} NVMe nvmeSubsystemMapDelete

Deletes an NVMe subsystem map.
### Related ONTAP commands
* `vserver nvme subsystem map remove`
### Learn more
* [`DOC /protocols/nvme/subsystem-maps`](#docs-NVMe-protocols_nvme_subsystem-maps)
*/
type NvmeSubsystemMapDelete struct {
	Context *middleware.Context
	Handler NvmeSubsystemMapDeleteHandler
}

func (o *NvmeSubsystemMapDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewNvmeSubsystemMapDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
