// Code generated by go-swagger; DO NOT EDIT.

package object_store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metal-stack/ontap-go/api/models"
)

// S3GroupModifyOKCode is the HTTP code returned for type S3GroupModifyOK
const S3GroupModifyOKCode int = 200

/*
S3GroupModifyOK OK

swagger:response s3GroupModifyOK
*/
type S3GroupModifyOK struct {
}

// NewS3GroupModifyOK creates S3GroupModifyOK with default headers values
func NewS3GroupModifyOK() *S3GroupModifyOK {

	return &S3GroupModifyOK{}
}

// WriteResponse to the client
func (o *S3GroupModifyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
S3GroupModifyDefault ONTAP Error Response Codes
| Error Code | Description |
| ---------- | ----------- |
| 92405896   | Users list cannot be empty.
| 92405930   | Group name \\\"{group name}\\\" is not valid. Group names must have between 1 and 128 characters.
| 92405931   | Group name \\\"{group name}\\\" contains invalid characters. Valid characters for a group name are 0-9, A-Z, a-z, "_", "+", "=", ",", ".", "@", and "-".
| 92405934   | Users {user name} specified in the user list do not exist for SVM \\\"{vserver name}\\\". Use the \"object-store-server user create\" command to create a user.
| 92405936   | Query characters such as * are not supported in the user list.
| 92405937   | Policies {policy name} specified in the policy list do not exist for SVM \\\"{vserver name}\\\".
| 262222     | User name is present more than once in the users field.
| 2621706    | The specified \\\"{svm.uuid}\\\" and \\\"{svm.name}\\\" refer to different SVMs.
| 92406154   | Users {user} specified in the user list do not exist for SVM "vs1". Use the "/protocols/s3/services/{svm.uuid}/users" endpoint to create a user.

swagger:response s3GroupModifyDefault
*/
type S3GroupModifyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewS3GroupModifyDefault creates S3GroupModifyDefault with default headers values
func NewS3GroupModifyDefault(code int) *S3GroupModifyDefault {
	if code <= 0 {
		code = 500
	}

	return &S3GroupModifyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the s3 group modify default response
func (o *S3GroupModifyDefault) WithStatusCode(code int) *S3GroupModifyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the s3 group modify default response
func (o *S3GroupModifyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the s3 group modify default response
func (o *S3GroupModifyDefault) WithPayload(payload *models.ErrorResponse) *S3GroupModifyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the s3 group modify default response
func (o *S3GroupModifyDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *S3GroupModifyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
